// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "calcola.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic calcola::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic calcola::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<38> calcola::ap_ST_fsm_state1 = "1";
const sc_lv<38> calcola::ap_ST_fsm_state2 = "10";
const sc_lv<38> calcola::ap_ST_fsm_state3 = "100";
const sc_lv<38> calcola::ap_ST_fsm_state4 = "1000";
const sc_lv<38> calcola::ap_ST_fsm_state5 = "10000";
const sc_lv<38> calcola::ap_ST_fsm_state6 = "100000";
const sc_lv<38> calcola::ap_ST_fsm_state7 = "1000000";
const sc_lv<38> calcola::ap_ST_fsm_state8 = "10000000";
const sc_lv<38> calcola::ap_ST_fsm_state9 = "100000000";
const sc_lv<38> calcola::ap_ST_fsm_state10 = "1000000000";
const sc_lv<38> calcola::ap_ST_fsm_state11 = "10000000000";
const sc_lv<38> calcola::ap_ST_fsm_state12 = "100000000000";
const sc_lv<38> calcola::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<38> calcola::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<38> calcola::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<38> calcola::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<38> calcola::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<38> calcola::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<38> calcola::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<38> calcola::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<38> calcola::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<38> calcola::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<38> calcola::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<38> calcola::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<38> calcola::ap_ST_fsm_state25 = "1000000000000000000000000";
const sc_lv<38> calcola::ap_ST_fsm_state26 = "10000000000000000000000000";
const sc_lv<38> calcola::ap_ST_fsm_state27 = "100000000000000000000000000";
const sc_lv<38> calcola::ap_ST_fsm_state28 = "1000000000000000000000000000";
const sc_lv<38> calcola::ap_ST_fsm_state29 = "10000000000000000000000000000";
const sc_lv<38> calcola::ap_ST_fsm_state30 = "100000000000000000000000000000";
const sc_lv<38> calcola::ap_ST_fsm_state31 = "1000000000000000000000000000000";
const sc_lv<38> calcola::ap_ST_fsm_state32 = "10000000000000000000000000000000";
const sc_lv<38> calcola::ap_ST_fsm_state33 = "100000000000000000000000000000000";
const sc_lv<38> calcola::ap_ST_fsm_state34 = "1000000000000000000000000000000000";
const sc_lv<38> calcola::ap_ST_fsm_state35 = "10000000000000000000000000000000000";
const sc_lv<38> calcola::ap_ST_fsm_state36 = "100000000000000000000000000000000000";
const sc_lv<38> calcola::ap_ST_fsm_state37 = "1000000000000000000000000000000000000";
const sc_lv<38> calcola::ap_ST_fsm_state38 = "10000000000000000000000000000000000000";
const int calcola::C_S_AXI_DATA_WIDTH = "100000";
const sc_lv<32> calcola::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> calcola::ap_const_lv1_0 = "0";
const sc_lv<1> calcola::ap_const_lv1_1 = "1";
const sc_lv<32> calcola::ap_const_lv32_24 = "100100";
const sc_lv<32> calcola::ap_const_lv32_25 = "100101";
const sc_lv<32> calcola::ap_const_lv32_23 = "100011";
const sc_lv<8> calcola::ap_const_lv8_2B = "101011";
const sc_lv<8> calcola::ap_const_lv8_2D = "101101";
const sc_lv<8> calcola::ap_const_lv8_2A = "101010";
const sc_lv<8> calcola::ap_const_lv8_2F = "101111";
const bool calcola::ap_const_boolean_1 = true;

calcola::calcola(sc_module_name name) : sc_module(name), mVcdFile(0) {
    calcola_AXILiteS_s_axi_U = new calcola_AXILiteS_s_axi<C_S_AXI_AXILITES_ADDR_WIDTH,C_S_AXI_AXILITES_DATA_WIDTH>("calcola_AXILiteS_s_axi_U");
    calcola_AXILiteS_s_axi_U->AWVALID(s_axi_AXILiteS_AWVALID);
    calcola_AXILiteS_s_axi_U->AWREADY(s_axi_AXILiteS_AWREADY);
    calcola_AXILiteS_s_axi_U->AWADDR(s_axi_AXILiteS_AWADDR);
    calcola_AXILiteS_s_axi_U->WVALID(s_axi_AXILiteS_WVALID);
    calcola_AXILiteS_s_axi_U->WREADY(s_axi_AXILiteS_WREADY);
    calcola_AXILiteS_s_axi_U->WDATA(s_axi_AXILiteS_WDATA);
    calcola_AXILiteS_s_axi_U->WSTRB(s_axi_AXILiteS_WSTRB);
    calcola_AXILiteS_s_axi_U->ARVALID(s_axi_AXILiteS_ARVALID);
    calcola_AXILiteS_s_axi_U->ARREADY(s_axi_AXILiteS_ARREADY);
    calcola_AXILiteS_s_axi_U->ARADDR(s_axi_AXILiteS_ARADDR);
    calcola_AXILiteS_s_axi_U->RVALID(s_axi_AXILiteS_RVALID);
    calcola_AXILiteS_s_axi_U->RREADY(s_axi_AXILiteS_RREADY);
    calcola_AXILiteS_s_axi_U->RDATA(s_axi_AXILiteS_RDATA);
    calcola_AXILiteS_s_axi_U->RRESP(s_axi_AXILiteS_RRESP);
    calcola_AXILiteS_s_axi_U->BVALID(s_axi_AXILiteS_BVALID);
    calcola_AXILiteS_s_axi_U->BREADY(s_axi_AXILiteS_BREADY);
    calcola_AXILiteS_s_axi_U->BRESP(s_axi_AXILiteS_BRESP);
    calcola_AXILiteS_s_axi_U->ACLK(ap_clk);
    calcola_AXILiteS_s_axi_U->ARESET(ap_rst_n_inv);
    calcola_AXILiteS_s_axi_U->ACLK_EN(ap_var_for_const0);
    calcola_AXILiteS_s_axi_U->a(a);
    calcola_AXILiteS_s_axi_U->b(b);
    calcola_AXILiteS_s_axi_U->o(o);
    calcola_AXILiteS_s_axi_U->c(ap_phi_mux_storemerge4_phi_fu_67_p10);
    calcola_AXILiteS_s_axi_U->c_ap_vld(c_ap_vld);
    calcola_sdiv_32s_bkb_U1 = new calcola_sdiv_32s_bkb<1,36,32,32,32>("calcola_sdiv_32s_bkb_U1");
    calcola_sdiv_32s_bkb_U1->clk(ap_clk);
    calcola_sdiv_32s_bkb_U1->reset(ap_rst_n_inv);
    calcola_sdiv_32s_bkb_U1->start(grp_fu_117_ap_start);
    calcola_sdiv_32s_bkb_U1->done(grp_fu_117_ap_done);
    calcola_sdiv_32s_bkb_U1->din0(a);
    calcola_sdiv_32s_bkb_U1->din1(b);
    calcola_sdiv_32s_bkb_U1->ce(ap_var_for_const0);
    calcola_sdiv_32s_bkb_U1->dout(grp_fu_117_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state36);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state37);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state38);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_phi_mux_storemerge4_phi_fu_67_p10);
    sensitive << ( tmp_1_reg_152 );
    sensitive << ( tmp_3_reg_156 );
    sensitive << ( tmp_5_reg_160 );
    sensitive << ( or_cond_reg_164 );
    sensitive << ( storemerge4_reg_63 );
    sensitive << ( grp_fu_117_p2 );
    sensitive << ( ap_CS_fsm_state36 );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_c_ap_vld);
    sensitive << ( ap_CS_fsm_state36 );

    SC_METHOD(thread_grp_fu_117_ap_start);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_1_fu_81_p2 );
    sensitive << ( tmp_3_fu_87_p2 );
    sensitive << ( tmp_5_fu_93_p2 );
    sensitive << ( or_cond_fu_111_p2 );

    SC_METHOD(thread_or_cond_fu_111_p2);
    sensitive << ( tmp_7_fu_99_p2 );
    sensitive << ( tmp_8_fu_105_p2 );

    SC_METHOD(thread_tmp_1_fu_81_p2);
    sensitive << ( o );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_tmp_2_fu_130_p0);
    sensitive << ( b );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_tmp_2_fu_130_p1);
    sensitive << ( a );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_tmp_2_fu_130_p2);
    sensitive << ( tmp_2_fu_130_p0 );
    sensitive << ( tmp_2_fu_130_p1 );

    SC_METHOD(thread_tmp_3_fu_87_p2);
    sensitive << ( o );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_1_fu_81_p2 );

    SC_METHOD(thread_tmp_4_fu_124_p0);
    sensitive << ( a );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_tmp_4_fu_124_p1);
    sensitive << ( b );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_tmp_4_fu_124_p2);
    sensitive << ( tmp_4_fu_124_p0 );
    sensitive << ( tmp_4_fu_124_p1 );

    SC_METHOD(thread_tmp_5_fu_93_p2);
    sensitive << ( o );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_1_fu_81_p2 );
    sensitive << ( tmp_3_fu_87_p2 );

    SC_METHOD(thread_tmp_6_fu_136_p2);
    sensitive << ( b_read_reg_140 );
    sensitive << ( a_read_reg_146 );

    SC_METHOD(thread_tmp_7_fu_99_p2);
    sensitive << ( o );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_1_fu_81_p2 );
    sensitive << ( tmp_3_fu_87_p2 );
    sensitive << ( tmp_5_fu_93_p2 );

    SC_METHOD(thread_tmp_8_fu_105_p0);
    sensitive << ( b );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_tmp_8_fu_105_p2);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_1_fu_81_p2 );
    sensitive << ( tmp_3_fu_87_p2 );
    sensitive << ( tmp_5_fu_93_p2 );
    sensitive << ( tmp_8_fu_105_p0 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_1_fu_81_p2 );
    sensitive << ( tmp_3_fu_87_p2 );
    sensitive << ( tmp_5_fu_93_p2 );
    sensitive << ( or_cond_fu_111_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "00000000000000000000000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "calcola_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWVALID, "(port)s_axi_AXILiteS_AWVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWREADY, "(port)s_axi_AXILiteS_AWREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWADDR, "(port)s_axi_AXILiteS_AWADDR");
    sc_trace(mVcdFile, s_axi_AXILiteS_WVALID, "(port)s_axi_AXILiteS_WVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_WREADY, "(port)s_axi_AXILiteS_WREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_WDATA, "(port)s_axi_AXILiteS_WDATA");
    sc_trace(mVcdFile, s_axi_AXILiteS_WSTRB, "(port)s_axi_AXILiteS_WSTRB");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARVALID, "(port)s_axi_AXILiteS_ARVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARREADY, "(port)s_axi_AXILiteS_ARREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARADDR, "(port)s_axi_AXILiteS_ARADDR");
    sc_trace(mVcdFile, s_axi_AXILiteS_RVALID, "(port)s_axi_AXILiteS_RVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_RREADY, "(port)s_axi_AXILiteS_RREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_RDATA, "(port)s_axi_AXILiteS_RDATA");
    sc_trace(mVcdFile, s_axi_AXILiteS_RRESP, "(port)s_axi_AXILiteS_RRESP");
    sc_trace(mVcdFile, s_axi_AXILiteS_BVALID, "(port)s_axi_AXILiteS_BVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_BREADY, "(port)s_axi_AXILiteS_BREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_BRESP, "(port)s_axi_AXILiteS_BRESP");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, a, "a");
    sc_trace(mVcdFile, b, "b");
    sc_trace(mVcdFile, o, "o");
    sc_trace(mVcdFile, c_ap_vld, "c_ap_vld");
    sc_trace(mVcdFile, b_read_reg_140, "b_read_reg_140");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, a_read_reg_146, "a_read_reg_146");
    sc_trace(mVcdFile, tmp_1_fu_81_p2, "tmp_1_fu_81_p2");
    sc_trace(mVcdFile, tmp_1_reg_152, "tmp_1_reg_152");
    sc_trace(mVcdFile, tmp_3_fu_87_p2, "tmp_3_fu_87_p2");
    sc_trace(mVcdFile, tmp_3_reg_156, "tmp_3_reg_156");
    sc_trace(mVcdFile, tmp_5_fu_93_p2, "tmp_5_fu_93_p2");
    sc_trace(mVcdFile, tmp_5_reg_160, "tmp_5_reg_160");
    sc_trace(mVcdFile, or_cond_fu_111_p2, "or_cond_fu_111_p2");
    sc_trace(mVcdFile, or_cond_reg_164, "or_cond_reg_164");
    sc_trace(mVcdFile, tmp_4_fu_124_p2, "tmp_4_fu_124_p2");
    sc_trace(mVcdFile, tmp_2_fu_130_p2, "tmp_2_fu_130_p2");
    sc_trace(mVcdFile, tmp_6_fu_136_p2, "tmp_6_fu_136_p2");
    sc_trace(mVcdFile, tmp_6_reg_178, "tmp_6_reg_178");
    sc_trace(mVcdFile, ap_CS_fsm_state37, "ap_CS_fsm_state37");
    sc_trace(mVcdFile, ap_phi_mux_storemerge4_phi_fu_67_p10, "ap_phi_mux_storemerge4_phi_fu_67_p10");
    sc_trace(mVcdFile, storemerge4_reg_63, "storemerge4_reg_63");
    sc_trace(mVcdFile, ap_CS_fsm_state38, "ap_CS_fsm_state38");
    sc_trace(mVcdFile, grp_fu_117_p2, "grp_fu_117_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state36, "ap_CS_fsm_state36");
    sc_trace(mVcdFile, tmp_8_fu_105_p0, "tmp_8_fu_105_p0");
    sc_trace(mVcdFile, tmp_7_fu_99_p2, "tmp_7_fu_99_p2");
    sc_trace(mVcdFile, tmp_8_fu_105_p2, "tmp_8_fu_105_p2");
    sc_trace(mVcdFile, tmp_4_fu_124_p0, "tmp_4_fu_124_p0");
    sc_trace(mVcdFile, tmp_4_fu_124_p1, "tmp_4_fu_124_p1");
    sc_trace(mVcdFile, tmp_2_fu_130_p0, "tmp_2_fu_130_p0");
    sc_trace(mVcdFile, tmp_2_fu_130_p1, "tmp_2_fu_130_p1");
    sc_trace(mVcdFile, grp_fu_117_ap_start, "grp_fu_117_ap_start");
    sc_trace(mVcdFile, grp_fu_117_ap_done, "grp_fu_117_ap_done");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("calcola.hdltvin.dat");
    mHdltvoutHandle.open("calcola.hdltvout.dat");
}

calcola::~calcola() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete calcola_AXILiteS_s_axi_U;
    delete calcola_sdiv_32s_bkb_U1;
}

void calcola::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void calcola::thread_ap_clk_no_reset_() {
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(tmp_1_fu_81_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(tmp_3_fu_87_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_5_fu_93_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, or_cond_fu_111_p2.read()))) {
        storemerge4_reg_63 = ap_const_lv32_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state36.read()) && 
                esl_seteq<1,1,1>(tmp_1_reg_152.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(tmp_3_reg_156.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_5_reg_160.read()) && 
                esl_seteq<1,1,1>(or_cond_reg_164.read(), ap_const_lv1_1))) {
        storemerge4_reg_63 = grp_fu_117_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state38.read())) {
        storemerge4_reg_63 = tmp_6_reg_178.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(tmp_1_fu_81_p2.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(tmp_3_fu_87_p2.read(), ap_const_lv1_1))) {
        storemerge4_reg_63 = tmp_4_fu_124_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(tmp_1_fu_81_p2.read(), ap_const_lv1_1))) {
        storemerge4_reg_63 = tmp_2_fu_130_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        a_read_reg_146 = a.read();
        b_read_reg_140 = b.read();
        tmp_1_reg_152 = tmp_1_fu_81_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(tmp_1_fu_81_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(tmp_3_fu_87_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_5_fu_93_p2.read()))) {
        or_cond_reg_164 = or_cond_fu_111_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(tmp_1_fu_81_p2.read(), ap_const_lv1_0))) {
        tmp_3_reg_156 = tmp_3_fu_87_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(tmp_1_fu_81_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(tmp_3_fu_87_p2.read(), ap_const_lv1_0))) {
        tmp_5_reg_160 = tmp_5_fu_93_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state37.read())) {
        tmp_6_reg_178 = tmp_6_fu_136_p2.read();
    }
}

void calcola::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void calcola::thread_ap_CS_fsm_state36() {
    ap_CS_fsm_state36 = ap_CS_fsm.read()[35];
}

void calcola::thread_ap_CS_fsm_state37() {
    ap_CS_fsm_state37 = ap_CS_fsm.read()[36];
}

void calcola::thread_ap_CS_fsm_state38() {
    ap_CS_fsm_state38 = ap_CS_fsm.read()[37];
}

void calcola::thread_ap_phi_mux_storemerge4_phi_fu_67_p10() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state36.read()) && 
         esl_seteq<1,1,1>(tmp_1_reg_152.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(tmp_3_reg_156.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_5_reg_160.read()) && 
         esl_seteq<1,1,1>(or_cond_reg_164.read(), ap_const_lv1_1))) {
        ap_phi_mux_storemerge4_phi_fu_67_p10 = grp_fu_117_p2.read();
    } else {
        ap_phi_mux_storemerge4_phi_fu_67_p10 = storemerge4_reg_63.read();
    }
}

void calcola::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void calcola::thread_c_ap_vld() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state36.read())) {
        c_ap_vld = ap_const_logic_1;
    } else {
        c_ap_vld = ap_const_logic_0;
    }
}

void calcola::thread_grp_fu_117_ap_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(tmp_1_fu_81_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(tmp_3_fu_87_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_5_fu_93_p2.read()) && 
         esl_seteq<1,1,1>(or_cond_fu_111_p2.read(), ap_const_lv1_1))) {
        grp_fu_117_ap_start = ap_const_logic_1;
    } else {
        grp_fu_117_ap_start = ap_const_logic_0;
    }
}

void calcola::thread_or_cond_fu_111_p2() {
    or_cond_fu_111_p2 = (tmp_7_fu_99_p2.read() & tmp_8_fu_105_p2.read());
}

void calcola::thread_tmp_1_fu_81_p2() {
    tmp_1_fu_81_p2 = (!o.read().is_01() || !ap_const_lv8_2B.is_01())? sc_lv<1>(): sc_lv<1>(o.read() == ap_const_lv8_2B);
}

void calcola::thread_tmp_2_fu_130_p0() {
    tmp_2_fu_130_p0 = b.read();
}

void calcola::thread_tmp_2_fu_130_p1() {
    tmp_2_fu_130_p1 = a.read();
}

void calcola::thread_tmp_2_fu_130_p2() {
    tmp_2_fu_130_p2 = (!tmp_2_fu_130_p0.read().is_01() || !tmp_2_fu_130_p1.read().is_01())? sc_lv<32>(): (sc_bigint<32>(tmp_2_fu_130_p0.read()) + sc_bigint<32>(tmp_2_fu_130_p1.read()));
}

void calcola::thread_tmp_3_fu_87_p2() {
    tmp_3_fu_87_p2 = (!o.read().is_01() || !ap_const_lv8_2D.is_01())? sc_lv<1>(): sc_lv<1>(o.read() == ap_const_lv8_2D);
}

void calcola::thread_tmp_4_fu_124_p0() {
    tmp_4_fu_124_p0 = a.read();
}

void calcola::thread_tmp_4_fu_124_p1() {
    tmp_4_fu_124_p1 = b.read();
}

void calcola::thread_tmp_4_fu_124_p2() {
    tmp_4_fu_124_p2 = (!tmp_4_fu_124_p0.read().is_01() || !tmp_4_fu_124_p1.read().is_01())? sc_lv<32>(): (sc_bigint<32>(tmp_4_fu_124_p0.read()) - sc_bigint<32>(tmp_4_fu_124_p1.read()));
}

void calcola::thread_tmp_5_fu_93_p2() {
    tmp_5_fu_93_p2 = (!o.read().is_01() || !ap_const_lv8_2A.is_01())? sc_lv<1>(): sc_lv<1>(o.read() == ap_const_lv8_2A);
}

void calcola::thread_tmp_6_fu_136_p2() {
    tmp_6_fu_136_p2 = (!b_read_reg_140.read().is_01() || !a_read_reg_146.read().is_01())? sc_lv<32>(): sc_bigint<32>(b_read_reg_140.read()) * sc_bigint<32>(a_read_reg_146.read());
}

void calcola::thread_tmp_7_fu_99_p2() {
    tmp_7_fu_99_p2 = (!o.read().is_01() || !ap_const_lv8_2F.is_01())? sc_lv<1>(): sc_lv<1>(o.read() == ap_const_lv8_2F);
}

void calcola::thread_tmp_8_fu_105_p0() {
    tmp_8_fu_105_p0 = b.read();
}

void calcola::thread_tmp_8_fu_105_p2() {
    tmp_8_fu_105_p2 = (!tmp_8_fu_105_p0.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): (sc_bigint<32>(tmp_8_fu_105_p0.read()) > sc_bigint<32>(ap_const_lv32_0));
}

void calcola::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && (((esl_seteq<1,1,1>(ap_const_lv1_0, tmp_5_fu_93_p2.read()) && 
    esl_seteq<1,1,1>(ap_const_lv1_0, or_cond_fu_111_p2.read())) || 
   esl_seteq<1,1,1>(tmp_3_fu_87_p2.read(), ap_const_lv1_1)) || 
  esl_seteq<1,1,1>(tmp_1_fu_81_p2.read(), ap_const_lv1_1)))) {
                ap_NS_fsm = ap_ST_fsm_state36;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(tmp_1_fu_81_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(tmp_3_fu_87_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_5_fu_93_p2.read()) && esl_seteq<1,1,1>(or_cond_fu_111_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state37;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state21;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_state22;
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_fsm_state23;
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_fsm_state24;
            break;
        case 8388608 : 
            ap_NS_fsm = ap_ST_fsm_state25;
            break;
        case 16777216 : 
            ap_NS_fsm = ap_ST_fsm_state26;
            break;
        case 33554432 : 
            ap_NS_fsm = ap_ST_fsm_state27;
            break;
        case 67108864 : 
            ap_NS_fsm = ap_ST_fsm_state28;
            break;
        case 134217728 : 
            ap_NS_fsm = ap_ST_fsm_state29;
            break;
        case 268435456 : 
            ap_NS_fsm = ap_ST_fsm_state30;
            break;
        case 536870912 : 
            ap_NS_fsm = ap_ST_fsm_state31;
            break;
        case 1073741824 : 
            ap_NS_fsm = ap_ST_fsm_state32;
            break;
        case 2147483648 : 
            ap_NS_fsm = ap_ST_fsm_state33;
            break;
        case 4294967296 : 
            ap_NS_fsm = ap_ST_fsm_state34;
            break;
        case 8589934592 : 
            ap_NS_fsm = ap_ST_fsm_state35;
            break;
        case 17179869184 : 
            ap_NS_fsm = ap_ST_fsm_state36;
            break;
        case 34359738368 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        case 68719476736 : 
            ap_NS_fsm = ap_ST_fsm_state38;
            break;
        case 137438953472 : 
            ap_NS_fsm = ap_ST_fsm_state36;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            break;
    }
}

void calcola::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_AWVALID\" :  \"" << s_axi_AXILiteS_AWVALID.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"s_axi_AXILiteS_AWREADY\" :  \"" << s_axi_AXILiteS_AWREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_AWADDR\" :  \"" << s_axi_AXILiteS_AWADDR.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WVALID\" :  \"" << s_axi_AXILiteS_WVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_WREADY\" :  \"" << s_axi_AXILiteS_WREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WDATA\" :  \"" << s_axi_AXILiteS_WDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WSTRB\" :  \"" << s_axi_AXILiteS_WSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_ARVALID\" :  \"" << s_axi_AXILiteS_ARVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_ARREADY\" :  \"" << s_axi_AXILiteS_ARREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_ARADDR\" :  \"" << s_axi_AXILiteS_ARADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RVALID\" :  \"" << s_axi_AXILiteS_RVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_RREADY\" :  \"" << s_axi_AXILiteS_RREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RDATA\" :  \"" << s_axi_AXILiteS_RDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RRESP\" :  \"" << s_axi_AXILiteS_RRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_BVALID\" :  \"" << s_axi_AXILiteS_BVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_BREADY\" :  \"" << s_axi_AXILiteS_BREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_BRESP\" :  \"" << s_axi_AXILiteS_BRESP.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

