// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "Block_Mat_exit38593_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic Block_Mat_exit38593_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic Block_Mat_exit38593_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> Block_Mat_exit38593_s::ap_ST_fsm_state1 = "1";
const sc_lv<3> Block_Mat_exit38593_s::ap_ST_fsm_state2 = "10";
const sc_lv<3> Block_Mat_exit38593_s::ap_ST_fsm_state3 = "100";
const sc_lv<32> Block_Mat_exit38593_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> Block_Mat_exit38593_s::ap_const_lv32_2 = "10";
const sc_lv<32> Block_Mat_exit38593_s::ap_const_lv32_1F = "11111";
const sc_lv<31> Block_Mat_exit38593_s::ap_const_lv31_0 = "0000000000000000000000000000000";
const bool Block_Mat_exit38593_s::ap_const_boolean_1 = true;

Block_Mat_exit38593_s::Block_Mat_exit38593_s(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state3);
    sensitive << ( col_packets_out_out_full_n );
    sensitive << ( col_packets_cast_out_out_full_n );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( col_packets_out_out_full_n );
    sensitive << ( col_packets_cast_out_out_full_n );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( internal_ap_ready );

    SC_METHOD(thread_ap_return);
    sensitive << ( col_packets_out_out_full_n );
    sensitive << ( col_packets_cast_out_out_full_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( packets_fu_156_p2 );
    sensitive << ( ap_return_preg );

    SC_METHOD(thread_col_packets_cast_out_out_blk_n);
    sensitive << ( col_packets_cast_out_out_full_n );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_col_packets_cast_out_out_din);
    sensitive << ( col_packets_out_out_full_n );
    sensitive << ( col_packets_cast_out_out_full_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( col_packets_fu_142_p3 );

    SC_METHOD(thread_col_packets_cast_out_out_write);
    sensitive << ( col_packets_out_out_full_n );
    sensitive << ( col_packets_cast_out_out_full_n );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_col_packets_fu_142_p3);
    sensitive << ( tmp_36_fu_96_p3 );
    sensitive << ( p_neg_t_i_fu_133_p2 );
    sensitive << ( p_lshr_f_cast_i_fu_139_p1 );

    SC_METHOD(thread_col_packets_out_out_blk_n);
    sensitive << ( col_packets_out_out_full_n );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_col_packets_out_out_din);
    sensitive << ( col_packets_out_out_full_n );
    sensitive << ( col_packets_cast_out_out_full_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( col_packets_fu_142_p3 );

    SC_METHOD(thread_col_packets_out_out_write);
    sensitive << ( col_packets_out_out_full_n );
    sensitive << ( col_packets_cast_out_out_full_n );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_internal_ap_ready);
    sensitive << ( col_packets_out_out_full_n );
    sensitive << ( col_packets_cast_out_out_full_n );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_p_lshr_cast_i_fu_129_p1);
    sensitive << ( tmp_fu_119_p4 );

    SC_METHOD(thread_p_lshr_f_cast_i_fu_139_p1);
    sensitive << ( tmp_s_fu_104_p4 );

    SC_METHOD(thread_p_neg_i_fu_114_p2);
    sensitive << ( tmp_i_fu_90_p2 );

    SC_METHOD(thread_p_neg_t_i_fu_133_p2);
    sensitive << ( p_lshr_cast_i_fu_129_p1 );

    SC_METHOD(thread_packets_fu_156_p0);
    sensitive << ( rows );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_packets_fu_156_p1);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( col_packets_fu_142_p3 );

    SC_METHOD(thread_packets_fu_156_p2);
    sensitive << ( packets_fu_156_p0 );
    sensitive << ( packets_fu_156_p1 );

    SC_METHOD(thread_real_start);
    sensitive << ( ap_start );
    sensitive << ( start_full_n );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_start_out);
    sensitive << ( real_start );

    SC_METHOD(thread_start_write);
    sensitive << ( real_start );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_tmp_36_fu_96_p3);
    sensitive << ( tmp_i_fu_90_p2 );

    SC_METHOD(thread_tmp_fu_119_p4);
    sensitive << ( p_neg_i_fu_114_p2 );

    SC_METHOD(thread_tmp_i_fu_90_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( channels );

    SC_METHOD(thread_tmp_i_fu_90_p1);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( cols );

    SC_METHOD(thread_tmp_i_fu_90_p2);
    sensitive << ( tmp_i_fu_90_p0 );
    sensitive << ( tmp_i_fu_90_p1 );

    SC_METHOD(thread_tmp_s_fu_104_p4);
    sensitive << ( tmp_i_fu_90_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( col_packets_out_out_full_n );
    sensitive << ( col_packets_cast_out_out_full_n );
    sensitive << ( ap_CS_fsm_state3 );

    start_once_reg = SC_LOGIC_0;
    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "001";
    ap_return_preg = "00000000000000000000000000000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "Block_Mat_exit38593_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, start_full_n, "(port)start_full_n");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, start_out, "(port)start_out");
    sc_trace(mVcdFile, start_write, "(port)start_write");
    sc_trace(mVcdFile, channels, "(port)channels");
    sc_trace(mVcdFile, cols, "(port)cols");
    sc_trace(mVcdFile, rows, "(port)rows");
    sc_trace(mVcdFile, col_packets_out_out_din, "(port)col_packets_out_out_din");
    sc_trace(mVcdFile, col_packets_out_out_full_n, "(port)col_packets_out_out_full_n");
    sc_trace(mVcdFile, col_packets_out_out_write, "(port)col_packets_out_out_write");
    sc_trace(mVcdFile, col_packets_cast_out_out_din, "(port)col_packets_cast_out_out_din");
    sc_trace(mVcdFile, col_packets_cast_out_out_full_n, "(port)col_packets_cast_out_out_full_n");
    sc_trace(mVcdFile, col_packets_cast_out_out_write, "(port)col_packets_cast_out_out_write");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, real_start, "real_start");
    sc_trace(mVcdFile, start_once_reg, "start_once_reg");
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, internal_ap_ready, "internal_ap_ready");
    sc_trace(mVcdFile, col_packets_out_out_blk_n, "col_packets_out_out_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, col_packets_cast_out_out_blk_n, "col_packets_cast_out_out_blk_n");
    sc_trace(mVcdFile, tmp_i_fu_90_p2, "tmp_i_fu_90_p2");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, tmp_36_fu_96_p3, "tmp_36_fu_96_p3");
    sc_trace(mVcdFile, tmp_s_fu_104_p4, "tmp_s_fu_104_p4");
    sc_trace(mVcdFile, col_packets_fu_142_p3, "col_packets_fu_142_p3");
    sc_trace(mVcdFile, ap_block_state3, "ap_block_state3");
    sc_trace(mVcdFile, tmp_i_fu_90_p0, "tmp_i_fu_90_p0");
    sc_trace(mVcdFile, tmp_i_fu_90_p1, "tmp_i_fu_90_p1");
    sc_trace(mVcdFile, p_neg_i_fu_114_p2, "p_neg_i_fu_114_p2");
    sc_trace(mVcdFile, tmp_fu_119_p4, "tmp_fu_119_p4");
    sc_trace(mVcdFile, p_lshr_cast_i_fu_129_p1, "p_lshr_cast_i_fu_129_p1");
    sc_trace(mVcdFile, p_neg_t_i_fu_133_p2, "p_neg_t_i_fu_133_p2");
    sc_trace(mVcdFile, p_lshr_f_cast_i_fu_139_p1, "p_lshr_f_cast_i_fu_139_p1");
    sc_trace(mVcdFile, packets_fu_156_p0, "packets_fu_156_p0");
    sc_trace(mVcdFile, packets_fu_156_p1, "packets_fu_156_p1");
    sc_trace(mVcdFile, packets_fu_156_p2, "packets_fu_156_p2");
    sc_trace(mVcdFile, ap_return_preg, "ap_return_preg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

Block_Mat_exit38593_s::~Block_Mat_exit38593_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void Block_Mat_exit38593_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, col_packets_out_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, col_packets_cast_out_out_full_n.read())))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_preg = ap_const_lv32_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, col_packets_out_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, col_packets_cast_out_out_full_n.read())))) {
            ap_return_preg = packets_fu_156_p2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        start_once_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_0, internal_ap_ready.read()))) {
            start_once_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, internal_ap_ready.read())) {
            start_once_reg = ap_const_logic_0;
        }
    }
}

void Block_Mat_exit38593_s::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void Block_Mat_exit38593_s::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void Block_Mat_exit38593_s::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void Block_Mat_exit38593_s::thread_ap_block_state3() {
    ap_block_state3 = (esl_seteq<1,1,1>(ap_const_logic_0, col_packets_out_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, col_packets_cast_out_out_full_n.read()));
}

void Block_Mat_exit38593_s::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, col_packets_out_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, col_packets_cast_out_out_full_n.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void Block_Mat_exit38593_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void Block_Mat_exit38593_s::thread_ap_ready() {
    ap_ready = internal_ap_ready.read();
}

void Block_Mat_exit38593_s::thread_ap_return() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, col_packets_out_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, col_packets_cast_out_out_full_n.read())))) {
        ap_return = packets_fu_156_p2.read();
    } else {
        ap_return = ap_return_preg.read();
    }
}

void Block_Mat_exit38593_s::thread_col_packets_cast_out_out_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        col_packets_cast_out_out_blk_n = col_packets_cast_out_out_full_n.read();
    } else {
        col_packets_cast_out_out_blk_n = ap_const_logic_1;
    }
}

void Block_Mat_exit38593_s::thread_col_packets_cast_out_out_din() {
    col_packets_cast_out_out_din = col_packets_fu_142_p3.read().range(30-1, 0);
}

void Block_Mat_exit38593_s::thread_col_packets_cast_out_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, col_packets_out_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, col_packets_cast_out_out_full_n.read())))) {
        col_packets_cast_out_out_write = ap_const_logic_1;
    } else {
        col_packets_cast_out_out_write = ap_const_logic_0;
    }
}

void Block_Mat_exit38593_s::thread_col_packets_fu_142_p3() {
    col_packets_fu_142_p3 = (!tmp_36_fu_96_p3.read()[0].is_01())? sc_lv<31>(): ((tmp_36_fu_96_p3.read()[0].to_bool())? p_neg_t_i_fu_133_p2.read(): p_lshr_f_cast_i_fu_139_p1.read());
}

void Block_Mat_exit38593_s::thread_col_packets_out_out_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        col_packets_out_out_blk_n = col_packets_out_out_full_n.read();
    } else {
        col_packets_out_out_blk_n = ap_const_logic_1;
    }
}

void Block_Mat_exit38593_s::thread_col_packets_out_out_din() {
    col_packets_out_out_din = col_packets_fu_142_p3.read();
}

void Block_Mat_exit38593_s::thread_col_packets_out_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, col_packets_out_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, col_packets_cast_out_out_full_n.read())))) {
        col_packets_out_out_write = ap_const_logic_1;
    } else {
        col_packets_out_out_write = ap_const_logic_0;
    }
}

void Block_Mat_exit38593_s::thread_internal_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, col_packets_out_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, col_packets_cast_out_out_full_n.read())))) {
        internal_ap_ready = ap_const_logic_1;
    } else {
        internal_ap_ready = ap_const_logic_0;
    }
}

void Block_Mat_exit38593_s::thread_p_lshr_cast_i_fu_129_p1() {
    p_lshr_cast_i_fu_129_p1 = esl_zext<31,30>(tmp_fu_119_p4.read());
}

void Block_Mat_exit38593_s::thread_p_lshr_f_cast_i_fu_139_p1() {
    p_lshr_f_cast_i_fu_139_p1 = esl_zext<31,30>(tmp_s_fu_104_p4.read());
}

void Block_Mat_exit38593_s::thread_p_neg_i_fu_114_p2() {
    p_neg_i_fu_114_p2 = (!ap_const_lv32_0.is_01() || !tmp_i_fu_90_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_0) - sc_biguint<32>(tmp_i_fu_90_p2.read()));
}

void Block_Mat_exit38593_s::thread_p_neg_t_i_fu_133_p2() {
    p_neg_t_i_fu_133_p2 = (!ap_const_lv31_0.is_01() || !p_lshr_cast_i_fu_129_p1.read().is_01())? sc_lv<31>(): (sc_biguint<31>(ap_const_lv31_0) - sc_biguint<31>(p_lshr_cast_i_fu_129_p1.read()));
}

void Block_Mat_exit38593_s::thread_packets_fu_156_p0() {
    packets_fu_156_p0 = rows.read();
}

void Block_Mat_exit38593_s::thread_packets_fu_156_p1() {
    packets_fu_156_p1 = col_packets_fu_142_p3.read();
}

void Block_Mat_exit38593_s::thread_packets_fu_156_p2() {
    packets_fu_156_p2 = (!packets_fu_156_p0.read().is_01() || !packets_fu_156_p1.read().is_01())? sc_lv<32>(): sc_bigint<32>(packets_fu_156_p0.read()) * sc_bigint<31>(packets_fu_156_p1.read());
}

void Block_Mat_exit38593_s::thread_real_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_full_n.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()))) {
        real_start = ap_const_logic_0;
    } else {
        real_start = ap_start.read();
    }
}

void Block_Mat_exit38593_s::thread_start_out() {
    start_out = real_start.read();
}

void Block_Mat_exit38593_s::thread_start_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()))) {
        start_write = ap_const_logic_1;
    } else {
        start_write = ap_const_logic_0;
    }
}

void Block_Mat_exit38593_s::thread_tmp_36_fu_96_p3() {
    tmp_36_fu_96_p3 = tmp_i_fu_90_p2.read().range(31, 31);
}

void Block_Mat_exit38593_s::thread_tmp_fu_119_p4() {
    tmp_fu_119_p4 = p_neg_i_fu_114_p2.read().range(31, 2);
}

void Block_Mat_exit38593_s::thread_tmp_i_fu_90_p0() {
    tmp_i_fu_90_p0 = channels.read();
}

void Block_Mat_exit38593_s::thread_tmp_i_fu_90_p1() {
    tmp_i_fu_90_p1 = cols.read();
}

void Block_Mat_exit38593_s::thread_tmp_i_fu_90_p2() {
    tmp_i_fu_90_p2 = (!tmp_i_fu_90_p0.read().is_01() || !tmp_i_fu_90_p1.read().is_01())? sc_lv<32>(): sc_bigint<32>(tmp_i_fu_90_p0.read()) * sc_bigint<32>(tmp_i_fu_90_p1.read());
}

void Block_Mat_exit38593_s::thread_tmp_s_fu_104_p4() {
    tmp_s_fu_104_p4 = tmp_i_fu_90_p2.read().range(31, 2);
}

void Block_Mat_exit38593_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, col_packets_out_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, col_packets_cast_out_out_full_n.read())))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

}

