// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "Block_proc.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic Block_proc::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic Block_proc::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<1> Block_proc::ap_ST_fsm_state1 = "1";
const sc_lv<32> Block_proc::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> Block_proc::ap_const_lv32_8 = "1000";
const sc_lv<32> Block_proc::ap_const_lv32_F = "1111";
const sc_lv<32> Block_proc::ap_const_lv32_10 = "10000";
const sc_lv<32> Block_proc::ap_const_lv32_17 = "10111";
const bool Block_proc::ap_const_boolean_1 = true;

Block_proc::Block_proc(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( kernel_val_0_V_0_out_full_n );
    sensitive << ( kernel_val_0_V_1_out_full_n );
    sensitive << ( kernel_val_0_V_2_out_full_n );
    sensitive << ( kernel_val_1_V_0_out_full_n );
    sensitive << ( kernel_val_1_V_1_out_full_n );
    sensitive << ( kernel_val_1_V_2_out_full_n );
    sensitive << ( kernel_val_2_V_0_out_full_n );
    sensitive << ( kernel_val_2_V_1_out_full_n );
    sensitive << ( kernel_val_2_V_2_out_full_n );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_val_0_V_0_out_full_n );
    sensitive << ( kernel_val_0_V_1_out_full_n );
    sensitive << ( kernel_val_0_V_2_out_full_n );
    sensitive << ( kernel_val_1_V_0_out_full_n );
    sensitive << ( kernel_val_1_V_1_out_full_n );
    sensitive << ( kernel_val_1_V_2_out_full_n );
    sensitive << ( kernel_val_2_V_0_out_full_n );
    sensitive << ( kernel_val_2_V_1_out_full_n );
    sensitive << ( kernel_val_2_V_2_out_full_n );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_val_0_V_0_out_full_n );
    sensitive << ( kernel_val_0_V_1_out_full_n );
    sensitive << ( kernel_val_0_V_2_out_full_n );
    sensitive << ( kernel_val_1_V_0_out_full_n );
    sensitive << ( kernel_val_1_V_1_out_full_n );
    sensitive << ( kernel_val_1_V_2_out_full_n );
    sensitive << ( kernel_val_2_V_0_out_full_n );
    sensitive << ( kernel_val_2_V_1_out_full_n );
    sensitive << ( kernel_val_2_V_2_out_full_n );

    SC_METHOD(thread_kernel_val_0_V_0_out_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_val_0_V_0_out_full_n );

    SC_METHOD(thread_kernel_val_0_V_0_out_din);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( r1_V );
    sensitive << ( kernel_val_0_V_0_out_full_n );
    sensitive << ( kernel_val_0_V_1_out_full_n );
    sensitive << ( kernel_val_0_V_2_out_full_n );
    sensitive << ( kernel_val_1_V_0_out_full_n );
    sensitive << ( kernel_val_1_V_1_out_full_n );
    sensitive << ( kernel_val_1_V_2_out_full_n );
    sensitive << ( kernel_val_2_V_0_out_full_n );
    sensitive << ( kernel_val_2_V_1_out_full_n );
    sensitive << ( kernel_val_2_V_2_out_full_n );

    SC_METHOD(thread_kernel_val_0_V_0_out_write);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_val_0_V_0_out_full_n );
    sensitive << ( kernel_val_0_V_1_out_full_n );
    sensitive << ( kernel_val_0_V_2_out_full_n );
    sensitive << ( kernel_val_1_V_0_out_full_n );
    sensitive << ( kernel_val_1_V_1_out_full_n );
    sensitive << ( kernel_val_1_V_2_out_full_n );
    sensitive << ( kernel_val_2_V_0_out_full_n );
    sensitive << ( kernel_val_2_V_1_out_full_n );
    sensitive << ( kernel_val_2_V_2_out_full_n );

    SC_METHOD(thread_kernel_val_0_V_1_out_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_val_0_V_1_out_full_n );

    SC_METHOD(thread_kernel_val_0_V_1_out_din);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( r1_V );
    sensitive << ( kernel_val_0_V_0_out_full_n );
    sensitive << ( kernel_val_0_V_1_out_full_n );
    sensitive << ( kernel_val_0_V_2_out_full_n );
    sensitive << ( kernel_val_1_V_0_out_full_n );
    sensitive << ( kernel_val_1_V_1_out_full_n );
    sensitive << ( kernel_val_1_V_2_out_full_n );
    sensitive << ( kernel_val_2_V_0_out_full_n );
    sensitive << ( kernel_val_2_V_1_out_full_n );
    sensitive << ( kernel_val_2_V_2_out_full_n );

    SC_METHOD(thread_kernel_val_0_V_1_out_write);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_val_0_V_0_out_full_n );
    sensitive << ( kernel_val_0_V_1_out_full_n );
    sensitive << ( kernel_val_0_V_2_out_full_n );
    sensitive << ( kernel_val_1_V_0_out_full_n );
    sensitive << ( kernel_val_1_V_1_out_full_n );
    sensitive << ( kernel_val_1_V_2_out_full_n );
    sensitive << ( kernel_val_2_V_0_out_full_n );
    sensitive << ( kernel_val_2_V_1_out_full_n );
    sensitive << ( kernel_val_2_V_2_out_full_n );

    SC_METHOD(thread_kernel_val_0_V_2_out_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_val_0_V_2_out_full_n );

    SC_METHOD(thread_kernel_val_0_V_2_out_din);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( r1_V );
    sensitive << ( kernel_val_0_V_0_out_full_n );
    sensitive << ( kernel_val_0_V_1_out_full_n );
    sensitive << ( kernel_val_0_V_2_out_full_n );
    sensitive << ( kernel_val_1_V_0_out_full_n );
    sensitive << ( kernel_val_1_V_1_out_full_n );
    sensitive << ( kernel_val_1_V_2_out_full_n );
    sensitive << ( kernel_val_2_V_0_out_full_n );
    sensitive << ( kernel_val_2_V_1_out_full_n );
    sensitive << ( kernel_val_2_V_2_out_full_n );

    SC_METHOD(thread_kernel_val_0_V_2_out_write);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_val_0_V_0_out_full_n );
    sensitive << ( kernel_val_0_V_1_out_full_n );
    sensitive << ( kernel_val_0_V_2_out_full_n );
    sensitive << ( kernel_val_1_V_0_out_full_n );
    sensitive << ( kernel_val_1_V_1_out_full_n );
    sensitive << ( kernel_val_1_V_2_out_full_n );
    sensitive << ( kernel_val_2_V_0_out_full_n );
    sensitive << ( kernel_val_2_V_1_out_full_n );
    sensitive << ( kernel_val_2_V_2_out_full_n );

    SC_METHOD(thread_kernel_val_1_V_0_out_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_val_1_V_0_out_full_n );

    SC_METHOD(thread_kernel_val_1_V_0_out_din);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( r2_V );
    sensitive << ( kernel_val_0_V_0_out_full_n );
    sensitive << ( kernel_val_0_V_1_out_full_n );
    sensitive << ( kernel_val_0_V_2_out_full_n );
    sensitive << ( kernel_val_1_V_0_out_full_n );
    sensitive << ( kernel_val_1_V_1_out_full_n );
    sensitive << ( kernel_val_1_V_2_out_full_n );
    sensitive << ( kernel_val_2_V_0_out_full_n );
    sensitive << ( kernel_val_2_V_1_out_full_n );
    sensitive << ( kernel_val_2_V_2_out_full_n );

    SC_METHOD(thread_kernel_val_1_V_0_out_write);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_val_0_V_0_out_full_n );
    sensitive << ( kernel_val_0_V_1_out_full_n );
    sensitive << ( kernel_val_0_V_2_out_full_n );
    sensitive << ( kernel_val_1_V_0_out_full_n );
    sensitive << ( kernel_val_1_V_1_out_full_n );
    sensitive << ( kernel_val_1_V_2_out_full_n );
    sensitive << ( kernel_val_2_V_0_out_full_n );
    sensitive << ( kernel_val_2_V_1_out_full_n );
    sensitive << ( kernel_val_2_V_2_out_full_n );

    SC_METHOD(thread_kernel_val_1_V_1_out_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_val_1_V_1_out_full_n );

    SC_METHOD(thread_kernel_val_1_V_1_out_din);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( r2_V );
    sensitive << ( kernel_val_0_V_0_out_full_n );
    sensitive << ( kernel_val_0_V_1_out_full_n );
    sensitive << ( kernel_val_0_V_2_out_full_n );
    sensitive << ( kernel_val_1_V_0_out_full_n );
    sensitive << ( kernel_val_1_V_1_out_full_n );
    sensitive << ( kernel_val_1_V_2_out_full_n );
    sensitive << ( kernel_val_2_V_0_out_full_n );
    sensitive << ( kernel_val_2_V_1_out_full_n );
    sensitive << ( kernel_val_2_V_2_out_full_n );

    SC_METHOD(thread_kernel_val_1_V_1_out_write);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_val_0_V_0_out_full_n );
    sensitive << ( kernel_val_0_V_1_out_full_n );
    sensitive << ( kernel_val_0_V_2_out_full_n );
    sensitive << ( kernel_val_1_V_0_out_full_n );
    sensitive << ( kernel_val_1_V_1_out_full_n );
    sensitive << ( kernel_val_1_V_2_out_full_n );
    sensitive << ( kernel_val_2_V_0_out_full_n );
    sensitive << ( kernel_val_2_V_1_out_full_n );
    sensitive << ( kernel_val_2_V_2_out_full_n );

    SC_METHOD(thread_kernel_val_1_V_2_out_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_val_1_V_2_out_full_n );

    SC_METHOD(thread_kernel_val_1_V_2_out_din);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( r2_V );
    sensitive << ( kernel_val_0_V_0_out_full_n );
    sensitive << ( kernel_val_0_V_1_out_full_n );
    sensitive << ( kernel_val_0_V_2_out_full_n );
    sensitive << ( kernel_val_1_V_0_out_full_n );
    sensitive << ( kernel_val_1_V_1_out_full_n );
    sensitive << ( kernel_val_1_V_2_out_full_n );
    sensitive << ( kernel_val_2_V_0_out_full_n );
    sensitive << ( kernel_val_2_V_1_out_full_n );
    sensitive << ( kernel_val_2_V_2_out_full_n );

    SC_METHOD(thread_kernel_val_1_V_2_out_write);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_val_0_V_0_out_full_n );
    sensitive << ( kernel_val_0_V_1_out_full_n );
    sensitive << ( kernel_val_0_V_2_out_full_n );
    sensitive << ( kernel_val_1_V_0_out_full_n );
    sensitive << ( kernel_val_1_V_1_out_full_n );
    sensitive << ( kernel_val_1_V_2_out_full_n );
    sensitive << ( kernel_val_2_V_0_out_full_n );
    sensitive << ( kernel_val_2_V_1_out_full_n );
    sensitive << ( kernel_val_2_V_2_out_full_n );

    SC_METHOD(thread_kernel_val_2_V_0_out_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_val_2_V_0_out_full_n );

    SC_METHOD(thread_kernel_val_2_V_0_out_din);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( r3_V );
    sensitive << ( kernel_val_0_V_0_out_full_n );
    sensitive << ( kernel_val_0_V_1_out_full_n );
    sensitive << ( kernel_val_0_V_2_out_full_n );
    sensitive << ( kernel_val_1_V_0_out_full_n );
    sensitive << ( kernel_val_1_V_1_out_full_n );
    sensitive << ( kernel_val_1_V_2_out_full_n );
    sensitive << ( kernel_val_2_V_0_out_full_n );
    sensitive << ( kernel_val_2_V_1_out_full_n );
    sensitive << ( kernel_val_2_V_2_out_full_n );

    SC_METHOD(thread_kernel_val_2_V_0_out_write);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_val_0_V_0_out_full_n );
    sensitive << ( kernel_val_0_V_1_out_full_n );
    sensitive << ( kernel_val_0_V_2_out_full_n );
    sensitive << ( kernel_val_1_V_0_out_full_n );
    sensitive << ( kernel_val_1_V_1_out_full_n );
    sensitive << ( kernel_val_1_V_2_out_full_n );
    sensitive << ( kernel_val_2_V_0_out_full_n );
    sensitive << ( kernel_val_2_V_1_out_full_n );
    sensitive << ( kernel_val_2_V_2_out_full_n );

    SC_METHOD(thread_kernel_val_2_V_1_out_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_val_2_V_1_out_full_n );

    SC_METHOD(thread_kernel_val_2_V_1_out_din);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( r3_V );
    sensitive << ( kernel_val_0_V_0_out_full_n );
    sensitive << ( kernel_val_0_V_1_out_full_n );
    sensitive << ( kernel_val_0_V_2_out_full_n );
    sensitive << ( kernel_val_1_V_0_out_full_n );
    sensitive << ( kernel_val_1_V_1_out_full_n );
    sensitive << ( kernel_val_1_V_2_out_full_n );
    sensitive << ( kernel_val_2_V_0_out_full_n );
    sensitive << ( kernel_val_2_V_1_out_full_n );
    sensitive << ( kernel_val_2_V_2_out_full_n );

    SC_METHOD(thread_kernel_val_2_V_1_out_write);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_val_0_V_0_out_full_n );
    sensitive << ( kernel_val_0_V_1_out_full_n );
    sensitive << ( kernel_val_0_V_2_out_full_n );
    sensitive << ( kernel_val_1_V_0_out_full_n );
    sensitive << ( kernel_val_1_V_1_out_full_n );
    sensitive << ( kernel_val_1_V_2_out_full_n );
    sensitive << ( kernel_val_2_V_0_out_full_n );
    sensitive << ( kernel_val_2_V_1_out_full_n );
    sensitive << ( kernel_val_2_V_2_out_full_n );

    SC_METHOD(thread_kernel_val_2_V_2_out_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_val_2_V_2_out_full_n );

    SC_METHOD(thread_kernel_val_2_V_2_out_din);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( r3_V );
    sensitive << ( kernel_val_0_V_0_out_full_n );
    sensitive << ( kernel_val_0_V_1_out_full_n );
    sensitive << ( kernel_val_0_V_2_out_full_n );
    sensitive << ( kernel_val_1_V_0_out_full_n );
    sensitive << ( kernel_val_1_V_1_out_full_n );
    sensitive << ( kernel_val_1_V_2_out_full_n );
    sensitive << ( kernel_val_2_V_0_out_full_n );
    sensitive << ( kernel_val_2_V_1_out_full_n );
    sensitive << ( kernel_val_2_V_2_out_full_n );

    SC_METHOD(thread_kernel_val_2_V_2_out_write);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_val_0_V_0_out_full_n );
    sensitive << ( kernel_val_0_V_1_out_full_n );
    sensitive << ( kernel_val_0_V_2_out_full_n );
    sensitive << ( kernel_val_1_V_0_out_full_n );
    sensitive << ( kernel_val_1_V_1_out_full_n );
    sensitive << ( kernel_val_1_V_2_out_full_n );
    sensitive << ( kernel_val_2_V_0_out_full_n );
    sensitive << ( kernel_val_2_V_1_out_full_n );
    sensitive << ( kernel_val_2_V_2_out_full_n );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_val_0_V_0_out_full_n );
    sensitive << ( kernel_val_0_V_1_out_full_n );
    sensitive << ( kernel_val_0_V_2_out_full_n );
    sensitive << ( kernel_val_1_V_0_out_full_n );
    sensitive << ( kernel_val_1_V_1_out_full_n );
    sensitive << ( kernel_val_1_V_2_out_full_n );
    sensitive << ( kernel_val_2_V_0_out_full_n );
    sensitive << ( kernel_val_2_V_1_out_full_n );
    sensitive << ( kernel_val_2_V_2_out_full_n );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "1";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "Block_proc_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, r1_V, "(port)r1_V");
    sc_trace(mVcdFile, r2_V, "(port)r2_V");
    sc_trace(mVcdFile, r3_V, "(port)r3_V");
    sc_trace(mVcdFile, kernel_val_0_V_0_out_din, "(port)kernel_val_0_V_0_out_din");
    sc_trace(mVcdFile, kernel_val_0_V_0_out_full_n, "(port)kernel_val_0_V_0_out_full_n");
    sc_trace(mVcdFile, kernel_val_0_V_0_out_write, "(port)kernel_val_0_V_0_out_write");
    sc_trace(mVcdFile, kernel_val_0_V_1_out_din, "(port)kernel_val_0_V_1_out_din");
    sc_trace(mVcdFile, kernel_val_0_V_1_out_full_n, "(port)kernel_val_0_V_1_out_full_n");
    sc_trace(mVcdFile, kernel_val_0_V_1_out_write, "(port)kernel_val_0_V_1_out_write");
    sc_trace(mVcdFile, kernel_val_0_V_2_out_din, "(port)kernel_val_0_V_2_out_din");
    sc_trace(mVcdFile, kernel_val_0_V_2_out_full_n, "(port)kernel_val_0_V_2_out_full_n");
    sc_trace(mVcdFile, kernel_val_0_V_2_out_write, "(port)kernel_val_0_V_2_out_write");
    sc_trace(mVcdFile, kernel_val_1_V_0_out_din, "(port)kernel_val_1_V_0_out_din");
    sc_trace(mVcdFile, kernel_val_1_V_0_out_full_n, "(port)kernel_val_1_V_0_out_full_n");
    sc_trace(mVcdFile, kernel_val_1_V_0_out_write, "(port)kernel_val_1_V_0_out_write");
    sc_trace(mVcdFile, kernel_val_1_V_1_out_din, "(port)kernel_val_1_V_1_out_din");
    sc_trace(mVcdFile, kernel_val_1_V_1_out_full_n, "(port)kernel_val_1_V_1_out_full_n");
    sc_trace(mVcdFile, kernel_val_1_V_1_out_write, "(port)kernel_val_1_V_1_out_write");
    sc_trace(mVcdFile, kernel_val_1_V_2_out_din, "(port)kernel_val_1_V_2_out_din");
    sc_trace(mVcdFile, kernel_val_1_V_2_out_full_n, "(port)kernel_val_1_V_2_out_full_n");
    sc_trace(mVcdFile, kernel_val_1_V_2_out_write, "(port)kernel_val_1_V_2_out_write");
    sc_trace(mVcdFile, kernel_val_2_V_0_out_din, "(port)kernel_val_2_V_0_out_din");
    sc_trace(mVcdFile, kernel_val_2_V_0_out_full_n, "(port)kernel_val_2_V_0_out_full_n");
    sc_trace(mVcdFile, kernel_val_2_V_0_out_write, "(port)kernel_val_2_V_0_out_write");
    sc_trace(mVcdFile, kernel_val_2_V_1_out_din, "(port)kernel_val_2_V_1_out_din");
    sc_trace(mVcdFile, kernel_val_2_V_1_out_full_n, "(port)kernel_val_2_V_1_out_full_n");
    sc_trace(mVcdFile, kernel_val_2_V_1_out_write, "(port)kernel_val_2_V_1_out_write");
    sc_trace(mVcdFile, kernel_val_2_V_2_out_din, "(port)kernel_val_2_V_2_out_din");
    sc_trace(mVcdFile, kernel_val_2_V_2_out_full_n, "(port)kernel_val_2_V_2_out_full_n");
    sc_trace(mVcdFile, kernel_val_2_V_2_out_write, "(port)kernel_val_2_V_2_out_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, kernel_val_0_V_0_out_blk_n, "kernel_val_0_V_0_out_blk_n");
    sc_trace(mVcdFile, kernel_val_0_V_1_out_blk_n, "kernel_val_0_V_1_out_blk_n");
    sc_trace(mVcdFile, kernel_val_0_V_2_out_blk_n, "kernel_val_0_V_2_out_blk_n");
    sc_trace(mVcdFile, kernel_val_1_V_0_out_blk_n, "kernel_val_1_V_0_out_blk_n");
    sc_trace(mVcdFile, kernel_val_1_V_1_out_blk_n, "kernel_val_1_V_1_out_blk_n");
    sc_trace(mVcdFile, kernel_val_1_V_2_out_blk_n, "kernel_val_1_V_2_out_blk_n");
    sc_trace(mVcdFile, kernel_val_2_V_0_out_blk_n, "kernel_val_2_V_0_out_blk_n");
    sc_trace(mVcdFile, kernel_val_2_V_1_out_blk_n, "kernel_val_2_V_1_out_blk_n");
    sc_trace(mVcdFile, kernel_val_2_V_2_out_blk_n, "kernel_val_2_V_2_out_blk_n");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

Block_proc::~Block_proc() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void Block_proc::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_0_V_0_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_0_V_1_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_0_V_2_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_1_V_0_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_1_V_1_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_1_V_2_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_2_V_0_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_2_V_1_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_2_V_2_out_full_n.read())))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
}

void Block_proc::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void Block_proc::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_0_V_0_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_0_V_1_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_0_V_2_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_1_V_0_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_1_V_1_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_1_V_2_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_2_V_0_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_2_V_1_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_2_V_2_out_full_n.read()));
}

void Block_proc::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_0_V_0_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_0_V_1_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_0_V_2_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_1_V_0_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_1_V_1_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_1_V_2_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_2_V_0_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_2_V_1_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_2_V_2_out_full_n.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void Block_proc::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void Block_proc::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_0_V_0_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_0_V_1_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_0_V_2_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_1_V_0_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_1_V_1_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_1_V_2_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_2_V_0_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_2_V_1_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_2_V_2_out_full_n.read())))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void Block_proc::thread_kernel_val_0_V_0_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        kernel_val_0_V_0_out_blk_n = kernel_val_0_V_0_out_full_n.read();
    } else {
        kernel_val_0_V_0_out_blk_n = ap_const_logic_1;
    }
}

void Block_proc::thread_kernel_val_0_V_0_out_din() {
    kernel_val_0_V_0_out_din = r1_V.read().range(8-1, 0);
}

void Block_proc::thread_kernel_val_0_V_0_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_0_V_0_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_0_V_1_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_0_V_2_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_1_V_0_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_1_V_1_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_1_V_2_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_2_V_0_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_2_V_1_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_2_V_2_out_full_n.read())))) {
        kernel_val_0_V_0_out_write = ap_const_logic_1;
    } else {
        kernel_val_0_V_0_out_write = ap_const_logic_0;
    }
}

void Block_proc::thread_kernel_val_0_V_1_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        kernel_val_0_V_1_out_blk_n = kernel_val_0_V_1_out_full_n.read();
    } else {
        kernel_val_0_V_1_out_blk_n = ap_const_logic_1;
    }
}

void Block_proc::thread_kernel_val_0_V_1_out_din() {
    kernel_val_0_V_1_out_din = r1_V.read().range(15, 8);
}

void Block_proc::thread_kernel_val_0_V_1_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_0_V_0_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_0_V_1_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_0_V_2_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_1_V_0_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_1_V_1_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_1_V_2_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_2_V_0_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_2_V_1_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_2_V_2_out_full_n.read())))) {
        kernel_val_0_V_1_out_write = ap_const_logic_1;
    } else {
        kernel_val_0_V_1_out_write = ap_const_logic_0;
    }
}

void Block_proc::thread_kernel_val_0_V_2_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        kernel_val_0_V_2_out_blk_n = kernel_val_0_V_2_out_full_n.read();
    } else {
        kernel_val_0_V_2_out_blk_n = ap_const_logic_1;
    }
}

void Block_proc::thread_kernel_val_0_V_2_out_din() {
    kernel_val_0_V_2_out_din = r1_V.read().range(23, 16);
}

void Block_proc::thread_kernel_val_0_V_2_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_0_V_0_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_0_V_1_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_0_V_2_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_1_V_0_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_1_V_1_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_1_V_2_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_2_V_0_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_2_V_1_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_2_V_2_out_full_n.read())))) {
        kernel_val_0_V_2_out_write = ap_const_logic_1;
    } else {
        kernel_val_0_V_2_out_write = ap_const_logic_0;
    }
}

void Block_proc::thread_kernel_val_1_V_0_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        kernel_val_1_V_0_out_blk_n = kernel_val_1_V_0_out_full_n.read();
    } else {
        kernel_val_1_V_0_out_blk_n = ap_const_logic_1;
    }
}

void Block_proc::thread_kernel_val_1_V_0_out_din() {
    kernel_val_1_V_0_out_din = r2_V.read().range(8-1, 0);
}

void Block_proc::thread_kernel_val_1_V_0_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_0_V_0_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_0_V_1_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_0_V_2_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_1_V_0_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_1_V_1_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_1_V_2_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_2_V_0_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_2_V_1_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_2_V_2_out_full_n.read())))) {
        kernel_val_1_V_0_out_write = ap_const_logic_1;
    } else {
        kernel_val_1_V_0_out_write = ap_const_logic_0;
    }
}

void Block_proc::thread_kernel_val_1_V_1_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        kernel_val_1_V_1_out_blk_n = kernel_val_1_V_1_out_full_n.read();
    } else {
        kernel_val_1_V_1_out_blk_n = ap_const_logic_1;
    }
}

void Block_proc::thread_kernel_val_1_V_1_out_din() {
    kernel_val_1_V_1_out_din = r2_V.read().range(15, 8);
}

void Block_proc::thread_kernel_val_1_V_1_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_0_V_0_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_0_V_1_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_0_V_2_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_1_V_0_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_1_V_1_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_1_V_2_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_2_V_0_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_2_V_1_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_2_V_2_out_full_n.read())))) {
        kernel_val_1_V_1_out_write = ap_const_logic_1;
    } else {
        kernel_val_1_V_1_out_write = ap_const_logic_0;
    }
}

void Block_proc::thread_kernel_val_1_V_2_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        kernel_val_1_V_2_out_blk_n = kernel_val_1_V_2_out_full_n.read();
    } else {
        kernel_val_1_V_2_out_blk_n = ap_const_logic_1;
    }
}

void Block_proc::thread_kernel_val_1_V_2_out_din() {
    kernel_val_1_V_2_out_din = r2_V.read().range(23, 16);
}

void Block_proc::thread_kernel_val_1_V_2_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_0_V_0_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_0_V_1_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_0_V_2_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_1_V_0_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_1_V_1_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_1_V_2_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_2_V_0_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_2_V_1_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_2_V_2_out_full_n.read())))) {
        kernel_val_1_V_2_out_write = ap_const_logic_1;
    } else {
        kernel_val_1_V_2_out_write = ap_const_logic_0;
    }
}

void Block_proc::thread_kernel_val_2_V_0_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        kernel_val_2_V_0_out_blk_n = kernel_val_2_V_0_out_full_n.read();
    } else {
        kernel_val_2_V_0_out_blk_n = ap_const_logic_1;
    }
}

void Block_proc::thread_kernel_val_2_V_0_out_din() {
    kernel_val_2_V_0_out_din = r3_V.read().range(8-1, 0);
}

void Block_proc::thread_kernel_val_2_V_0_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_0_V_0_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_0_V_1_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_0_V_2_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_1_V_0_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_1_V_1_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_1_V_2_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_2_V_0_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_2_V_1_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_2_V_2_out_full_n.read())))) {
        kernel_val_2_V_0_out_write = ap_const_logic_1;
    } else {
        kernel_val_2_V_0_out_write = ap_const_logic_0;
    }
}

void Block_proc::thread_kernel_val_2_V_1_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        kernel_val_2_V_1_out_blk_n = kernel_val_2_V_1_out_full_n.read();
    } else {
        kernel_val_2_V_1_out_blk_n = ap_const_logic_1;
    }
}

void Block_proc::thread_kernel_val_2_V_1_out_din() {
    kernel_val_2_V_1_out_din = r3_V.read().range(15, 8);
}

void Block_proc::thread_kernel_val_2_V_1_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_0_V_0_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_0_V_1_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_0_V_2_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_1_V_0_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_1_V_1_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_1_V_2_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_2_V_0_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_2_V_1_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_2_V_2_out_full_n.read())))) {
        kernel_val_2_V_1_out_write = ap_const_logic_1;
    } else {
        kernel_val_2_V_1_out_write = ap_const_logic_0;
    }
}

void Block_proc::thread_kernel_val_2_V_2_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        kernel_val_2_V_2_out_blk_n = kernel_val_2_V_2_out_full_n.read();
    } else {
        kernel_val_2_V_2_out_blk_n = ap_const_logic_1;
    }
}

void Block_proc::thread_kernel_val_2_V_2_out_din() {
    kernel_val_2_V_2_out_din = r3_V.read().range(23, 16);
}

void Block_proc::thread_kernel_val_2_V_2_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_0_V_0_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_0_V_1_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_0_V_2_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_1_V_0_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_1_V_1_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_1_V_2_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_2_V_0_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_2_V_1_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, kernel_val_2_V_2_out_full_n.read())))) {
        kernel_val_2_V_2_out_write = ap_const_logic_1;
    } else {
        kernel_val_2_V_2_out_write = ap_const_logic_0;
    }
}

void Block_proc::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_state1;
break;
        default : 
            ap_NS_fsm = "X";
            break;
    }
}

}

