// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "filter2D_hls.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const int filter2D_hls::C_S_AXI_DATA_WIDTH = "100000";
const int filter2D_hls::C_S_AXI_WSTRB_WIDTH = "100";
const int filter2D_hls::C_S_AXI_ADDR_WIDTH = "100000";
const sc_logic filter2D_hls::ap_const_logic_1 = sc_dt::Log_1;
const sc_lv<32> filter2D_hls::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> filter2D_hls::ap_const_lv1_0 = "0";
const sc_logic filter2D_hls::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> filter2D_hls::ap_const_lv2_0 = "00";
const sc_lv<2> filter2D_hls::ap_const_lv2_1 = "1";
const bool filter2D_hls::ap_const_boolean_1 = true;

filter2D_hls::filter2D_hls(sc_module_name name) : sc_module(name), mVcdFile(0) {
    filter2D_hls_CONTROL_BUS_s_axi_U = new filter2D_hls_CONTROL_BUS_s_axi<C_S_AXI_CONTROL_BUS_ADDR_WIDTH,C_S_AXI_CONTROL_BUS_DATA_WIDTH>("filter2D_hls_CONTROL_BUS_s_axi_U");
    filter2D_hls_CONTROL_BUS_s_axi_U->AWVALID(s_axi_CONTROL_BUS_AWVALID);
    filter2D_hls_CONTROL_BUS_s_axi_U->AWREADY(s_axi_CONTROL_BUS_AWREADY);
    filter2D_hls_CONTROL_BUS_s_axi_U->AWADDR(s_axi_CONTROL_BUS_AWADDR);
    filter2D_hls_CONTROL_BUS_s_axi_U->WVALID(s_axi_CONTROL_BUS_WVALID);
    filter2D_hls_CONTROL_BUS_s_axi_U->WREADY(s_axi_CONTROL_BUS_WREADY);
    filter2D_hls_CONTROL_BUS_s_axi_U->WDATA(s_axi_CONTROL_BUS_WDATA);
    filter2D_hls_CONTROL_BUS_s_axi_U->WSTRB(s_axi_CONTROL_BUS_WSTRB);
    filter2D_hls_CONTROL_BUS_s_axi_U->ARVALID(s_axi_CONTROL_BUS_ARVALID);
    filter2D_hls_CONTROL_BUS_s_axi_U->ARREADY(s_axi_CONTROL_BUS_ARREADY);
    filter2D_hls_CONTROL_BUS_s_axi_U->ARADDR(s_axi_CONTROL_BUS_ARADDR);
    filter2D_hls_CONTROL_BUS_s_axi_U->RVALID(s_axi_CONTROL_BUS_RVALID);
    filter2D_hls_CONTROL_BUS_s_axi_U->RREADY(s_axi_CONTROL_BUS_RREADY);
    filter2D_hls_CONTROL_BUS_s_axi_U->RDATA(s_axi_CONTROL_BUS_RDATA);
    filter2D_hls_CONTROL_BUS_s_axi_U->RRESP(s_axi_CONTROL_BUS_RRESP);
    filter2D_hls_CONTROL_BUS_s_axi_U->BVALID(s_axi_CONTROL_BUS_BVALID);
    filter2D_hls_CONTROL_BUS_s_axi_U->BREADY(s_axi_CONTROL_BUS_BREADY);
    filter2D_hls_CONTROL_BUS_s_axi_U->BRESP(s_axi_CONTROL_BUS_BRESP);
    filter2D_hls_CONTROL_BUS_s_axi_U->ACLK(AXI_LITE_clk);
    filter2D_hls_CONTROL_BUS_s_axi_U->ARESET(ap_rst_n_inv);
    filter2D_hls_CONTROL_BUS_s_axi_U->ACLK_EN(ap_var_for_const0);
    filter2D_hls_CONTROL_BUS_s_axi_U->rows(rows);
    filter2D_hls_CONTROL_BUS_s_axi_U->cols(cols);
    filter2D_hls_CONTROL_BUS_s_axi_U->channels(channels);
    filter2D_hls_CONTROL_BUS_s_axi_U->mode(mode);
    filter2D_hls_CONTROL_BUS_s_axi_U->r1_V(r1_V);
    filter2D_hls_CONTROL_BUS_s_axi_U->r2_V(r2_V);
    filter2D_hls_CONTROL_BUS_s_axi_U->r3_V(r3_V);
    filter2D_hls_CONTROL_BUS_s_axi_U->ap_start(ap_start);
    filter2D_hls_CONTROL_BUS_s_axi_U->interrupt(interrupt);
    filter2D_hls_CONTROL_BUS_s_axi_U->ap_ready(ap_ready);
    filter2D_hls_CONTROL_BUS_s_axi_U->ap_done(ap_done);
    filter2D_hls_CONTROL_BUS_s_axi_U->ap_idle(ap_idle);
    filter2D_hls_CONTROL_BUS_s_axi_U->clk(ap_clk);
    filter2D_hls_CONTROL_BUS_s_axi_U->rst(ap_rst_n_AXI_LITE_clk_inv);
    Block_Mat_exit38593_U0 = new Block_Mat_exit38593_s("Block_Mat_exit38593_U0");
    Block_Mat_exit38593_U0->ap_clk(ap_clk);
    Block_Mat_exit38593_U0->ap_rst(ap_rst_n_inv);
    Block_Mat_exit38593_U0->ap_start(Block_Mat_exit38593_U0_ap_start);
    Block_Mat_exit38593_U0->start_full_n(start_for_Loop_2_proc_U0_full_n);
    Block_Mat_exit38593_U0->ap_done(Block_Mat_exit38593_U0_ap_done);
    Block_Mat_exit38593_U0->ap_continue(Block_Mat_exit38593_U0_ap_continue);
    Block_Mat_exit38593_U0->ap_idle(Block_Mat_exit38593_U0_ap_idle);
    Block_Mat_exit38593_U0->ap_ready(Block_Mat_exit38593_U0_ap_ready);
    Block_Mat_exit38593_U0->start_out(Block_Mat_exit38593_U0_start_out);
    Block_Mat_exit38593_U0->start_write(Block_Mat_exit38593_U0_start_write);
    Block_Mat_exit38593_U0->channels(channels);
    Block_Mat_exit38593_U0->cols(cols);
    Block_Mat_exit38593_U0->rows(rows);
    Block_Mat_exit38593_U0->col_packets_out_out_din(Block_Mat_exit38593_U0_col_packets_out_out_din);
    Block_Mat_exit38593_U0->col_packets_out_out_full_n(col_packets_loc_c_full_n);
    Block_Mat_exit38593_U0->col_packets_out_out_write(Block_Mat_exit38593_U0_col_packets_out_out_write);
    Block_Mat_exit38593_U0->col_packets_cast_out_out_din(Block_Mat_exit38593_U0_col_packets_cast_out_out_din);
    Block_Mat_exit38593_U0->col_packets_cast_out_out_full_n(ap_var_for_const0);
    Block_Mat_exit38593_U0->col_packets_cast_out_out_write(Block_Mat_exit38593_U0_col_packets_cast_out_out_write);
    Block_Mat_exit38593_U0->ap_return(Block_Mat_exit38593_U0_ap_return);
    Loop_1_proc_U0 = new Loop_1_proc("Loop_1_proc_U0");
    Loop_1_proc_U0->ap_clk(ap_clk);
    Loop_1_proc_U0->ap_rst(ap_rst_n_inv);
    Loop_1_proc_U0->ap_start(Loop_1_proc_U0_ap_start);
    Loop_1_proc_U0->start_full_n(start_for_Filter2D_U0_full_n);
    Loop_1_proc_U0->ap_done(Loop_1_proc_U0_ap_done);
    Loop_1_proc_U0->ap_continue(Loop_1_proc_U0_ap_continue);
    Loop_1_proc_U0->ap_idle(Loop_1_proc_U0_ap_idle);
    Loop_1_proc_U0->ap_ready(Loop_1_proc_U0_ap_ready);
    Loop_1_proc_U0->start_out(Loop_1_proc_U0_start_out);
    Loop_1_proc_U0->start_write(Loop_1_proc_U0_start_write);
    Loop_1_proc_U0->p_read(packets_loc_channel_dout);
    Loop_1_proc_U0->in_stream_TDATA(in_stream_TDATA);
    Loop_1_proc_U0->in_stream_TVALID(in_stream_TVALID);
    Loop_1_proc_U0->in_stream_TREADY(Loop_1_proc_U0_in_stream_TREADY);
    Loop_1_proc_U0->g_img_0_data_stream_0_V_din(Loop_1_proc_U0_g_img_0_data_stream_0_V_din);
    Loop_1_proc_U0->g_img_0_data_stream_0_V_full_n(g_img_0_data_stream_s_full_n);
    Loop_1_proc_U0->g_img_0_data_stream_0_V_write(Loop_1_proc_U0_g_img_0_data_stream_0_V_write);
    Block_proc_U0 = new Block_proc("Block_proc_U0");
    Block_proc_U0->ap_clk(ap_clk);
    Block_proc_U0->ap_rst(ap_rst_n_inv);
    Block_proc_U0->ap_start(Block_proc_U0_ap_start);
    Block_proc_U0->ap_done(Block_proc_U0_ap_done);
    Block_proc_U0->ap_continue(Block_proc_U0_ap_continue);
    Block_proc_U0->ap_idle(Block_proc_U0_ap_idle);
    Block_proc_U0->ap_ready(Block_proc_U0_ap_ready);
    Block_proc_U0->r1_V(r1_V);
    Block_proc_U0->r2_V(r2_V);
    Block_proc_U0->r3_V(r3_V);
    Block_proc_U0->kernel_val_0_V_0_out_din(Block_proc_U0_kernel_val_0_V_0_out_din);
    Block_proc_U0->kernel_val_0_V_0_out_full_n(kernel_val_0_V_0_c_full_n);
    Block_proc_U0->kernel_val_0_V_0_out_write(Block_proc_U0_kernel_val_0_V_0_out_write);
    Block_proc_U0->kernel_val_0_V_1_out_din(Block_proc_U0_kernel_val_0_V_1_out_din);
    Block_proc_U0->kernel_val_0_V_1_out_full_n(kernel_val_0_V_1_c_full_n);
    Block_proc_U0->kernel_val_0_V_1_out_write(Block_proc_U0_kernel_val_0_V_1_out_write);
    Block_proc_U0->kernel_val_0_V_2_out_din(Block_proc_U0_kernel_val_0_V_2_out_din);
    Block_proc_U0->kernel_val_0_V_2_out_full_n(kernel_val_0_V_2_c_full_n);
    Block_proc_U0->kernel_val_0_V_2_out_write(Block_proc_U0_kernel_val_0_V_2_out_write);
    Block_proc_U0->kernel_val_1_V_0_out_din(Block_proc_U0_kernel_val_1_V_0_out_din);
    Block_proc_U0->kernel_val_1_V_0_out_full_n(kernel_val_1_V_0_c_full_n);
    Block_proc_U0->kernel_val_1_V_0_out_write(Block_proc_U0_kernel_val_1_V_0_out_write);
    Block_proc_U0->kernel_val_1_V_1_out_din(Block_proc_U0_kernel_val_1_V_1_out_din);
    Block_proc_U0->kernel_val_1_V_1_out_full_n(kernel_val_1_V_1_c_full_n);
    Block_proc_U0->kernel_val_1_V_1_out_write(Block_proc_U0_kernel_val_1_V_1_out_write);
    Block_proc_U0->kernel_val_1_V_2_out_din(Block_proc_U0_kernel_val_1_V_2_out_din);
    Block_proc_U0->kernel_val_1_V_2_out_full_n(kernel_val_1_V_2_c_full_n);
    Block_proc_U0->kernel_val_1_V_2_out_write(Block_proc_U0_kernel_val_1_V_2_out_write);
    Block_proc_U0->kernel_val_2_V_0_out_din(Block_proc_U0_kernel_val_2_V_0_out_din);
    Block_proc_U0->kernel_val_2_V_0_out_full_n(kernel_val_2_V_0_c_full_n);
    Block_proc_U0->kernel_val_2_V_0_out_write(Block_proc_U0_kernel_val_2_V_0_out_write);
    Block_proc_U0->kernel_val_2_V_1_out_din(Block_proc_U0_kernel_val_2_V_1_out_din);
    Block_proc_U0->kernel_val_2_V_1_out_full_n(kernel_val_2_V_1_c_full_n);
    Block_proc_U0->kernel_val_2_V_1_out_write(Block_proc_U0_kernel_val_2_V_1_out_write);
    Block_proc_U0->kernel_val_2_V_2_out_din(Block_proc_U0_kernel_val_2_V_2_out_din);
    Block_proc_U0->kernel_val_2_V_2_out_full_n(kernel_val_2_V_2_c_full_n);
    Block_proc_U0->kernel_val_2_V_2_out_write(Block_proc_U0_kernel_val_2_V_2_out_write);
    Filter2D_U0 = new Filter2D("Filter2D_U0");
    Filter2D_U0->ap_clk(ap_clk);
    Filter2D_U0->ap_rst(ap_rst_n_inv);
    Filter2D_U0->ap_start(Filter2D_U0_ap_start);
    Filter2D_U0->ap_done(Filter2D_U0_ap_done);
    Filter2D_U0->ap_continue(Filter2D_U0_ap_continue);
    Filter2D_U0->ap_idle(Filter2D_U0_ap_idle);
    Filter2D_U0->ap_ready(Filter2D_U0_ap_ready);
    Filter2D_U0->p_src_rows_V(rows);
    Filter2D_U0->p_src_cols_V(cols);
    Filter2D_U0->p_src_data_stream_V_dout(g_img_0_data_stream_s_dout);
    Filter2D_U0->p_src_data_stream_V_empty_n(g_img_0_data_stream_s_empty_n);
    Filter2D_U0->p_src_data_stream_V_read(Filter2D_U0_p_src_data_stream_V_read);
    Filter2D_U0->p_dst_data_stream_V_din(Filter2D_U0_p_dst_data_stream_V_din);
    Filter2D_U0->p_dst_data_stream_V_full_n(g_img_1_data_stream_s_full_n);
    Filter2D_U0->p_dst_data_stream_V_write(Filter2D_U0_p_dst_data_stream_V_write);
    Filter2D_U0->p_kernel_val_0_V_0_dout(kernel_val_0_V_0_c_dout);
    Filter2D_U0->p_kernel_val_0_V_0_empty_n(kernel_val_0_V_0_c_empty_n);
    Filter2D_U0->p_kernel_val_0_V_0_read(Filter2D_U0_p_kernel_val_0_V_0_read);
    Filter2D_U0->p_kernel_val_0_V_1_dout(kernel_val_0_V_1_c_dout);
    Filter2D_U0->p_kernel_val_0_V_1_empty_n(kernel_val_0_V_1_c_empty_n);
    Filter2D_U0->p_kernel_val_0_V_1_read(Filter2D_U0_p_kernel_val_0_V_1_read);
    Filter2D_U0->p_kernel_val_0_V_2_dout(kernel_val_0_V_2_c_dout);
    Filter2D_U0->p_kernel_val_0_V_2_empty_n(kernel_val_0_V_2_c_empty_n);
    Filter2D_U0->p_kernel_val_0_V_2_read(Filter2D_U0_p_kernel_val_0_V_2_read);
    Filter2D_U0->p_kernel_val_1_V_0_dout(kernel_val_1_V_0_c_dout);
    Filter2D_U0->p_kernel_val_1_V_0_empty_n(kernel_val_1_V_0_c_empty_n);
    Filter2D_U0->p_kernel_val_1_V_0_read(Filter2D_U0_p_kernel_val_1_V_0_read);
    Filter2D_U0->p_kernel_val_1_V_1_dout(kernel_val_1_V_1_c_dout);
    Filter2D_U0->p_kernel_val_1_V_1_empty_n(kernel_val_1_V_1_c_empty_n);
    Filter2D_U0->p_kernel_val_1_V_1_read(Filter2D_U0_p_kernel_val_1_V_1_read);
    Filter2D_U0->p_kernel_val_1_V_2_dout(kernel_val_1_V_2_c_dout);
    Filter2D_U0->p_kernel_val_1_V_2_empty_n(kernel_val_1_V_2_c_empty_n);
    Filter2D_U0->p_kernel_val_1_V_2_read(Filter2D_U0_p_kernel_val_1_V_2_read);
    Filter2D_U0->p_kernel_val_2_V_0_dout(kernel_val_2_V_0_c_dout);
    Filter2D_U0->p_kernel_val_2_V_0_empty_n(kernel_val_2_V_0_c_empty_n);
    Filter2D_U0->p_kernel_val_2_V_0_read(Filter2D_U0_p_kernel_val_2_V_0_read);
    Filter2D_U0->p_kernel_val_2_V_1_dout(kernel_val_2_V_1_c_dout);
    Filter2D_U0->p_kernel_val_2_V_1_empty_n(kernel_val_2_V_1_c_empty_n);
    Filter2D_U0->p_kernel_val_2_V_1_read(Filter2D_U0_p_kernel_val_2_V_1_read);
    Filter2D_U0->p_kernel_val_2_V_2_dout(kernel_val_2_V_2_c_dout);
    Filter2D_U0->p_kernel_val_2_V_2_empty_n(kernel_val_2_V_2_c_empty_n);
    Filter2D_U0->p_kernel_val_2_V_2_read(Filter2D_U0_p_kernel_val_2_V_2_read);
    Loop_2_proc_U0 = new Loop_2_proc("Loop_2_proc_U0");
    Loop_2_proc_U0->ap_clk(ap_clk);
    Loop_2_proc_U0->ap_rst(ap_rst_n_inv);
    Loop_2_proc_U0->ap_start(Loop_2_proc_U0_ap_start);
    Loop_2_proc_U0->ap_done(Loop_2_proc_U0_ap_done);
    Loop_2_proc_U0->ap_continue(Loop_2_proc_U0_ap_continue);
    Loop_2_proc_U0->ap_idle(Loop_2_proc_U0_ap_idle);
    Loop_2_proc_U0->ap_ready(Loop_2_proc_U0_ap_ready);
    Loop_2_proc_U0->rows(rows);
    Loop_2_proc_U0->col_packets_loc_dout(col_packets_loc_c_dout);
    Loop_2_proc_U0->col_packets_loc_empty_n(col_packets_loc_c_empty_n);
    Loop_2_proc_U0->col_packets_loc_read(Loop_2_proc_U0_col_packets_loc_read);
    Loop_2_proc_U0->out_stream_TDATA(Loop_2_proc_U0_out_stream_TDATA);
    Loop_2_proc_U0->out_stream_TVALID(Loop_2_proc_U0_out_stream_TVALID);
    Loop_2_proc_U0->out_stream_TREADY(out_stream_TREADY);
    Loop_2_proc_U0->g_img_1_data_stream_0_V_dout(g_img_1_data_stream_s_dout);
    Loop_2_proc_U0->g_img_1_data_stream_0_V_empty_n(g_img_1_data_stream_s_empty_n);
    Loop_2_proc_U0->g_img_1_data_stream_0_V_read(Loop_2_proc_U0_g_img_1_data_stream_0_V_read);
    Loop_2_proc_U0->out_stream_TUSER(Loop_2_proc_U0_out_stream_TUSER);
    Loop_2_proc_U0->out_stream_TLAST(Loop_2_proc_U0_out_stream_TLAST);
    col_packets_loc_c_U = new fifo_w31_d4_A("col_packets_loc_c_U");
    col_packets_loc_c_U->clk(ap_clk);
    col_packets_loc_c_U->reset(ap_rst_n_inv);
    col_packets_loc_c_U->if_read_ce(ap_var_for_const0);
    col_packets_loc_c_U->if_write_ce(ap_var_for_const0);
    col_packets_loc_c_U->if_din(Block_Mat_exit38593_U0_col_packets_out_out_din);
    col_packets_loc_c_U->if_full_n(col_packets_loc_c_full_n);
    col_packets_loc_c_U->if_write(Block_Mat_exit38593_U0_col_packets_out_out_write);
    col_packets_loc_c_U->if_dout(col_packets_loc_c_dout);
    col_packets_loc_c_U->if_empty_n(col_packets_loc_c_empty_n);
    col_packets_loc_c_U->if_read(Loop_2_proc_U0_col_packets_loc_read);
    packets_loc_channel_U = new fifo_w32_d2_A("packets_loc_channel_U");
    packets_loc_channel_U->clk(ap_clk);
    packets_loc_channel_U->reset(ap_rst_n_inv);
    packets_loc_channel_U->if_read_ce(ap_var_for_const0);
    packets_loc_channel_U->if_write_ce(ap_var_for_const0);
    packets_loc_channel_U->if_din(Block_Mat_exit38593_U0_ap_return);
    packets_loc_channel_U->if_full_n(packets_loc_channel_full_n);
    packets_loc_channel_U->if_write(Block_Mat_exit38593_U0_ap_done);
    packets_loc_channel_U->if_dout(packets_loc_channel_dout);
    packets_loc_channel_U->if_empty_n(packets_loc_channel_empty_n);
    packets_loc_channel_U->if_read(Loop_1_proc_U0_ap_ready);
    g_img_0_data_stream_s_U = new fifo_w8_d2_A("g_img_0_data_stream_s_U");
    g_img_0_data_stream_s_U->clk(ap_clk);
    g_img_0_data_stream_s_U->reset(ap_rst_n_inv);
    g_img_0_data_stream_s_U->if_read_ce(ap_var_for_const0);
    g_img_0_data_stream_s_U->if_write_ce(ap_var_for_const0);
    g_img_0_data_stream_s_U->if_din(Loop_1_proc_U0_g_img_0_data_stream_0_V_din);
    g_img_0_data_stream_s_U->if_full_n(g_img_0_data_stream_s_full_n);
    g_img_0_data_stream_s_U->if_write(Loop_1_proc_U0_g_img_0_data_stream_0_V_write);
    g_img_0_data_stream_s_U->if_dout(g_img_0_data_stream_s_dout);
    g_img_0_data_stream_s_U->if_empty_n(g_img_0_data_stream_s_empty_n);
    g_img_0_data_stream_s_U->if_read(Filter2D_U0_p_src_data_stream_V_read);
    kernel_val_0_V_0_c_U = new fifo_w8_d3_A("kernel_val_0_V_0_c_U");
    kernel_val_0_V_0_c_U->clk(ap_clk);
    kernel_val_0_V_0_c_U->reset(ap_rst_n_inv);
    kernel_val_0_V_0_c_U->if_read_ce(ap_var_for_const0);
    kernel_val_0_V_0_c_U->if_write_ce(ap_var_for_const0);
    kernel_val_0_V_0_c_U->if_din(Block_proc_U0_kernel_val_0_V_0_out_din);
    kernel_val_0_V_0_c_U->if_full_n(kernel_val_0_V_0_c_full_n);
    kernel_val_0_V_0_c_U->if_write(Block_proc_U0_kernel_val_0_V_0_out_write);
    kernel_val_0_V_0_c_U->if_dout(kernel_val_0_V_0_c_dout);
    kernel_val_0_V_0_c_U->if_empty_n(kernel_val_0_V_0_c_empty_n);
    kernel_val_0_V_0_c_U->if_read(Filter2D_U0_p_kernel_val_0_V_0_read);
    kernel_val_0_V_1_c_U = new fifo_w8_d3_A("kernel_val_0_V_1_c_U");
    kernel_val_0_V_1_c_U->clk(ap_clk);
    kernel_val_0_V_1_c_U->reset(ap_rst_n_inv);
    kernel_val_0_V_1_c_U->if_read_ce(ap_var_for_const0);
    kernel_val_0_V_1_c_U->if_write_ce(ap_var_for_const0);
    kernel_val_0_V_1_c_U->if_din(Block_proc_U0_kernel_val_0_V_1_out_din);
    kernel_val_0_V_1_c_U->if_full_n(kernel_val_0_V_1_c_full_n);
    kernel_val_0_V_1_c_U->if_write(Block_proc_U0_kernel_val_0_V_1_out_write);
    kernel_val_0_V_1_c_U->if_dout(kernel_val_0_V_1_c_dout);
    kernel_val_0_V_1_c_U->if_empty_n(kernel_val_0_V_1_c_empty_n);
    kernel_val_0_V_1_c_U->if_read(Filter2D_U0_p_kernel_val_0_V_1_read);
    kernel_val_0_V_2_c_U = new fifo_w8_d3_A("kernel_val_0_V_2_c_U");
    kernel_val_0_V_2_c_U->clk(ap_clk);
    kernel_val_0_V_2_c_U->reset(ap_rst_n_inv);
    kernel_val_0_V_2_c_U->if_read_ce(ap_var_for_const0);
    kernel_val_0_V_2_c_U->if_write_ce(ap_var_for_const0);
    kernel_val_0_V_2_c_U->if_din(Block_proc_U0_kernel_val_0_V_2_out_din);
    kernel_val_0_V_2_c_U->if_full_n(kernel_val_0_V_2_c_full_n);
    kernel_val_0_V_2_c_U->if_write(Block_proc_U0_kernel_val_0_V_2_out_write);
    kernel_val_0_V_2_c_U->if_dout(kernel_val_0_V_2_c_dout);
    kernel_val_0_V_2_c_U->if_empty_n(kernel_val_0_V_2_c_empty_n);
    kernel_val_0_V_2_c_U->if_read(Filter2D_U0_p_kernel_val_0_V_2_read);
    kernel_val_1_V_0_c_U = new fifo_w8_d3_A("kernel_val_1_V_0_c_U");
    kernel_val_1_V_0_c_U->clk(ap_clk);
    kernel_val_1_V_0_c_U->reset(ap_rst_n_inv);
    kernel_val_1_V_0_c_U->if_read_ce(ap_var_for_const0);
    kernel_val_1_V_0_c_U->if_write_ce(ap_var_for_const0);
    kernel_val_1_V_0_c_U->if_din(Block_proc_U0_kernel_val_1_V_0_out_din);
    kernel_val_1_V_0_c_U->if_full_n(kernel_val_1_V_0_c_full_n);
    kernel_val_1_V_0_c_U->if_write(Block_proc_U0_kernel_val_1_V_0_out_write);
    kernel_val_1_V_0_c_U->if_dout(kernel_val_1_V_0_c_dout);
    kernel_val_1_V_0_c_U->if_empty_n(kernel_val_1_V_0_c_empty_n);
    kernel_val_1_V_0_c_U->if_read(Filter2D_U0_p_kernel_val_1_V_0_read);
    kernel_val_1_V_1_c_U = new fifo_w8_d3_A("kernel_val_1_V_1_c_U");
    kernel_val_1_V_1_c_U->clk(ap_clk);
    kernel_val_1_V_1_c_U->reset(ap_rst_n_inv);
    kernel_val_1_V_1_c_U->if_read_ce(ap_var_for_const0);
    kernel_val_1_V_1_c_U->if_write_ce(ap_var_for_const0);
    kernel_val_1_V_1_c_U->if_din(Block_proc_U0_kernel_val_1_V_1_out_din);
    kernel_val_1_V_1_c_U->if_full_n(kernel_val_1_V_1_c_full_n);
    kernel_val_1_V_1_c_U->if_write(Block_proc_U0_kernel_val_1_V_1_out_write);
    kernel_val_1_V_1_c_U->if_dout(kernel_val_1_V_1_c_dout);
    kernel_val_1_V_1_c_U->if_empty_n(kernel_val_1_V_1_c_empty_n);
    kernel_val_1_V_1_c_U->if_read(Filter2D_U0_p_kernel_val_1_V_1_read);
    kernel_val_1_V_2_c_U = new fifo_w8_d3_A("kernel_val_1_V_2_c_U");
    kernel_val_1_V_2_c_U->clk(ap_clk);
    kernel_val_1_V_2_c_U->reset(ap_rst_n_inv);
    kernel_val_1_V_2_c_U->if_read_ce(ap_var_for_const0);
    kernel_val_1_V_2_c_U->if_write_ce(ap_var_for_const0);
    kernel_val_1_V_2_c_U->if_din(Block_proc_U0_kernel_val_1_V_2_out_din);
    kernel_val_1_V_2_c_U->if_full_n(kernel_val_1_V_2_c_full_n);
    kernel_val_1_V_2_c_U->if_write(Block_proc_U0_kernel_val_1_V_2_out_write);
    kernel_val_1_V_2_c_U->if_dout(kernel_val_1_V_2_c_dout);
    kernel_val_1_V_2_c_U->if_empty_n(kernel_val_1_V_2_c_empty_n);
    kernel_val_1_V_2_c_U->if_read(Filter2D_U0_p_kernel_val_1_V_2_read);
    kernel_val_2_V_0_c_U = new fifo_w8_d3_A("kernel_val_2_V_0_c_U");
    kernel_val_2_V_0_c_U->clk(ap_clk);
    kernel_val_2_V_0_c_U->reset(ap_rst_n_inv);
    kernel_val_2_V_0_c_U->if_read_ce(ap_var_for_const0);
    kernel_val_2_V_0_c_U->if_write_ce(ap_var_for_const0);
    kernel_val_2_V_0_c_U->if_din(Block_proc_U0_kernel_val_2_V_0_out_din);
    kernel_val_2_V_0_c_U->if_full_n(kernel_val_2_V_0_c_full_n);
    kernel_val_2_V_0_c_U->if_write(Block_proc_U0_kernel_val_2_V_0_out_write);
    kernel_val_2_V_0_c_U->if_dout(kernel_val_2_V_0_c_dout);
    kernel_val_2_V_0_c_U->if_empty_n(kernel_val_2_V_0_c_empty_n);
    kernel_val_2_V_0_c_U->if_read(Filter2D_U0_p_kernel_val_2_V_0_read);
    kernel_val_2_V_1_c_U = new fifo_w8_d3_A("kernel_val_2_V_1_c_U");
    kernel_val_2_V_1_c_U->clk(ap_clk);
    kernel_val_2_V_1_c_U->reset(ap_rst_n_inv);
    kernel_val_2_V_1_c_U->if_read_ce(ap_var_for_const0);
    kernel_val_2_V_1_c_U->if_write_ce(ap_var_for_const0);
    kernel_val_2_V_1_c_U->if_din(Block_proc_U0_kernel_val_2_V_1_out_din);
    kernel_val_2_V_1_c_U->if_full_n(kernel_val_2_V_1_c_full_n);
    kernel_val_2_V_1_c_U->if_write(Block_proc_U0_kernel_val_2_V_1_out_write);
    kernel_val_2_V_1_c_U->if_dout(kernel_val_2_V_1_c_dout);
    kernel_val_2_V_1_c_U->if_empty_n(kernel_val_2_V_1_c_empty_n);
    kernel_val_2_V_1_c_U->if_read(Filter2D_U0_p_kernel_val_2_V_1_read);
    kernel_val_2_V_2_c_U = new fifo_w8_d3_A("kernel_val_2_V_2_c_U");
    kernel_val_2_V_2_c_U->clk(ap_clk);
    kernel_val_2_V_2_c_U->reset(ap_rst_n_inv);
    kernel_val_2_V_2_c_U->if_read_ce(ap_var_for_const0);
    kernel_val_2_V_2_c_U->if_write_ce(ap_var_for_const0);
    kernel_val_2_V_2_c_U->if_din(Block_proc_U0_kernel_val_2_V_2_out_din);
    kernel_val_2_V_2_c_U->if_full_n(kernel_val_2_V_2_c_full_n);
    kernel_val_2_V_2_c_U->if_write(Block_proc_U0_kernel_val_2_V_2_out_write);
    kernel_val_2_V_2_c_U->if_dout(kernel_val_2_V_2_c_dout);
    kernel_val_2_V_2_c_U->if_empty_n(kernel_val_2_V_2_c_empty_n);
    kernel_val_2_V_2_c_U->if_read(Filter2D_U0_p_kernel_val_2_V_2_read);
    g_img_1_data_stream_s_U = new fifo_w8_d2_A("g_img_1_data_stream_s_U");
    g_img_1_data_stream_s_U->clk(ap_clk);
    g_img_1_data_stream_s_U->reset(ap_rst_n_inv);
    g_img_1_data_stream_s_U->if_read_ce(ap_var_for_const0);
    g_img_1_data_stream_s_U->if_write_ce(ap_var_for_const0);
    g_img_1_data_stream_s_U->if_din(Filter2D_U0_p_dst_data_stream_V_din);
    g_img_1_data_stream_s_U->if_full_n(g_img_1_data_stream_s_full_n);
    g_img_1_data_stream_s_U->if_write(Filter2D_U0_p_dst_data_stream_V_write);
    g_img_1_data_stream_s_U->if_dout(g_img_1_data_stream_s_dout);
    g_img_1_data_stream_s_U->if_empty_n(g_img_1_data_stream_s_empty_n);
    g_img_1_data_stream_s_U->if_read(Loop_2_proc_U0_g_img_1_data_stream_0_V_read);
    start_for_Loop_2_hbi_U = new start_for_Loop_2_hbi("start_for_Loop_2_hbi_U");
    start_for_Loop_2_hbi_U->clk(ap_clk);
    start_for_Loop_2_hbi_U->reset(ap_rst_n_inv);
    start_for_Loop_2_hbi_U->if_read_ce(ap_var_for_const0);
    start_for_Loop_2_hbi_U->if_write_ce(ap_var_for_const0);
    start_for_Loop_2_hbi_U->if_din(start_for_Loop_2_proc_U0_din);
    start_for_Loop_2_hbi_U->if_full_n(start_for_Loop_2_proc_U0_full_n);
    start_for_Loop_2_hbi_U->if_write(Block_Mat_exit38593_U0_start_write);
    start_for_Loop_2_hbi_U->if_dout(start_for_Loop_2_proc_U0_dout);
    start_for_Loop_2_hbi_U->if_empty_n(start_for_Loop_2_proc_U0_empty_n);
    start_for_Loop_2_hbi_U->if_read(Loop_2_proc_U0_ap_ready);
    start_for_Filter2ibs_U = new start_for_Filter2ibs("start_for_Filter2ibs_U");
    start_for_Filter2ibs_U->clk(ap_clk);
    start_for_Filter2ibs_U->reset(ap_rst_n_inv);
    start_for_Filter2ibs_U->if_read_ce(ap_var_for_const0);
    start_for_Filter2ibs_U->if_write_ce(ap_var_for_const0);
    start_for_Filter2ibs_U->if_din(start_for_Filter2D_U0_din);
    start_for_Filter2ibs_U->if_full_n(start_for_Filter2D_U0_full_n);
    start_for_Filter2ibs_U->if_write(Loop_1_proc_U0_start_write);
    start_for_Filter2ibs_U->if_dout(start_for_Filter2D_U0_dout);
    start_for_Filter2ibs_U->if_empty_n(start_for_Filter2D_U0_empty_n);
    start_for_Filter2ibs_U->if_read(Filter2D_U0_ap_ready);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_Block_Mat_exit38593_U0_ap_continue);
    sensitive << ( packets_loc_channel_full_n );

    SC_METHOD(thread_Block_Mat_exit38593_U0_ap_start);
    sensitive << ( ap_start );
    sensitive << ( ap_sync_reg_Block_Mat_exit38593_U0_ap_ready );

    SC_METHOD(thread_Block_proc_U0_ap_continue);

    SC_METHOD(thread_Block_proc_U0_ap_start);
    sensitive << ( ap_start );
    sensitive << ( ap_sync_reg_Block_proc_U0_ap_ready );

    SC_METHOD(thread_Block_proc_U0_start_full_n);

    SC_METHOD(thread_Block_proc_U0_start_write);

    SC_METHOD(thread_Filter2D_U0_ap_continue);

    SC_METHOD(thread_Filter2D_U0_ap_start);
    sensitive << ( start_for_Filter2D_U0_empty_n );

    SC_METHOD(thread_Filter2D_U0_start_full_n);

    SC_METHOD(thread_Filter2D_U0_start_write);

    SC_METHOD(thread_Loop_1_proc_U0_ap_continue);

    SC_METHOD(thread_Loop_1_proc_U0_ap_start);
    sensitive << ( ap_start );
    sensitive << ( packets_loc_channel_empty_n );
    sensitive << ( ap_sync_reg_Loop_1_proc_U0_ap_ready );

    SC_METHOD(thread_Loop_2_proc_U0_ap_continue);

    SC_METHOD(thread_Loop_2_proc_U0_ap_start);
    sensitive << ( start_for_Loop_2_proc_U0_empty_n );

    SC_METHOD(thread_Loop_2_proc_U0_start_full_n);

    SC_METHOD(thread_Loop_2_proc_U0_start_write);

    SC_METHOD(thread_ap_channel_done_packets_loc_channel);
    sensitive << ( Block_Mat_exit38593_U0_ap_done );

    SC_METHOD(thread_ap_done);
    sensitive << ( Loop_2_proc_U0_ap_done );

    SC_METHOD(thread_ap_idle);
    sensitive << ( Block_Mat_exit38593_U0_ap_idle );
    sensitive << ( Loop_1_proc_U0_ap_idle );
    sensitive << ( Block_proc_U0_ap_idle );
    sensitive << ( Filter2D_U0_ap_idle );
    sensitive << ( Loop_2_proc_U0_ap_idle );
    sensitive << ( packets_loc_channel_empty_n );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sync_ready );

    SC_METHOD(thread_ap_rst_n_AXI_LITE_clk_inv);
    sensitive << ( ap_rst_n_AXI_LITE_clk );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_ap_sync_Block_Mat_exit38593_U0_ap_ready);
    sensitive << ( Block_Mat_exit38593_U0_ap_ready );
    sensitive << ( ap_sync_reg_Block_Mat_exit38593_U0_ap_ready );

    SC_METHOD(thread_ap_sync_Block_proc_U0_ap_ready);
    sensitive << ( Block_proc_U0_ap_ready );
    sensitive << ( ap_sync_reg_Block_proc_U0_ap_ready );

    SC_METHOD(thread_ap_sync_Loop_1_proc_U0_ap_ready);
    sensitive << ( Loop_1_proc_U0_ap_ready );
    sensitive << ( ap_sync_reg_Loop_1_proc_U0_ap_ready );

    SC_METHOD(thread_ap_sync_continue);

    SC_METHOD(thread_ap_sync_done);
    sensitive << ( Loop_2_proc_U0_ap_done );

    SC_METHOD(thread_ap_sync_ready);
    sensitive << ( ap_sync_Block_Mat_exit38593_U0_ap_ready );
    sensitive << ( ap_sync_Loop_1_proc_U0_ap_ready );
    sensitive << ( ap_sync_Block_proc_U0_ap_ready );

    SC_METHOD(thread_in_stream_TREADY);
    sensitive << ( Loop_1_proc_U0_in_stream_TREADY );

    SC_METHOD(thread_out_stream_TDATA);
    sensitive << ( Loop_2_proc_U0_out_stream_TDATA );

    SC_METHOD(thread_out_stream_TLAST);
    sensitive << ( Loop_2_proc_U0_out_stream_TLAST );

    SC_METHOD(thread_out_stream_TUSER);
    sensitive << ( Loop_2_proc_U0_out_stream_TUSER );

    SC_METHOD(thread_out_stream_TVALID);
    sensitive << ( Loop_2_proc_U0_out_stream_TVALID );

    SC_METHOD(thread_start_for_Filter2D_U0_din);

    SC_METHOD(thread_start_for_Loop_2_proc_U0_din);

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    ap_sync_reg_Block_Mat_exit38593_U0_ap_ready = SC_LOGIC_0;
    Block_Mat_exit38593_U0_ap_ready_count = "00";
    ap_sync_reg_Loop_1_proc_U0_ap_ready = SC_LOGIC_0;
    Loop_1_proc_U0_ap_ready_count = "00";
    ap_sync_reg_Block_proc_U0_ap_ready = SC_LOGIC_0;
    Block_proc_U0_ap_ready_count = "00";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "filter2D_hls_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_AWVALID, "(port)s_axi_CONTROL_BUS_AWVALID");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_AWREADY, "(port)s_axi_CONTROL_BUS_AWREADY");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_AWADDR, "(port)s_axi_CONTROL_BUS_AWADDR");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_WVALID, "(port)s_axi_CONTROL_BUS_WVALID");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_WREADY, "(port)s_axi_CONTROL_BUS_WREADY");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_WDATA, "(port)s_axi_CONTROL_BUS_WDATA");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_WSTRB, "(port)s_axi_CONTROL_BUS_WSTRB");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_ARVALID, "(port)s_axi_CONTROL_BUS_ARVALID");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_ARREADY, "(port)s_axi_CONTROL_BUS_ARREADY");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_ARADDR, "(port)s_axi_CONTROL_BUS_ARADDR");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_RVALID, "(port)s_axi_CONTROL_BUS_RVALID");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_RREADY, "(port)s_axi_CONTROL_BUS_RREADY");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_RDATA, "(port)s_axi_CONTROL_BUS_RDATA");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_RRESP, "(port)s_axi_CONTROL_BUS_RRESP");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_BVALID, "(port)s_axi_CONTROL_BUS_BVALID");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_BREADY, "(port)s_axi_CONTROL_BUS_BREADY");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_BRESP, "(port)s_axi_CONTROL_BUS_BRESP");
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, interrupt, "(port)interrupt");
    sc_trace(mVcdFile, AXI_LITE_clk, "(port)AXI_LITE_clk");
    sc_trace(mVcdFile, ap_rst_n_AXI_LITE_clk, "(port)ap_rst_n_AXI_LITE_clk");
    sc_trace(mVcdFile, in_stream_TDATA, "(port)in_stream_TDATA");
    sc_trace(mVcdFile, in_stream_TUSER, "(port)in_stream_TUSER");
    sc_trace(mVcdFile, in_stream_TLAST, "(port)in_stream_TLAST");
    sc_trace(mVcdFile, out_stream_TDATA, "(port)out_stream_TDATA");
    sc_trace(mVcdFile, out_stream_TUSER, "(port)out_stream_TUSER");
    sc_trace(mVcdFile, out_stream_TLAST, "(port)out_stream_TLAST");
    sc_trace(mVcdFile, in_stream_TVALID, "(port)in_stream_TVALID");
    sc_trace(mVcdFile, in_stream_TREADY, "(port)in_stream_TREADY");
    sc_trace(mVcdFile, out_stream_TVALID, "(port)out_stream_TVALID");
    sc_trace(mVcdFile, out_stream_TREADY, "(port)out_stream_TREADY");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, rows, "rows");
    sc_trace(mVcdFile, cols, "cols");
    sc_trace(mVcdFile, channels, "channels");
    sc_trace(mVcdFile, mode, "mode");
    sc_trace(mVcdFile, r1_V, "r1_V");
    sc_trace(mVcdFile, r2_V, "r2_V");
    sc_trace(mVcdFile, r3_V, "r3_V");
    sc_trace(mVcdFile, ap_start, "ap_start");
    sc_trace(mVcdFile, ap_ready, "ap_ready");
    sc_trace(mVcdFile, ap_done, "ap_done");
    sc_trace(mVcdFile, ap_idle, "ap_idle");
    sc_trace(mVcdFile, ap_rst_n_AXI_LITE_clk_inv, "ap_rst_n_AXI_LITE_clk_inv");
    sc_trace(mVcdFile, Block_Mat_exit38593_U0_ap_start, "Block_Mat_exit38593_U0_ap_start");
    sc_trace(mVcdFile, Block_Mat_exit38593_U0_ap_done, "Block_Mat_exit38593_U0_ap_done");
    sc_trace(mVcdFile, Block_Mat_exit38593_U0_ap_continue, "Block_Mat_exit38593_U0_ap_continue");
    sc_trace(mVcdFile, Block_Mat_exit38593_U0_ap_idle, "Block_Mat_exit38593_U0_ap_idle");
    sc_trace(mVcdFile, Block_Mat_exit38593_U0_ap_ready, "Block_Mat_exit38593_U0_ap_ready");
    sc_trace(mVcdFile, Block_Mat_exit38593_U0_start_out, "Block_Mat_exit38593_U0_start_out");
    sc_trace(mVcdFile, Block_Mat_exit38593_U0_start_write, "Block_Mat_exit38593_U0_start_write");
    sc_trace(mVcdFile, Block_Mat_exit38593_U0_col_packets_out_out_din, "Block_Mat_exit38593_U0_col_packets_out_out_din");
    sc_trace(mVcdFile, Block_Mat_exit38593_U0_col_packets_out_out_write, "Block_Mat_exit38593_U0_col_packets_out_out_write");
    sc_trace(mVcdFile, Block_Mat_exit38593_U0_col_packets_cast_out_out_din, "Block_Mat_exit38593_U0_col_packets_cast_out_out_din");
    sc_trace(mVcdFile, Block_Mat_exit38593_U0_col_packets_cast_out_out_write, "Block_Mat_exit38593_U0_col_packets_cast_out_out_write");
    sc_trace(mVcdFile, Block_Mat_exit38593_U0_ap_return, "Block_Mat_exit38593_U0_ap_return");
    sc_trace(mVcdFile, ap_channel_done_packets_loc_channel, "ap_channel_done_packets_loc_channel");
    sc_trace(mVcdFile, packets_loc_channel_full_n, "packets_loc_channel_full_n");
    sc_trace(mVcdFile, Loop_1_proc_U0_ap_start, "Loop_1_proc_U0_ap_start");
    sc_trace(mVcdFile, Loop_1_proc_U0_ap_done, "Loop_1_proc_U0_ap_done");
    sc_trace(mVcdFile, Loop_1_proc_U0_ap_continue, "Loop_1_proc_U0_ap_continue");
    sc_trace(mVcdFile, Loop_1_proc_U0_ap_idle, "Loop_1_proc_U0_ap_idle");
    sc_trace(mVcdFile, Loop_1_proc_U0_ap_ready, "Loop_1_proc_U0_ap_ready");
    sc_trace(mVcdFile, Loop_1_proc_U0_start_out, "Loop_1_proc_U0_start_out");
    sc_trace(mVcdFile, Loop_1_proc_U0_start_write, "Loop_1_proc_U0_start_write");
    sc_trace(mVcdFile, Loop_1_proc_U0_in_stream_TREADY, "Loop_1_proc_U0_in_stream_TREADY");
    sc_trace(mVcdFile, Loop_1_proc_U0_g_img_0_data_stream_0_V_din, "Loop_1_proc_U0_g_img_0_data_stream_0_V_din");
    sc_trace(mVcdFile, Loop_1_proc_U0_g_img_0_data_stream_0_V_write, "Loop_1_proc_U0_g_img_0_data_stream_0_V_write");
    sc_trace(mVcdFile, Block_proc_U0_ap_start, "Block_proc_U0_ap_start");
    sc_trace(mVcdFile, Block_proc_U0_ap_done, "Block_proc_U0_ap_done");
    sc_trace(mVcdFile, Block_proc_U0_ap_continue, "Block_proc_U0_ap_continue");
    sc_trace(mVcdFile, Block_proc_U0_ap_idle, "Block_proc_U0_ap_idle");
    sc_trace(mVcdFile, Block_proc_U0_ap_ready, "Block_proc_U0_ap_ready");
    sc_trace(mVcdFile, Block_proc_U0_kernel_val_0_V_0_out_din, "Block_proc_U0_kernel_val_0_V_0_out_din");
    sc_trace(mVcdFile, Block_proc_U0_kernel_val_0_V_0_out_write, "Block_proc_U0_kernel_val_0_V_0_out_write");
    sc_trace(mVcdFile, Block_proc_U0_kernel_val_0_V_1_out_din, "Block_proc_U0_kernel_val_0_V_1_out_din");
    sc_trace(mVcdFile, Block_proc_U0_kernel_val_0_V_1_out_write, "Block_proc_U0_kernel_val_0_V_1_out_write");
    sc_trace(mVcdFile, Block_proc_U0_kernel_val_0_V_2_out_din, "Block_proc_U0_kernel_val_0_V_2_out_din");
    sc_trace(mVcdFile, Block_proc_U0_kernel_val_0_V_2_out_write, "Block_proc_U0_kernel_val_0_V_2_out_write");
    sc_trace(mVcdFile, Block_proc_U0_kernel_val_1_V_0_out_din, "Block_proc_U0_kernel_val_1_V_0_out_din");
    sc_trace(mVcdFile, Block_proc_U0_kernel_val_1_V_0_out_write, "Block_proc_U0_kernel_val_1_V_0_out_write");
    sc_trace(mVcdFile, Block_proc_U0_kernel_val_1_V_1_out_din, "Block_proc_U0_kernel_val_1_V_1_out_din");
    sc_trace(mVcdFile, Block_proc_U0_kernel_val_1_V_1_out_write, "Block_proc_U0_kernel_val_1_V_1_out_write");
    sc_trace(mVcdFile, Block_proc_U0_kernel_val_1_V_2_out_din, "Block_proc_U0_kernel_val_1_V_2_out_din");
    sc_trace(mVcdFile, Block_proc_U0_kernel_val_1_V_2_out_write, "Block_proc_U0_kernel_val_1_V_2_out_write");
    sc_trace(mVcdFile, Block_proc_U0_kernel_val_2_V_0_out_din, "Block_proc_U0_kernel_val_2_V_0_out_din");
    sc_trace(mVcdFile, Block_proc_U0_kernel_val_2_V_0_out_write, "Block_proc_U0_kernel_val_2_V_0_out_write");
    sc_trace(mVcdFile, Block_proc_U0_kernel_val_2_V_1_out_din, "Block_proc_U0_kernel_val_2_V_1_out_din");
    sc_trace(mVcdFile, Block_proc_U0_kernel_val_2_V_1_out_write, "Block_proc_U0_kernel_val_2_V_1_out_write");
    sc_trace(mVcdFile, Block_proc_U0_kernel_val_2_V_2_out_din, "Block_proc_U0_kernel_val_2_V_2_out_din");
    sc_trace(mVcdFile, Block_proc_U0_kernel_val_2_V_2_out_write, "Block_proc_U0_kernel_val_2_V_2_out_write");
    sc_trace(mVcdFile, Filter2D_U0_ap_start, "Filter2D_U0_ap_start");
    sc_trace(mVcdFile, Filter2D_U0_ap_done, "Filter2D_U0_ap_done");
    sc_trace(mVcdFile, Filter2D_U0_ap_continue, "Filter2D_U0_ap_continue");
    sc_trace(mVcdFile, Filter2D_U0_ap_idle, "Filter2D_U0_ap_idle");
    sc_trace(mVcdFile, Filter2D_U0_ap_ready, "Filter2D_U0_ap_ready");
    sc_trace(mVcdFile, Filter2D_U0_p_src_data_stream_V_read, "Filter2D_U0_p_src_data_stream_V_read");
    sc_trace(mVcdFile, Filter2D_U0_p_dst_data_stream_V_din, "Filter2D_U0_p_dst_data_stream_V_din");
    sc_trace(mVcdFile, Filter2D_U0_p_dst_data_stream_V_write, "Filter2D_U0_p_dst_data_stream_V_write");
    sc_trace(mVcdFile, Filter2D_U0_p_kernel_val_0_V_0_read, "Filter2D_U0_p_kernel_val_0_V_0_read");
    sc_trace(mVcdFile, Filter2D_U0_p_kernel_val_0_V_1_read, "Filter2D_U0_p_kernel_val_0_V_1_read");
    sc_trace(mVcdFile, Filter2D_U0_p_kernel_val_0_V_2_read, "Filter2D_U0_p_kernel_val_0_V_2_read");
    sc_trace(mVcdFile, Filter2D_U0_p_kernel_val_1_V_0_read, "Filter2D_U0_p_kernel_val_1_V_0_read");
    sc_trace(mVcdFile, Filter2D_U0_p_kernel_val_1_V_1_read, "Filter2D_U0_p_kernel_val_1_V_1_read");
    sc_trace(mVcdFile, Filter2D_U0_p_kernel_val_1_V_2_read, "Filter2D_U0_p_kernel_val_1_V_2_read");
    sc_trace(mVcdFile, Filter2D_U0_p_kernel_val_2_V_0_read, "Filter2D_U0_p_kernel_val_2_V_0_read");
    sc_trace(mVcdFile, Filter2D_U0_p_kernel_val_2_V_1_read, "Filter2D_U0_p_kernel_val_2_V_1_read");
    sc_trace(mVcdFile, Filter2D_U0_p_kernel_val_2_V_2_read, "Filter2D_U0_p_kernel_val_2_V_2_read");
    sc_trace(mVcdFile, Loop_2_proc_U0_ap_start, "Loop_2_proc_U0_ap_start");
    sc_trace(mVcdFile, Loop_2_proc_U0_ap_done, "Loop_2_proc_U0_ap_done");
    sc_trace(mVcdFile, Loop_2_proc_U0_ap_continue, "Loop_2_proc_U0_ap_continue");
    sc_trace(mVcdFile, Loop_2_proc_U0_ap_idle, "Loop_2_proc_U0_ap_idle");
    sc_trace(mVcdFile, Loop_2_proc_U0_ap_ready, "Loop_2_proc_U0_ap_ready");
    sc_trace(mVcdFile, Loop_2_proc_U0_col_packets_loc_read, "Loop_2_proc_U0_col_packets_loc_read");
    sc_trace(mVcdFile, Loop_2_proc_U0_out_stream_TDATA, "Loop_2_proc_U0_out_stream_TDATA");
    sc_trace(mVcdFile, Loop_2_proc_U0_out_stream_TVALID, "Loop_2_proc_U0_out_stream_TVALID");
    sc_trace(mVcdFile, Loop_2_proc_U0_g_img_1_data_stream_0_V_read, "Loop_2_proc_U0_g_img_1_data_stream_0_V_read");
    sc_trace(mVcdFile, Loop_2_proc_U0_out_stream_TUSER, "Loop_2_proc_U0_out_stream_TUSER");
    sc_trace(mVcdFile, Loop_2_proc_U0_out_stream_TLAST, "Loop_2_proc_U0_out_stream_TLAST");
    sc_trace(mVcdFile, ap_sync_continue, "ap_sync_continue");
    sc_trace(mVcdFile, col_packets_loc_c_full_n, "col_packets_loc_c_full_n");
    sc_trace(mVcdFile, col_packets_loc_c_dout, "col_packets_loc_c_dout");
    sc_trace(mVcdFile, col_packets_loc_c_empty_n, "col_packets_loc_c_empty_n");
    sc_trace(mVcdFile, packets_loc_channel_dout, "packets_loc_channel_dout");
    sc_trace(mVcdFile, packets_loc_channel_empty_n, "packets_loc_channel_empty_n");
    sc_trace(mVcdFile, g_img_0_data_stream_s_full_n, "g_img_0_data_stream_s_full_n");
    sc_trace(mVcdFile, g_img_0_data_stream_s_dout, "g_img_0_data_stream_s_dout");
    sc_trace(mVcdFile, g_img_0_data_stream_s_empty_n, "g_img_0_data_stream_s_empty_n");
    sc_trace(mVcdFile, kernel_val_0_V_0_c_full_n, "kernel_val_0_V_0_c_full_n");
    sc_trace(mVcdFile, kernel_val_0_V_0_c_dout, "kernel_val_0_V_0_c_dout");
    sc_trace(mVcdFile, kernel_val_0_V_0_c_empty_n, "kernel_val_0_V_0_c_empty_n");
    sc_trace(mVcdFile, kernel_val_0_V_1_c_full_n, "kernel_val_0_V_1_c_full_n");
    sc_trace(mVcdFile, kernel_val_0_V_1_c_dout, "kernel_val_0_V_1_c_dout");
    sc_trace(mVcdFile, kernel_val_0_V_1_c_empty_n, "kernel_val_0_V_1_c_empty_n");
    sc_trace(mVcdFile, kernel_val_0_V_2_c_full_n, "kernel_val_0_V_2_c_full_n");
    sc_trace(mVcdFile, kernel_val_0_V_2_c_dout, "kernel_val_0_V_2_c_dout");
    sc_trace(mVcdFile, kernel_val_0_V_2_c_empty_n, "kernel_val_0_V_2_c_empty_n");
    sc_trace(mVcdFile, kernel_val_1_V_0_c_full_n, "kernel_val_1_V_0_c_full_n");
    sc_trace(mVcdFile, kernel_val_1_V_0_c_dout, "kernel_val_1_V_0_c_dout");
    sc_trace(mVcdFile, kernel_val_1_V_0_c_empty_n, "kernel_val_1_V_0_c_empty_n");
    sc_trace(mVcdFile, kernel_val_1_V_1_c_full_n, "kernel_val_1_V_1_c_full_n");
    sc_trace(mVcdFile, kernel_val_1_V_1_c_dout, "kernel_val_1_V_1_c_dout");
    sc_trace(mVcdFile, kernel_val_1_V_1_c_empty_n, "kernel_val_1_V_1_c_empty_n");
    sc_trace(mVcdFile, kernel_val_1_V_2_c_full_n, "kernel_val_1_V_2_c_full_n");
    sc_trace(mVcdFile, kernel_val_1_V_2_c_dout, "kernel_val_1_V_2_c_dout");
    sc_trace(mVcdFile, kernel_val_1_V_2_c_empty_n, "kernel_val_1_V_2_c_empty_n");
    sc_trace(mVcdFile, kernel_val_2_V_0_c_full_n, "kernel_val_2_V_0_c_full_n");
    sc_trace(mVcdFile, kernel_val_2_V_0_c_dout, "kernel_val_2_V_0_c_dout");
    sc_trace(mVcdFile, kernel_val_2_V_0_c_empty_n, "kernel_val_2_V_0_c_empty_n");
    sc_trace(mVcdFile, kernel_val_2_V_1_c_full_n, "kernel_val_2_V_1_c_full_n");
    sc_trace(mVcdFile, kernel_val_2_V_1_c_dout, "kernel_val_2_V_1_c_dout");
    sc_trace(mVcdFile, kernel_val_2_V_1_c_empty_n, "kernel_val_2_V_1_c_empty_n");
    sc_trace(mVcdFile, kernel_val_2_V_2_c_full_n, "kernel_val_2_V_2_c_full_n");
    sc_trace(mVcdFile, kernel_val_2_V_2_c_dout, "kernel_val_2_V_2_c_dout");
    sc_trace(mVcdFile, kernel_val_2_V_2_c_empty_n, "kernel_val_2_V_2_c_empty_n");
    sc_trace(mVcdFile, g_img_1_data_stream_s_full_n, "g_img_1_data_stream_s_full_n");
    sc_trace(mVcdFile, g_img_1_data_stream_s_dout, "g_img_1_data_stream_s_dout");
    sc_trace(mVcdFile, g_img_1_data_stream_s_empty_n, "g_img_1_data_stream_s_empty_n");
    sc_trace(mVcdFile, ap_sync_done, "ap_sync_done");
    sc_trace(mVcdFile, ap_sync_ready, "ap_sync_ready");
    sc_trace(mVcdFile, ap_sync_reg_Block_Mat_exit38593_U0_ap_ready, "ap_sync_reg_Block_Mat_exit38593_U0_ap_ready");
    sc_trace(mVcdFile, ap_sync_Block_Mat_exit38593_U0_ap_ready, "ap_sync_Block_Mat_exit38593_U0_ap_ready");
    sc_trace(mVcdFile, Block_Mat_exit38593_U0_ap_ready_count, "Block_Mat_exit38593_U0_ap_ready_count");
    sc_trace(mVcdFile, ap_sync_reg_Loop_1_proc_U0_ap_ready, "ap_sync_reg_Loop_1_proc_U0_ap_ready");
    sc_trace(mVcdFile, ap_sync_Loop_1_proc_U0_ap_ready, "ap_sync_Loop_1_proc_U0_ap_ready");
    sc_trace(mVcdFile, Loop_1_proc_U0_ap_ready_count, "Loop_1_proc_U0_ap_ready_count");
    sc_trace(mVcdFile, ap_sync_reg_Block_proc_U0_ap_ready, "ap_sync_reg_Block_proc_U0_ap_ready");
    sc_trace(mVcdFile, ap_sync_Block_proc_U0_ap_ready, "ap_sync_Block_proc_U0_ap_ready");
    sc_trace(mVcdFile, Block_proc_U0_ap_ready_count, "Block_proc_U0_ap_ready_count");
    sc_trace(mVcdFile, start_for_Loop_2_proc_U0_din, "start_for_Loop_2_proc_U0_din");
    sc_trace(mVcdFile, start_for_Loop_2_proc_U0_full_n, "start_for_Loop_2_proc_U0_full_n");
    sc_trace(mVcdFile, start_for_Loop_2_proc_U0_dout, "start_for_Loop_2_proc_U0_dout");
    sc_trace(mVcdFile, start_for_Loop_2_proc_U0_empty_n, "start_for_Loop_2_proc_U0_empty_n");
    sc_trace(mVcdFile, start_for_Filter2D_U0_din, "start_for_Filter2D_U0_din");
    sc_trace(mVcdFile, start_for_Filter2D_U0_full_n, "start_for_Filter2D_U0_full_n");
    sc_trace(mVcdFile, start_for_Filter2D_U0_dout, "start_for_Filter2D_U0_dout");
    sc_trace(mVcdFile, start_for_Filter2D_U0_empty_n, "start_for_Filter2D_U0_empty_n");
    sc_trace(mVcdFile, Block_proc_U0_start_full_n, "Block_proc_U0_start_full_n");
    sc_trace(mVcdFile, Block_proc_U0_start_write, "Block_proc_U0_start_write");
    sc_trace(mVcdFile, Filter2D_U0_start_full_n, "Filter2D_U0_start_full_n");
    sc_trace(mVcdFile, Filter2D_U0_start_write, "Filter2D_U0_start_write");
    sc_trace(mVcdFile, Loop_2_proc_U0_start_full_n, "Loop_2_proc_U0_start_full_n");
    sc_trace(mVcdFile, Loop_2_proc_U0_start_write, "Loop_2_proc_U0_start_write");
#endif

    }
    mHdltvinHandle.open("filter2D_hls.hdltvin.dat");
    mHdltvoutHandle.open("filter2D_hls.hdltvout.dat");
}

filter2D_hls::~filter2D_hls() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete filter2D_hls_CONTROL_BUS_s_axi_U;
    delete Block_Mat_exit38593_U0;
    delete Loop_1_proc_U0;
    delete Block_proc_U0;
    delete Filter2D_U0;
    delete Loop_2_proc_U0;
    delete col_packets_loc_c_U;
    delete packets_loc_channel_U;
    delete g_img_0_data_stream_s_U;
    delete kernel_val_0_V_0_c_U;
    delete kernel_val_0_V_1_c_U;
    delete kernel_val_0_V_2_c_U;
    delete kernel_val_1_V_0_c_U;
    delete kernel_val_1_V_1_c_U;
    delete kernel_val_1_V_2_c_U;
    delete kernel_val_2_V_0_c_U;
    delete kernel_val_2_V_1_c_U;
    delete kernel_val_2_V_2_c_U;
    delete g_img_1_data_stream_s_U;
    delete start_for_Loop_2_hbi_U;
    delete start_for_Filter2ibs_U;
}

void filter2D_hls::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void filter2D_hls::thread_ap_clk_no_reset_() {
    if ((esl_seteq<1,1,1>(Block_Mat_exit38593_U0_ap_ready.read(), ap_const_logic_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sync_ready.read()))) {
        Block_Mat_exit38593_U0_ap_ready_count = (!Block_Mat_exit38593_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(Block_Mat_exit38593_U0_ap_ready_count.read()) - sc_biguint<2>(ap_const_lv2_1));
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, Block_Mat_exit38593_U0_ap_ready.read()) && 
                esl_seteq<1,1,1>(ap_sync_ready.read(), ap_const_logic_0))) {
        Block_Mat_exit38593_U0_ap_ready_count = (!Block_Mat_exit38593_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(Block_Mat_exit38593_U0_ap_ready_count.read()) + sc_biguint<2>(ap_const_lv2_1));
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sync_ready.read()) && 
         esl_seteq<1,1,1>(Block_proc_U0_ap_ready.read(), ap_const_logic_0))) {
        Block_proc_U0_ap_ready_count = (!Block_proc_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(Block_proc_U0_ap_ready_count.read()) - sc_biguint<2>(ap_const_lv2_1));
    } else if ((esl_seteq<1,1,1>(ap_sync_ready.read(), ap_const_logic_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, Block_proc_U0_ap_ready.read()))) {
        Block_proc_U0_ap_ready_count = (!Block_proc_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(Block_proc_U0_ap_ready_count.read()) + sc_biguint<2>(ap_const_lv2_1));
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sync_ready.read()) && 
         esl_seteq<1,1,1>(Loop_1_proc_U0_ap_ready.read(), ap_const_logic_0))) {
        Loop_1_proc_U0_ap_ready_count = (!Loop_1_proc_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(Loop_1_proc_U0_ap_ready_count.read()) - sc_biguint<2>(ap_const_lv2_1));
    } else if ((esl_seteq<1,1,1>(ap_sync_ready.read(), ap_const_logic_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, Loop_1_proc_U0_ap_ready.read()))) {
        Loop_1_proc_U0_ap_ready_count = (!Loop_1_proc_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(Loop_1_proc_U0_ap_ready_count.read()) + sc_biguint<2>(ap_const_lv2_1));
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_Block_Mat_exit38593_U0_ap_ready = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (ap_start.read() & 
             ap_sync_ready.read()))) {
            ap_sync_reg_Block_Mat_exit38593_U0_ap_ready = ap_const_logic_0;
        } else {
            ap_sync_reg_Block_Mat_exit38593_U0_ap_ready = ap_sync_Block_Mat_exit38593_U0_ap_ready.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_Block_proc_U0_ap_ready = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (ap_start.read() & 
             ap_sync_ready.read()))) {
            ap_sync_reg_Block_proc_U0_ap_ready = ap_const_logic_0;
        } else {
            ap_sync_reg_Block_proc_U0_ap_ready = ap_sync_Block_proc_U0_ap_ready.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_Loop_1_proc_U0_ap_ready = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (ap_start.read() & 
             ap_sync_ready.read()))) {
            ap_sync_reg_Loop_1_proc_U0_ap_ready = ap_const_logic_0;
        } else {
            ap_sync_reg_Loop_1_proc_U0_ap_ready = ap_sync_Loop_1_proc_U0_ap_ready.read();
        }
    }
}

void filter2D_hls::thread_Block_Mat_exit38593_U0_ap_continue() {
    Block_Mat_exit38593_U0_ap_continue = packets_loc_channel_full_n.read();
}

void filter2D_hls::thread_Block_Mat_exit38593_U0_ap_start() {
    Block_Mat_exit38593_U0_ap_start = (ap_start.read() & (ap_sync_reg_Block_Mat_exit38593_U0_ap_ready.read() ^ 
  ap_const_logic_1));
}

void filter2D_hls::thread_Block_proc_U0_ap_continue() {
    Block_proc_U0_ap_continue = ap_const_logic_1;
}

void filter2D_hls::thread_Block_proc_U0_ap_start() {
    Block_proc_U0_ap_start = (ap_start.read() & (ap_sync_reg_Block_proc_U0_ap_ready.read() ^ 
  ap_const_logic_1));
}

void filter2D_hls::thread_Block_proc_U0_start_full_n() {
    Block_proc_U0_start_full_n = ap_const_logic_1;
}

void filter2D_hls::thread_Block_proc_U0_start_write() {
    Block_proc_U0_start_write = ap_const_logic_0;
}

void filter2D_hls::thread_Filter2D_U0_ap_continue() {
    Filter2D_U0_ap_continue = ap_const_logic_1;
}

void filter2D_hls::thread_Filter2D_U0_ap_start() {
    Filter2D_U0_ap_start = start_for_Filter2D_U0_empty_n.read();
}

void filter2D_hls::thread_Filter2D_U0_start_full_n() {
    Filter2D_U0_start_full_n = ap_const_logic_1;
}

void filter2D_hls::thread_Filter2D_U0_start_write() {
    Filter2D_U0_start_write = ap_const_logic_0;
}

void filter2D_hls::thread_Loop_1_proc_U0_ap_continue() {
    Loop_1_proc_U0_ap_continue = ap_const_logic_1;
}

void filter2D_hls::thread_Loop_1_proc_U0_ap_start() {
    Loop_1_proc_U0_ap_start = (ap_start.read() & packets_loc_channel_empty_n.read() & (ap_sync_reg_Loop_1_proc_U0_ap_ready.read() ^ 
  ap_const_logic_1));
}

void filter2D_hls::thread_Loop_2_proc_U0_ap_continue() {
    Loop_2_proc_U0_ap_continue = ap_const_logic_1;
}

void filter2D_hls::thread_Loop_2_proc_U0_ap_start() {
    Loop_2_proc_U0_ap_start = start_for_Loop_2_proc_U0_empty_n.read();
}

void filter2D_hls::thread_Loop_2_proc_U0_start_full_n() {
    Loop_2_proc_U0_start_full_n = ap_const_logic_1;
}

void filter2D_hls::thread_Loop_2_proc_U0_start_write() {
    Loop_2_proc_U0_start_write = ap_const_logic_0;
}

void filter2D_hls::thread_ap_channel_done_packets_loc_channel() {
    ap_channel_done_packets_loc_channel = Block_Mat_exit38593_U0_ap_done.read();
}

void filter2D_hls::thread_ap_done() {
    ap_done = Loop_2_proc_U0_ap_done.read();
}

void filter2D_hls::thread_ap_idle() {
    ap_idle = (Block_Mat_exit38593_U0_ap_idle.read() & Loop_1_proc_U0_ap_idle.read() & Block_proc_U0_ap_idle.read() & Filter2D_U0_ap_idle.read() & Loop_2_proc_U0_ap_idle.read() & (packets_loc_channel_empty_n.read() ^ 
  ap_const_logic_1));
}

void filter2D_hls::thread_ap_ready() {
    ap_ready = ap_sync_ready.read();
}

void filter2D_hls::thread_ap_rst_n_AXI_LITE_clk_inv() {
    ap_rst_n_AXI_LITE_clk_inv =  (sc_logic) (~ap_rst_n_AXI_LITE_clk.read());
}

void filter2D_hls::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void filter2D_hls::thread_ap_sync_Block_Mat_exit38593_U0_ap_ready() {
    ap_sync_Block_Mat_exit38593_U0_ap_ready = (Block_Mat_exit38593_U0_ap_ready.read() | ap_sync_reg_Block_Mat_exit38593_U0_ap_ready.read());
}

void filter2D_hls::thread_ap_sync_Block_proc_U0_ap_ready() {
    ap_sync_Block_proc_U0_ap_ready = (Block_proc_U0_ap_ready.read() | ap_sync_reg_Block_proc_U0_ap_ready.read());
}

void filter2D_hls::thread_ap_sync_Loop_1_proc_U0_ap_ready() {
    ap_sync_Loop_1_proc_U0_ap_ready = (Loop_1_proc_U0_ap_ready.read() | ap_sync_reg_Loop_1_proc_U0_ap_ready.read());
}

void filter2D_hls::thread_ap_sync_continue() {
    ap_sync_continue = ap_const_logic_1;
}

void filter2D_hls::thread_ap_sync_done() {
    ap_sync_done = Loop_2_proc_U0_ap_done.read();
}

void filter2D_hls::thread_ap_sync_ready() {
    ap_sync_ready = (ap_sync_Block_Mat_exit38593_U0_ap_ready.read() & ap_sync_Loop_1_proc_U0_ap_ready.read() & ap_sync_Block_proc_U0_ap_ready.read());
}

void filter2D_hls::thread_in_stream_TREADY() {
    in_stream_TREADY = Loop_1_proc_U0_in_stream_TREADY.read();
}

void filter2D_hls::thread_out_stream_TDATA() {
    out_stream_TDATA = Loop_2_proc_U0_out_stream_TDATA.read();
}

void filter2D_hls::thread_out_stream_TLAST() {
    out_stream_TLAST = Loop_2_proc_U0_out_stream_TLAST.read();
}

void filter2D_hls::thread_out_stream_TUSER() {
    out_stream_TUSER = Loop_2_proc_U0_out_stream_TUSER.read();
}

void filter2D_hls::thread_out_stream_TVALID() {
    out_stream_TVALID = Loop_2_proc_U0_out_stream_TVALID.read();
}

void filter2D_hls::thread_start_for_Filter2D_U0_din() {
    start_for_Filter2D_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void filter2D_hls::thread_start_for_Loop_2_proc_U0_din() {
    start_for_Loop_2_proc_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void filter2D_hls::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"s_axi_CONTROL_BUS_AWVALID\" :  \"" << s_axi_CONTROL_BUS_AWVALID.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"s_axi_CONTROL_BUS_AWREADY\" :  \"" << s_axi_CONTROL_BUS_AWREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_AWADDR\" :  \"" << s_axi_CONTROL_BUS_AWADDR.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_WVALID\" :  \"" << s_axi_CONTROL_BUS_WVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CONTROL_BUS_WREADY\" :  \"" << s_axi_CONTROL_BUS_WREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_WDATA\" :  \"" << s_axi_CONTROL_BUS_WDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_WSTRB\" :  \"" << s_axi_CONTROL_BUS_WSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_ARVALID\" :  \"" << s_axi_CONTROL_BUS_ARVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CONTROL_BUS_ARREADY\" :  \"" << s_axi_CONTROL_BUS_ARREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_ARADDR\" :  \"" << s_axi_CONTROL_BUS_ARADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CONTROL_BUS_RVALID\" :  \"" << s_axi_CONTROL_BUS_RVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_RREADY\" :  \"" << s_axi_CONTROL_BUS_RREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CONTROL_BUS_RDATA\" :  \"" << s_axi_CONTROL_BUS_RDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CONTROL_BUS_RRESP\" :  \"" << s_axi_CONTROL_BUS_RRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CONTROL_BUS_BVALID\" :  \"" << s_axi_CONTROL_BUS_BVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_BREADY\" :  \"" << s_axi_CONTROL_BUS_BREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CONTROL_BUS_BRESP\" :  \"" << s_axi_CONTROL_BUS_BRESP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"interrupt\" :  \"" << interrupt.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_rst_n_AXI_LITE_clk\" :  \"" << ap_rst_n_AXI_LITE_clk.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_stream_TDATA\" :  \"" << in_stream_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_stream_TUSER\" :  \"" << in_stream_TUSER.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_stream_TLAST\" :  \"" << in_stream_TLAST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_stream_TDATA\" :  \"" << out_stream_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_stream_TUSER\" :  \"" << out_stream_TUSER.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_stream_TLAST\" :  \"" << out_stream_TLAST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_stream_TVALID\" :  \"" << in_stream_TVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"in_stream_TREADY\" :  \"" << in_stream_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_stream_TVALID\" :  \"" << out_stream_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"out_stream_TREADY\" :  \"" << out_stream_TREADY.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

