// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _filter2D_hls_HH_
#define _filter2D_hls_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "Block_Mat_exit38593_s.h"
#include "Loop_1_proc.h"
#include "Block_proc.h"
#include "Filter2D.h"
#include "Loop_2_proc.h"
#include "fifo_w31_d4_A.h"
#include "fifo_w32_d2_A.h"
#include "fifo_w8_d2_A.h"
#include "fifo_w8_d3_A.h"
#include "start_for_Loop_2_hbi.h"
#include "start_for_Filter2ibs.h"
#include "filter2D_hls_CONTROL_BUS_s_axi.h"

namespace ap_rtl {

template<unsigned int C_S_AXI_CONTROL_BUS_ADDR_WIDTH = 7,
         unsigned int C_S_AXI_CONTROL_BUS_DATA_WIDTH = 32>
struct filter2D_hls : public sc_module {
    // Port declarations 32
    sc_in< sc_logic > s_axi_CONTROL_BUS_AWVALID;
    sc_out< sc_logic > s_axi_CONTROL_BUS_AWREADY;
    sc_in< sc_uint<C_S_AXI_CONTROL_BUS_ADDR_WIDTH> > s_axi_CONTROL_BUS_AWADDR;
    sc_in< sc_logic > s_axi_CONTROL_BUS_WVALID;
    sc_out< sc_logic > s_axi_CONTROL_BUS_WREADY;
    sc_in< sc_uint<C_S_AXI_CONTROL_BUS_DATA_WIDTH> > s_axi_CONTROL_BUS_WDATA;
    sc_in< sc_uint<C_S_AXI_CONTROL_BUS_DATA_WIDTH/8> > s_axi_CONTROL_BUS_WSTRB;
    sc_in< sc_logic > s_axi_CONTROL_BUS_ARVALID;
    sc_out< sc_logic > s_axi_CONTROL_BUS_ARREADY;
    sc_in< sc_uint<C_S_AXI_CONTROL_BUS_ADDR_WIDTH> > s_axi_CONTROL_BUS_ARADDR;
    sc_out< sc_logic > s_axi_CONTROL_BUS_RVALID;
    sc_in< sc_logic > s_axi_CONTROL_BUS_RREADY;
    sc_out< sc_uint<C_S_AXI_CONTROL_BUS_DATA_WIDTH> > s_axi_CONTROL_BUS_RDATA;
    sc_out< sc_lv<2> > s_axi_CONTROL_BUS_RRESP;
    sc_out< sc_logic > s_axi_CONTROL_BUS_BVALID;
    sc_in< sc_logic > s_axi_CONTROL_BUS_BREADY;
    sc_out< sc_lv<2> > s_axi_CONTROL_BUS_BRESP;
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_out< sc_logic > interrupt;
    sc_in_clk AXI_LITE_clk;
    sc_in< sc_logic > ap_rst_n_AXI_LITE_clk;
    sc_in< sc_lv<32> > in_stream_TDATA;
    sc_in< sc_lv<1> > in_stream_TUSER;
    sc_in< sc_lv<1> > in_stream_TLAST;
    sc_out< sc_lv<32> > out_stream_TDATA;
    sc_out< sc_lv<1> > out_stream_TUSER;
    sc_out< sc_lv<1> > out_stream_TLAST;
    sc_in< sc_logic > in_stream_TVALID;
    sc_out< sc_logic > in_stream_TREADY;
    sc_out< sc_logic > out_stream_TVALID;
    sc_in< sc_logic > out_stream_TREADY;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    filter2D_hls(sc_module_name name);
    SC_HAS_PROCESS(filter2D_hls);

    ~filter2D_hls();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    filter2D_hls_CONTROL_BUS_s_axi<C_S_AXI_CONTROL_BUS_ADDR_WIDTH,C_S_AXI_CONTROL_BUS_DATA_WIDTH>* filter2D_hls_CONTROL_BUS_s_axi_U;
    Block_Mat_exit38593_s* Block_Mat_exit38593_U0;
    Loop_1_proc* Loop_1_proc_U0;
    Block_proc* Block_proc_U0;
    Filter2D* Filter2D_U0;
    Loop_2_proc* Loop_2_proc_U0;
    fifo_w31_d4_A* col_packets_loc_c_U;
    fifo_w32_d2_A* packets_loc_channel_U;
    fifo_w8_d2_A* g_img_0_data_stream_s_U;
    fifo_w8_d3_A* kernel_val_0_V_0_c_U;
    fifo_w8_d3_A* kernel_val_0_V_1_c_U;
    fifo_w8_d3_A* kernel_val_0_V_2_c_U;
    fifo_w8_d3_A* kernel_val_1_V_0_c_U;
    fifo_w8_d3_A* kernel_val_1_V_1_c_U;
    fifo_w8_d3_A* kernel_val_1_V_2_c_U;
    fifo_w8_d3_A* kernel_val_2_V_0_c_U;
    fifo_w8_d3_A* kernel_val_2_V_1_c_U;
    fifo_w8_d3_A* kernel_val_2_V_2_c_U;
    fifo_w8_d2_A* g_img_1_data_stream_s_U;
    start_for_Loop_2_hbi* start_for_Loop_2_hbi_U;
    start_for_Filter2ibs* start_for_Filter2ibs_U;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_lv<32> > rows;
    sc_signal< sc_lv<32> > cols;
    sc_signal< sc_lv<32> > channels;
    sc_signal< sc_lv<32> > mode;
    sc_signal< sc_lv<32> > r1_V;
    sc_signal< sc_lv<32> > r2_V;
    sc_signal< sc_lv<32> > r3_V;
    sc_signal< sc_logic > ap_start;
    sc_signal< sc_logic > ap_ready;
    sc_signal< sc_logic > ap_done;
    sc_signal< sc_logic > ap_idle;
    sc_signal< sc_logic > ap_rst_n_AXI_LITE_clk_inv;
    sc_signal< sc_logic > Block_Mat_exit38593_U0_ap_start;
    sc_signal< sc_logic > Block_Mat_exit38593_U0_ap_done;
    sc_signal< sc_logic > Block_Mat_exit38593_U0_ap_continue;
    sc_signal< sc_logic > Block_Mat_exit38593_U0_ap_idle;
    sc_signal< sc_logic > Block_Mat_exit38593_U0_ap_ready;
    sc_signal< sc_logic > Block_Mat_exit38593_U0_start_out;
    sc_signal< sc_logic > Block_Mat_exit38593_U0_start_write;
    sc_signal< sc_lv<31> > Block_Mat_exit38593_U0_col_packets_out_out_din;
    sc_signal< sc_logic > Block_Mat_exit38593_U0_col_packets_out_out_write;
    sc_signal< sc_lv<30> > Block_Mat_exit38593_U0_col_packets_cast_out_out_din;
    sc_signal< sc_logic > Block_Mat_exit38593_U0_col_packets_cast_out_out_write;
    sc_signal< sc_lv<32> > Block_Mat_exit38593_U0_ap_return;
    sc_signal< sc_logic > ap_channel_done_packets_loc_channel;
    sc_signal< sc_logic > packets_loc_channel_full_n;
    sc_signal< sc_logic > Loop_1_proc_U0_ap_start;
    sc_signal< sc_logic > Loop_1_proc_U0_ap_done;
    sc_signal< sc_logic > Loop_1_proc_U0_ap_continue;
    sc_signal< sc_logic > Loop_1_proc_U0_ap_idle;
    sc_signal< sc_logic > Loop_1_proc_U0_ap_ready;
    sc_signal< sc_logic > Loop_1_proc_U0_start_out;
    sc_signal< sc_logic > Loop_1_proc_U0_start_write;
    sc_signal< sc_logic > Loop_1_proc_U0_in_stream_TREADY;
    sc_signal< sc_lv<8> > Loop_1_proc_U0_g_img_0_data_stream_0_V_din;
    sc_signal< sc_logic > Loop_1_proc_U0_g_img_0_data_stream_0_V_write;
    sc_signal< sc_logic > Block_proc_U0_ap_start;
    sc_signal< sc_logic > Block_proc_U0_ap_done;
    sc_signal< sc_logic > Block_proc_U0_ap_continue;
    sc_signal< sc_logic > Block_proc_U0_ap_idle;
    sc_signal< sc_logic > Block_proc_U0_ap_ready;
    sc_signal< sc_lv<8> > Block_proc_U0_kernel_val_0_V_0_out_din;
    sc_signal< sc_logic > Block_proc_U0_kernel_val_0_V_0_out_write;
    sc_signal< sc_lv<8> > Block_proc_U0_kernel_val_0_V_1_out_din;
    sc_signal< sc_logic > Block_proc_U0_kernel_val_0_V_1_out_write;
    sc_signal< sc_lv<8> > Block_proc_U0_kernel_val_0_V_2_out_din;
    sc_signal< sc_logic > Block_proc_U0_kernel_val_0_V_2_out_write;
    sc_signal< sc_lv<8> > Block_proc_U0_kernel_val_1_V_0_out_din;
    sc_signal< sc_logic > Block_proc_U0_kernel_val_1_V_0_out_write;
    sc_signal< sc_lv<8> > Block_proc_U0_kernel_val_1_V_1_out_din;
    sc_signal< sc_logic > Block_proc_U0_kernel_val_1_V_1_out_write;
    sc_signal< sc_lv<8> > Block_proc_U0_kernel_val_1_V_2_out_din;
    sc_signal< sc_logic > Block_proc_U0_kernel_val_1_V_2_out_write;
    sc_signal< sc_lv<8> > Block_proc_U0_kernel_val_2_V_0_out_din;
    sc_signal< sc_logic > Block_proc_U0_kernel_val_2_V_0_out_write;
    sc_signal< sc_lv<8> > Block_proc_U0_kernel_val_2_V_1_out_din;
    sc_signal< sc_logic > Block_proc_U0_kernel_val_2_V_1_out_write;
    sc_signal< sc_lv<8> > Block_proc_U0_kernel_val_2_V_2_out_din;
    sc_signal< sc_logic > Block_proc_U0_kernel_val_2_V_2_out_write;
    sc_signal< sc_logic > Filter2D_U0_ap_start;
    sc_signal< sc_logic > Filter2D_U0_ap_done;
    sc_signal< sc_logic > Filter2D_U0_ap_continue;
    sc_signal< sc_logic > Filter2D_U0_ap_idle;
    sc_signal< sc_logic > Filter2D_U0_ap_ready;
    sc_signal< sc_logic > Filter2D_U0_p_src_data_stream_V_read;
    sc_signal< sc_lv<8> > Filter2D_U0_p_dst_data_stream_V_din;
    sc_signal< sc_logic > Filter2D_U0_p_dst_data_stream_V_write;
    sc_signal< sc_logic > Filter2D_U0_p_kernel_val_0_V_0_read;
    sc_signal< sc_logic > Filter2D_U0_p_kernel_val_0_V_1_read;
    sc_signal< sc_logic > Filter2D_U0_p_kernel_val_0_V_2_read;
    sc_signal< sc_logic > Filter2D_U0_p_kernel_val_1_V_0_read;
    sc_signal< sc_logic > Filter2D_U0_p_kernel_val_1_V_1_read;
    sc_signal< sc_logic > Filter2D_U0_p_kernel_val_1_V_2_read;
    sc_signal< sc_logic > Filter2D_U0_p_kernel_val_2_V_0_read;
    sc_signal< sc_logic > Filter2D_U0_p_kernel_val_2_V_1_read;
    sc_signal< sc_logic > Filter2D_U0_p_kernel_val_2_V_2_read;
    sc_signal< sc_logic > Loop_2_proc_U0_ap_start;
    sc_signal< sc_logic > Loop_2_proc_U0_ap_done;
    sc_signal< sc_logic > Loop_2_proc_U0_ap_continue;
    sc_signal< sc_logic > Loop_2_proc_U0_ap_idle;
    sc_signal< sc_logic > Loop_2_proc_U0_ap_ready;
    sc_signal< sc_logic > Loop_2_proc_U0_col_packets_loc_read;
    sc_signal< sc_lv<32> > Loop_2_proc_U0_out_stream_TDATA;
    sc_signal< sc_logic > Loop_2_proc_U0_out_stream_TVALID;
    sc_signal< sc_logic > Loop_2_proc_U0_g_img_1_data_stream_0_V_read;
    sc_signal< sc_lv<1> > Loop_2_proc_U0_out_stream_TUSER;
    sc_signal< sc_lv<1> > Loop_2_proc_U0_out_stream_TLAST;
    sc_signal< sc_logic > ap_sync_continue;
    sc_signal< sc_logic > col_packets_loc_c_full_n;
    sc_signal< sc_lv<31> > col_packets_loc_c_dout;
    sc_signal< sc_logic > col_packets_loc_c_empty_n;
    sc_signal< sc_lv<32> > packets_loc_channel_dout;
    sc_signal< sc_logic > packets_loc_channel_empty_n;
    sc_signal< sc_logic > g_img_0_data_stream_s_full_n;
    sc_signal< sc_lv<8> > g_img_0_data_stream_s_dout;
    sc_signal< sc_logic > g_img_0_data_stream_s_empty_n;
    sc_signal< sc_logic > kernel_val_0_V_0_c_full_n;
    sc_signal< sc_lv<8> > kernel_val_0_V_0_c_dout;
    sc_signal< sc_logic > kernel_val_0_V_0_c_empty_n;
    sc_signal< sc_logic > kernel_val_0_V_1_c_full_n;
    sc_signal< sc_lv<8> > kernel_val_0_V_1_c_dout;
    sc_signal< sc_logic > kernel_val_0_V_1_c_empty_n;
    sc_signal< sc_logic > kernel_val_0_V_2_c_full_n;
    sc_signal< sc_lv<8> > kernel_val_0_V_2_c_dout;
    sc_signal< sc_logic > kernel_val_0_V_2_c_empty_n;
    sc_signal< sc_logic > kernel_val_1_V_0_c_full_n;
    sc_signal< sc_lv<8> > kernel_val_1_V_0_c_dout;
    sc_signal< sc_logic > kernel_val_1_V_0_c_empty_n;
    sc_signal< sc_logic > kernel_val_1_V_1_c_full_n;
    sc_signal< sc_lv<8> > kernel_val_1_V_1_c_dout;
    sc_signal< sc_logic > kernel_val_1_V_1_c_empty_n;
    sc_signal< sc_logic > kernel_val_1_V_2_c_full_n;
    sc_signal< sc_lv<8> > kernel_val_1_V_2_c_dout;
    sc_signal< sc_logic > kernel_val_1_V_2_c_empty_n;
    sc_signal< sc_logic > kernel_val_2_V_0_c_full_n;
    sc_signal< sc_lv<8> > kernel_val_2_V_0_c_dout;
    sc_signal< sc_logic > kernel_val_2_V_0_c_empty_n;
    sc_signal< sc_logic > kernel_val_2_V_1_c_full_n;
    sc_signal< sc_lv<8> > kernel_val_2_V_1_c_dout;
    sc_signal< sc_logic > kernel_val_2_V_1_c_empty_n;
    sc_signal< sc_logic > kernel_val_2_V_2_c_full_n;
    sc_signal< sc_lv<8> > kernel_val_2_V_2_c_dout;
    sc_signal< sc_logic > kernel_val_2_V_2_c_empty_n;
    sc_signal< sc_logic > g_img_1_data_stream_s_full_n;
    sc_signal< sc_lv<8> > g_img_1_data_stream_s_dout;
    sc_signal< sc_logic > g_img_1_data_stream_s_empty_n;
    sc_signal< sc_logic > ap_sync_done;
    sc_signal< sc_logic > ap_sync_ready;
    sc_signal< sc_logic > ap_sync_reg_Block_Mat_exit38593_U0_ap_ready;
    sc_signal< sc_logic > ap_sync_Block_Mat_exit38593_U0_ap_ready;
    sc_signal< sc_lv<2> > Block_Mat_exit38593_U0_ap_ready_count;
    sc_signal< sc_logic > ap_sync_reg_Loop_1_proc_U0_ap_ready;
    sc_signal< sc_logic > ap_sync_Loop_1_proc_U0_ap_ready;
    sc_signal< sc_lv<2> > Loop_1_proc_U0_ap_ready_count;
    sc_signal< sc_logic > ap_sync_reg_Block_proc_U0_ap_ready;
    sc_signal< sc_logic > ap_sync_Block_proc_U0_ap_ready;
    sc_signal< sc_lv<2> > Block_proc_U0_ap_ready_count;
    sc_signal< sc_lv<1> > start_for_Loop_2_proc_U0_din;
    sc_signal< sc_logic > start_for_Loop_2_proc_U0_full_n;
    sc_signal< sc_lv<1> > start_for_Loop_2_proc_U0_dout;
    sc_signal< sc_logic > start_for_Loop_2_proc_U0_empty_n;
    sc_signal< sc_lv<1> > start_for_Filter2D_U0_din;
    sc_signal< sc_logic > start_for_Filter2D_U0_full_n;
    sc_signal< sc_lv<1> > start_for_Filter2D_U0_dout;
    sc_signal< sc_logic > start_for_Filter2D_U0_empty_n;
    sc_signal< sc_logic > Block_proc_U0_start_full_n;
    sc_signal< sc_logic > Block_proc_U0_start_write;
    sc_signal< sc_logic > Filter2D_U0_start_full_n;
    sc_signal< sc_logic > Filter2D_U0_start_write;
    sc_signal< sc_logic > Loop_2_proc_U0_start_full_n;
    sc_signal< sc_logic > Loop_2_proc_U0_start_write;
    static const int C_S_AXI_DATA_WIDTH;
    static const int C_S_AXI_WSTRB_WIDTH;
    static const int C_S_AXI_ADDR_WIDTH;
    static const sc_logic ap_const_logic_1;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<2> ap_const_lv2_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_Block_Mat_exit38593_U0_ap_continue();
    void thread_Block_Mat_exit38593_U0_ap_start();
    void thread_Block_proc_U0_ap_continue();
    void thread_Block_proc_U0_ap_start();
    void thread_Block_proc_U0_start_full_n();
    void thread_Block_proc_U0_start_write();
    void thread_Filter2D_U0_ap_continue();
    void thread_Filter2D_U0_ap_start();
    void thread_Filter2D_U0_start_full_n();
    void thread_Filter2D_U0_start_write();
    void thread_Loop_1_proc_U0_ap_continue();
    void thread_Loop_1_proc_U0_ap_start();
    void thread_Loop_2_proc_U0_ap_continue();
    void thread_Loop_2_proc_U0_ap_start();
    void thread_Loop_2_proc_U0_start_full_n();
    void thread_Loop_2_proc_U0_start_write();
    void thread_ap_channel_done_packets_loc_channel();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_rst_n_AXI_LITE_clk_inv();
    void thread_ap_rst_n_inv();
    void thread_ap_sync_Block_Mat_exit38593_U0_ap_ready();
    void thread_ap_sync_Block_proc_U0_ap_ready();
    void thread_ap_sync_Loop_1_proc_U0_ap_ready();
    void thread_ap_sync_continue();
    void thread_ap_sync_done();
    void thread_ap_sync_ready();
    void thread_in_stream_TREADY();
    void thread_out_stream_TDATA();
    void thread_out_stream_TLAST();
    void thread_out_stream_TUSER();
    void thread_out_stream_TVALID();
    void thread_start_for_Filter2D_U0_din();
    void thread_start_for_Loop_2_proc_U0_din();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
