// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="calcola,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.510000,HLS_SYN_LAT=8,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=3,HLS_SYN_FF=722,HLS_SYN_LUT=857,HLS_VERSION=2018_3}" *)

module calcola (
        ap_clk,
        ap_rst_n,
        s_axi_AXILiteS_AWVALID,
        s_axi_AXILiteS_AWREADY,
        s_axi_AXILiteS_AWADDR,
        s_axi_AXILiteS_WVALID,
        s_axi_AXILiteS_WREADY,
        s_axi_AXILiteS_WDATA,
        s_axi_AXILiteS_WSTRB,
        s_axi_AXILiteS_ARVALID,
        s_axi_AXILiteS_ARREADY,
        s_axi_AXILiteS_ARADDR,
        s_axi_AXILiteS_RVALID,
        s_axi_AXILiteS_RREADY,
        s_axi_AXILiteS_RDATA,
        s_axi_AXILiteS_RRESP,
        s_axi_AXILiteS_BVALID,
        s_axi_AXILiteS_BREADY,
        s_axi_AXILiteS_BRESP
);

parameter    ap_ST_fsm_state1 = 38'd1;
parameter    ap_ST_fsm_state2 = 38'd2;
parameter    ap_ST_fsm_state3 = 38'd4;
parameter    ap_ST_fsm_state4 = 38'd8;
parameter    ap_ST_fsm_state5 = 38'd16;
parameter    ap_ST_fsm_state6 = 38'd32;
parameter    ap_ST_fsm_state7 = 38'd64;
parameter    ap_ST_fsm_state8 = 38'd128;
parameter    ap_ST_fsm_state9 = 38'd256;
parameter    ap_ST_fsm_state10 = 38'd512;
parameter    ap_ST_fsm_state11 = 38'd1024;
parameter    ap_ST_fsm_state12 = 38'd2048;
parameter    ap_ST_fsm_state13 = 38'd4096;
parameter    ap_ST_fsm_state14 = 38'd8192;
parameter    ap_ST_fsm_state15 = 38'd16384;
parameter    ap_ST_fsm_state16 = 38'd32768;
parameter    ap_ST_fsm_state17 = 38'd65536;
parameter    ap_ST_fsm_state18 = 38'd131072;
parameter    ap_ST_fsm_state19 = 38'd262144;
parameter    ap_ST_fsm_state20 = 38'd524288;
parameter    ap_ST_fsm_state21 = 38'd1048576;
parameter    ap_ST_fsm_state22 = 38'd2097152;
parameter    ap_ST_fsm_state23 = 38'd4194304;
parameter    ap_ST_fsm_state24 = 38'd8388608;
parameter    ap_ST_fsm_state25 = 38'd16777216;
parameter    ap_ST_fsm_state26 = 38'd33554432;
parameter    ap_ST_fsm_state27 = 38'd67108864;
parameter    ap_ST_fsm_state28 = 38'd134217728;
parameter    ap_ST_fsm_state29 = 38'd268435456;
parameter    ap_ST_fsm_state30 = 38'd536870912;
parameter    ap_ST_fsm_state31 = 38'd1073741824;
parameter    ap_ST_fsm_state32 = 38'd2147483648;
parameter    ap_ST_fsm_state33 = 38'd4294967296;
parameter    ap_ST_fsm_state34 = 38'd8589934592;
parameter    ap_ST_fsm_state35 = 38'd17179869184;
parameter    ap_ST_fsm_state36 = 38'd34359738368;
parameter    ap_ST_fsm_state37 = 38'd68719476736;
parameter    ap_ST_fsm_state38 = 38'd137438953472;
parameter    C_S_AXI_AXILITES_DATA_WIDTH = 32;
parameter    C_S_AXI_AXILITES_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_AXILITES_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   s_axi_AXILiteS_AWVALID;
output   s_axi_AXILiteS_AWREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1:0] s_axi_AXILiteS_AWADDR;
input   s_axi_AXILiteS_WVALID;
output   s_axi_AXILiteS_WREADY;
input  [C_S_AXI_AXILITES_DATA_WIDTH - 1:0] s_axi_AXILiteS_WDATA;
input  [C_S_AXI_AXILITES_WSTRB_WIDTH - 1:0] s_axi_AXILiteS_WSTRB;
input   s_axi_AXILiteS_ARVALID;
output   s_axi_AXILiteS_ARREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1:0] s_axi_AXILiteS_ARADDR;
output   s_axi_AXILiteS_RVALID;
input   s_axi_AXILiteS_RREADY;
output  [C_S_AXI_AXILITES_DATA_WIDTH - 1:0] s_axi_AXILiteS_RDATA;
output  [1:0] s_axi_AXILiteS_RRESP;
output   s_axi_AXILiteS_BVALID;
input   s_axi_AXILiteS_BREADY;
output  [1:0] s_axi_AXILiteS_BRESP;

 reg    ap_rst_n_inv;
wire  signed [31:0] a;
wire  signed [31:0] b;
wire   [7:0] o;
reg    c_ap_vld;
reg  signed [31:0] b_read_reg_140;
(* fsm_encoding = "none" *) reg   [37:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg  signed [31:0] a_read_reg_146;
wire   [0:0] tmp_1_fu_81_p2;
reg   [0:0] tmp_1_reg_152;
wire   [0:0] tmp_3_fu_87_p2;
reg   [0:0] tmp_3_reg_156;
wire   [0:0] tmp_5_fu_93_p2;
reg   [0:0] tmp_5_reg_160;
wire   [0:0] or_cond_fu_111_p2;
reg   [0:0] or_cond_reg_164;
wire   [31:0] tmp_4_fu_124_p2;
wire   [31:0] tmp_2_fu_130_p2;
wire   [31:0] tmp_6_fu_136_p2;
reg   [31:0] tmp_6_reg_178;
wire    ap_CS_fsm_state37;
reg   [31:0] ap_phi_mux_storemerge4_phi_fu_67_p10;
reg   [31:0] storemerge4_reg_63;
wire    ap_CS_fsm_state38;
wire   [31:0] grp_fu_117_p2;
wire    ap_CS_fsm_state36;
wire  signed [31:0] tmp_8_fu_105_p0;
wire   [0:0] tmp_7_fu_99_p2;
wire   [0:0] tmp_8_fu_105_p2;
wire  signed [31:0] tmp_4_fu_124_p0;
wire  signed [31:0] tmp_4_fu_124_p1;
wire  signed [31:0] tmp_2_fu_130_p0;
wire  signed [31:0] tmp_2_fu_130_p1;
reg    grp_fu_117_ap_start;
wire    grp_fu_117_ap_done;
reg   [37:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 38'd1;
end

calcola_AXILiteS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_AXILITES_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_AXILITES_DATA_WIDTH ))
calcola_AXILiteS_s_axi_U(
    .AWVALID(s_axi_AXILiteS_AWVALID),
    .AWREADY(s_axi_AXILiteS_AWREADY),
    .AWADDR(s_axi_AXILiteS_AWADDR),
    .WVALID(s_axi_AXILiteS_WVALID),
    .WREADY(s_axi_AXILiteS_WREADY),
    .WDATA(s_axi_AXILiteS_WDATA),
    .WSTRB(s_axi_AXILiteS_WSTRB),
    .ARVALID(s_axi_AXILiteS_ARVALID),
    .ARREADY(s_axi_AXILiteS_ARREADY),
    .ARADDR(s_axi_AXILiteS_ARADDR),
    .RVALID(s_axi_AXILiteS_RVALID),
    .RREADY(s_axi_AXILiteS_RREADY),
    .RDATA(s_axi_AXILiteS_RDATA),
    .RRESP(s_axi_AXILiteS_RRESP),
    .BVALID(s_axi_AXILiteS_BVALID),
    .BREADY(s_axi_AXILiteS_BREADY),
    .BRESP(s_axi_AXILiteS_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .a(a),
    .b(b),
    .o(o),
    .c(ap_phi_mux_storemerge4_phi_fu_67_p10),
    .c_ap_vld(c_ap_vld)
);

calcola_sdiv_32s_bkb #(
    .ID( 1 ),
    .NUM_STAGE( 36 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
calcola_sdiv_32s_bkb_U1(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .start(grp_fu_117_ap_start),
    .done(grp_fu_117_ap_done),
    .din0(a),
    .din1(b),
    .ce(1'b1),
    .dout(grp_fu_117_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_fu_81_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (or_cond_fu_111_p2 == 1'd0) & (tmp_5_fu_93_p2 == 1'd0) & (tmp_3_fu_87_p2 == 1'd0))) begin
        storemerge4_reg_63 <= 32'd0;
    end else if (((tmp_1_reg_152 == 1'd0) & (1'b1 == ap_CS_fsm_state36) & (or_cond_reg_164 == 1'd1) & (tmp_5_reg_160 == 1'd0) & (tmp_3_reg_156 == 1'd0))) begin
        storemerge4_reg_63 <= grp_fu_117_p2;
    end else if ((1'b1 == ap_CS_fsm_state38)) begin
        storemerge4_reg_63 <= tmp_6_reg_178;
    end else if (((tmp_1_fu_81_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (tmp_3_fu_87_p2 == 1'd1))) begin
        storemerge4_reg_63 <= tmp_4_fu_124_p2;
    end else if (((tmp_1_fu_81_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        storemerge4_reg_63 <= tmp_2_fu_130_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        a_read_reg_146 <= a;
        b_read_reg_140 <= b;
        tmp_1_reg_152 <= tmp_1_fu_81_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_fu_81_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (tmp_5_fu_93_p2 == 1'd0) & (tmp_3_fu_87_p2 == 1'd0))) begin
        or_cond_reg_164 <= or_cond_fu_111_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_fu_81_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        tmp_3_reg_156 <= tmp_3_fu_87_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_fu_81_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (tmp_3_fu_87_p2 == 1'd0))) begin
        tmp_5_reg_160 <= tmp_5_fu_93_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        tmp_6_reg_178 <= tmp_6_fu_136_p2;
    end
end

always @ (*) begin
    if (((tmp_1_reg_152 == 1'd0) & (1'b1 == ap_CS_fsm_state36) & (or_cond_reg_164 == 1'd1) & (tmp_5_reg_160 == 1'd0) & (tmp_3_reg_156 == 1'd0))) begin
        ap_phi_mux_storemerge4_phi_fu_67_p10 = grp_fu_117_p2;
    end else begin
        ap_phi_mux_storemerge4_phi_fu_67_p10 = storemerge4_reg_63;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state36)) begin
        c_ap_vld = 1'b1;
    end else begin
        c_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_1_fu_81_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (or_cond_fu_111_p2 == 1'd1) & (tmp_5_fu_93_p2 == 1'd0) & (tmp_3_fu_87_p2 == 1'd0))) begin
        grp_fu_117_ap_start = 1'b1;
    end else begin
        grp_fu_117_ap_start = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & ((tmp_1_fu_81_p2 == 1'd1) | ((tmp_3_fu_87_p2 == 1'd1) | ((or_cond_fu_111_p2 == 1'd0) & (tmp_5_fu_93_p2 == 1'd0)))))) begin
                ap_NS_fsm = ap_ST_fsm_state36;
            end else if (((tmp_1_fu_81_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (or_cond_fu_111_p2 == 1'd1) & (tmp_5_fu_93_p2 == 1'd0) & (tmp_3_fu_87_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state37;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state36 = ap_CS_fsm[32'd35];

assign ap_CS_fsm_state37 = ap_CS_fsm[32'd36];

assign ap_CS_fsm_state38 = ap_CS_fsm[32'd37];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign or_cond_fu_111_p2 = (tmp_8_fu_105_p2 & tmp_7_fu_99_p2);

assign tmp_1_fu_81_p2 = ((o == 8'd43) ? 1'b1 : 1'b0);

assign tmp_2_fu_130_p0 = b;

assign tmp_2_fu_130_p1 = a;

assign tmp_2_fu_130_p2 = ($signed(tmp_2_fu_130_p0) + $signed(tmp_2_fu_130_p1));

assign tmp_3_fu_87_p2 = ((o == 8'd45) ? 1'b1 : 1'b0);

assign tmp_4_fu_124_p0 = a;

assign tmp_4_fu_124_p1 = b;

assign tmp_4_fu_124_p2 = ($signed(tmp_4_fu_124_p0) - $signed(tmp_4_fu_124_p1));

assign tmp_5_fu_93_p2 = ((o == 8'd42) ? 1'b1 : 1'b0);

assign tmp_6_fu_136_p2 = ($signed(b_read_reg_140) * $signed(a_read_reg_146));

assign tmp_7_fu_99_p2 = ((o == 8'd47) ? 1'b1 : 1'b0);

assign tmp_8_fu_105_p0 = b;

assign tmp_8_fu_105_p2 = (($signed(tmp_8_fu_105_p0) > $signed(32'd0)) ? 1'b1 : 1'b0);

endmodule //calcola
