// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Block_Mat_exit38593_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        channels,
        cols,
        rows,
        col_packets_out_out_din,
        col_packets_out_out_full_n,
        col_packets_out_out_write,
        col_packets_cast_out_out_din,
        col_packets_cast_out_out_full_n,
        col_packets_cast_out_out_write,
        ap_return
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [31:0] channels;
input  [31:0] cols;
input  [31:0] rows;
output  [30:0] col_packets_out_out_din;
input   col_packets_out_out_full_n;
output   col_packets_out_out_write;
output  [29:0] col_packets_cast_out_out_din;
input   col_packets_cast_out_out_full_n;
output   col_packets_cast_out_out_write;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg start_write;
reg col_packets_out_out_write;
reg col_packets_cast_out_out_write;
reg[31:0] ap_return;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    col_packets_out_out_blk_n;
wire    ap_CS_fsm_state3;
reg    col_packets_cast_out_out_blk_n;
wire   [31:0] tmp_i_fu_90_p2;
reg    ap_block_state1;
wire   [0:0] tmp_36_fu_96_p3;
wire   [29:0] tmp_s_fu_104_p4;
wire  signed [30:0] col_packets_fu_142_p3;
reg    ap_block_state3;
wire  signed [31:0] tmp_i_fu_90_p0;
wire  signed [31:0] tmp_i_fu_90_p1;
wire   [31:0] p_neg_i_fu_114_p2;
wire   [29:0] tmp_fu_119_p4;
wire   [30:0] p_lshr_cast_i_fu_129_p1;
wire   [30:0] p_neg_t_i_fu_133_p2;
wire   [30:0] p_lshr_f_cast_i_fu_139_p1;
wire  signed [31:0] packets_fu_156_p0;
wire  signed [30:0] packets_fu_156_p1;
wire   [31:0] packets_fu_156_p2;
reg   [31:0] ap_return_preg;
reg   [2:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 ap_return_preg = 32'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((col_packets_cast_out_out_full_n == 1'b0) | (col_packets_out_out_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 32'd0;
    end else begin
        if ((~((col_packets_cast_out_out_full_n == 1'b0) | (col_packets_out_out_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_return_preg <= packets_fu_156_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((~((col_packets_cast_out_out_full_n == 1'b0) | (col_packets_out_out_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((col_packets_cast_out_out_full_n == 1'b0) | (col_packets_out_out_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_return = packets_fu_156_p2;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        col_packets_cast_out_out_blk_n = col_packets_cast_out_out_full_n;
    end else begin
        col_packets_cast_out_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((col_packets_cast_out_out_full_n == 1'b0) | (col_packets_out_out_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3))) begin
        col_packets_cast_out_out_write = 1'b1;
    end else begin
        col_packets_cast_out_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        col_packets_out_out_blk_n = col_packets_out_out_full_n;
    end else begin
        col_packets_out_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((col_packets_cast_out_out_full_n == 1'b0) | (col_packets_out_out_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3))) begin
        col_packets_out_out_write = 1'b1;
    end else begin
        col_packets_out_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((col_packets_cast_out_out_full_n == 1'b0) | (col_packets_out_out_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if ((~((col_packets_cast_out_out_full_n == 1'b0) | (col_packets_out_out_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state3 = ((col_packets_cast_out_out_full_n == 1'b0) | (col_packets_out_out_full_n == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign col_packets_cast_out_out_din = col_packets_fu_142_p3[29:0];

assign col_packets_fu_142_p3 = ((tmp_36_fu_96_p3[0:0] === 1'b1) ? p_neg_t_i_fu_133_p2 : p_lshr_f_cast_i_fu_139_p1);

assign col_packets_out_out_din = col_packets_fu_142_p3;

assign p_lshr_cast_i_fu_129_p1 = tmp_fu_119_p4;

assign p_lshr_f_cast_i_fu_139_p1 = tmp_s_fu_104_p4;

assign p_neg_i_fu_114_p2 = (32'd0 - tmp_i_fu_90_p2);

assign p_neg_t_i_fu_133_p2 = (31'd0 - p_lshr_cast_i_fu_129_p1);

assign packets_fu_156_p0 = rows;

assign packets_fu_156_p1 = col_packets_fu_142_p3;

assign packets_fu_156_p2 = ($signed(packets_fu_156_p0) * $signed(packets_fu_156_p1));

assign start_out = real_start;

assign tmp_36_fu_96_p3 = tmp_i_fu_90_p2[32'd31];

assign tmp_fu_119_p4 = {{p_neg_i_fu_114_p2[31:2]}};

assign tmp_i_fu_90_p0 = channels;

assign tmp_i_fu_90_p1 = cols;

assign tmp_i_fu_90_p2 = ($signed(tmp_i_fu_90_p0) * $signed(tmp_i_fu_90_p1));

assign tmp_s_fu_104_p4 = {{tmp_i_fu_90_p2[31:2]}};

endmodule //Block_Mat_exit38593_s
