// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Filter2D (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_src_rows_V,
        p_src_cols_V,
        p_src_data_stream_V_dout,
        p_src_data_stream_V_empty_n,
        p_src_data_stream_V_read,
        p_dst_data_stream_V_din,
        p_dst_data_stream_V_full_n,
        p_dst_data_stream_V_write,
        p_kernel_val_0_V_0_dout,
        p_kernel_val_0_V_0_empty_n,
        p_kernel_val_0_V_0_read,
        p_kernel_val_0_V_1_dout,
        p_kernel_val_0_V_1_empty_n,
        p_kernel_val_0_V_1_read,
        p_kernel_val_0_V_2_dout,
        p_kernel_val_0_V_2_empty_n,
        p_kernel_val_0_V_2_read,
        p_kernel_val_1_V_0_dout,
        p_kernel_val_1_V_0_empty_n,
        p_kernel_val_1_V_0_read,
        p_kernel_val_1_V_1_dout,
        p_kernel_val_1_V_1_empty_n,
        p_kernel_val_1_V_1_read,
        p_kernel_val_1_V_2_dout,
        p_kernel_val_1_V_2_empty_n,
        p_kernel_val_1_V_2_read,
        p_kernel_val_2_V_0_dout,
        p_kernel_val_2_V_0_empty_n,
        p_kernel_val_2_V_0_read,
        p_kernel_val_2_V_1_dout,
        p_kernel_val_2_V_1_empty_n,
        p_kernel_val_2_V_1_read,
        p_kernel_val_2_V_2_dout,
        p_kernel_val_2_V_2_empty_n,
        p_kernel_val_2_V_2_read
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_pp0_stage0 = 5'd8;
parameter    ap_ST_fsm_state10 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] p_src_rows_V;
input  [31:0] p_src_cols_V;
input  [7:0] p_src_data_stream_V_dout;
input   p_src_data_stream_V_empty_n;
output   p_src_data_stream_V_read;
output  [7:0] p_dst_data_stream_V_din;
input   p_dst_data_stream_V_full_n;
output   p_dst_data_stream_V_write;
input  [7:0] p_kernel_val_0_V_0_dout;
input   p_kernel_val_0_V_0_empty_n;
output   p_kernel_val_0_V_0_read;
input  [7:0] p_kernel_val_0_V_1_dout;
input   p_kernel_val_0_V_1_empty_n;
output   p_kernel_val_0_V_1_read;
input  [7:0] p_kernel_val_0_V_2_dout;
input   p_kernel_val_0_V_2_empty_n;
output   p_kernel_val_0_V_2_read;
input  [7:0] p_kernel_val_1_V_0_dout;
input   p_kernel_val_1_V_0_empty_n;
output   p_kernel_val_1_V_0_read;
input  [7:0] p_kernel_val_1_V_1_dout;
input   p_kernel_val_1_V_1_empty_n;
output   p_kernel_val_1_V_1_read;
input  [7:0] p_kernel_val_1_V_2_dout;
input   p_kernel_val_1_V_2_empty_n;
output   p_kernel_val_1_V_2_read;
input  [7:0] p_kernel_val_2_V_0_dout;
input   p_kernel_val_2_V_0_empty_n;
output   p_kernel_val_2_V_0_read;
input  [7:0] p_kernel_val_2_V_1_dout;
input   p_kernel_val_2_V_1_empty_n;
output   p_kernel_val_2_V_1_read;
input  [7:0] p_kernel_val_2_V_2_dout;
input   p_kernel_val_2_V_2_empty_n;
output   p_kernel_val_2_V_2_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_src_data_stream_V_read;
reg p_dst_data_stream_V_write;
reg p_kernel_val_0_V_0_read;
reg p_kernel_val_0_V_1_read;
reg p_kernel_val_0_V_2_read;
reg p_kernel_val_1_V_0_read;
reg p_kernel_val_1_V_1_read;
reg p_kernel_val_1_V_2_read;
reg p_kernel_val_2_V_0_read;
reg p_kernel_val_2_V_1_read;
reg p_kernel_val_2_V_2_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    p_src_data_stream_V_blk_n;
reg    ap_enable_reg_pp0_iter2;
wire    ap_block_pp0_stage0;
reg   [0:0] exitcond460_i_i_reg_1717;
reg   [0:0] exitcond460_i_i_reg_1717_pp0_iter1_reg;
reg   [0:0] or_cond_i_i_i_reg_1726;
reg   [0:0] or_cond_i_i_i_reg_1726_pp0_iter1_reg;
reg   [0:0] icmp_reg_1662;
reg   [0:0] tmp_2_i_reg_1657;
reg    p_dst_data_stream_V_blk_n;
reg    ap_enable_reg_pp0_iter5;
reg   [0:0] or_cond_i_i_reg_1743;
reg   [0:0] or_cond_i_i_reg_1743_pp0_iter4_reg;
reg    p_kernel_val_0_V_0_blk_n;
reg    p_kernel_val_0_V_1_blk_n;
reg    p_kernel_val_0_V_2_blk_n;
reg    p_kernel_val_1_V_0_blk_n;
reg    p_kernel_val_1_V_1_blk_n;
reg    p_kernel_val_1_V_2_blk_n;
reg    p_kernel_val_2_V_0_blk_n;
reg    p_kernel_val_2_V_1_blk_n;
reg    p_kernel_val_2_V_2_blk_n;
reg   [31:0] t_V_1_reg_459;
reg    ap_block_state1;
wire   [31:0] tmp_i_fu_470_p2;
wire   [31:0] tmp_1_i_fu_476_p2;
wire   [31:0] p_neg465_i_i_fu_482_p2;
wire   [31:0] tmp_11_i_fu_488_p2;
wire   [31:0] tmp_133_i_fu_500_p2;
wire  signed [15:0] tmp_137_0_i_fu_506_p1;
reg  signed [15:0] tmp_137_0_i_reg_1599;
wire  signed [15:0] tmp_137_0_1_i_fu_510_p1;
reg  signed [15:0] tmp_137_0_1_i_reg_1604;
wire  signed [15:0] tmp_137_0_2_i_fu_514_p1;
reg  signed [15:0] tmp_137_0_2_i_reg_1609;
wire  signed [15:0] tmp_137_1_i_fu_518_p1;
reg  signed [15:0] tmp_137_1_i_reg_1614;
wire  signed [15:0] tmp_137_1_1_i_fu_522_p1;
reg  signed [15:0] tmp_137_1_1_i_reg_1619;
wire  signed [15:0] tmp_137_1_2_i_fu_526_p1;
reg  signed [15:0] tmp_137_1_2_i_reg_1624;
wire  signed [15:0] tmp_137_2_i_fu_530_p1;
reg  signed [15:0] tmp_137_2_i_reg_1629;
wire  signed [15:0] tmp_137_2_1_i_fu_534_p1;
reg  signed [15:0] tmp_137_2_1_i_reg_1634;
wire  signed [15:0] tmp_137_2_2_i_fu_538_p1;
reg  signed [15:0] tmp_137_2_2_i_reg_1639;
wire   [31:0] tmp_10_i_fu_548_p2;
wire   [31:0] i_V_fu_559_p2;
reg   [31:0] i_V_reg_1652;
wire    ap_CS_fsm_state2;
wire   [0:0] tmp_2_i_fu_565_p2;
wire   [0:0] exitcond461_i_i_fu_554_p2;
wire   [0:0] icmp_fu_580_p2;
wire   [0:0] tmp_93_i_fu_586_p2;
reg   [0:0] tmp_93_i_reg_1667;
wire   [0:0] tmp_93_1_i_fu_592_p2;
reg   [0:0] tmp_93_1_i_reg_1671;
wire   [0:0] tmp_115_i_fu_598_p2;
reg   [0:0] tmp_115_i_reg_1675;
wire   [31:0] y_i_fu_800_p3;
reg   [31:0] y_i_reg_1682;
wire   [31:0] y_1_i_fu_816_p3;
reg   [31:0] y_1_i_reg_1687;
wire   [31:0] y_2_i_fu_832_p3;
reg   [31:0] y_2_i_reg_1692;
wire   [0:0] tmp_48_0_not_i_fu_840_p2;
reg   [0:0] tmp_48_0_not_i_reg_1697;
wire    ap_CS_fsm_state3;
wire   [1:0] tmp_20_fu_849_p1;
reg   [1:0] tmp_20_reg_1702;
wire   [1:0] tmp_21_fu_857_p1;
reg   [1:0] tmp_21_reg_1707;
wire   [1:0] tmp_22_fu_865_p1;
reg   [1:0] tmp_22_reg_1712;
wire   [0:0] exitcond460_i_i_fu_869_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state4_pp0_stage0_iter0;
wire    ap_block_state5_pp0_stage0_iter1;
reg    ap_predicate_op190_read_state6;
reg    ap_predicate_op201_read_state6;
reg    ap_block_state6_pp0_stage0_iter2;
wire    ap_block_state7_pp0_stage0_iter3;
wire    ap_block_state8_pp0_stage0_iter4;
reg    ap_block_state9_pp0_stage0_iter5;
reg    ap_block_pp0_stage0_11001;
wire   [31:0] j_V_fu_874_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] or_cond_i_i_i_fu_921_p2;
wire   [31:0] x_fu_985_p3;
reg   [31:0] x_reg_1730;
wire   [0:0] brmerge_i_fu_993_p2;
reg   [0:0] brmerge_i_reg_1736;
reg   [0:0] brmerge_i_reg_1736_pp0_iter1_reg;
wire   [0:0] or_cond_i_i_fu_998_p2;
reg   [0:0] or_cond_i_i_reg_1743_pp0_iter1_reg;
reg   [0:0] or_cond_i_i_reg_1743_pp0_iter2_reg;
reg   [0:0] or_cond_i_i_reg_1743_pp0_iter3_reg;
reg   [10:0] k_buf_0_val_3_addr_reg_1747;
wire   [1:0] tmp_26_fu_1013_p1;
reg   [1:0] tmp_26_reg_1753;
reg   [10:0] k_buf_0_val_4_addr_reg_1760;
reg   [10:0] k_buf_0_val_5_addr_reg_1766;
wire   [7:0] src_kernel_win_0_va_6_fu_1136_p3;
reg   [7:0] src_kernel_win_0_va_6_reg_1772;
reg   [7:0] src_kernel_win_0_va_6_reg_1772_pp0_iter3_reg;
wire   [7:0] src_kernel_win_0_va_7_fu_1154_p3;
reg   [7:0] src_kernel_win_0_va_7_reg_1777;
wire   [7:0] src_kernel_win_0_va_8_fu_1172_p3;
reg   [7:0] src_kernel_win_0_va_8_reg_1782;
reg   [7:0] src_kernel_win_0_va_10_reg_1787;
wire  signed [16:0] grp_fu_1444_p3;
reg  signed [16:0] sum_V_0_1_i_reg_1792;
wire   [15:0] r_V_2_1_i_fu_1218_p2;
reg  signed [15:0] r_V_2_1_i_reg_1798;
wire  signed [16:0] grp_fu_1451_p3;
reg  signed [16:0] tmp13_reg_1803;
wire   [17:0] sum_V_1_i_fu_1295_p2;
reg   [17:0] sum_V_1_i_reg_1808;
wire  signed [15:0] r_V_2_1_2_i_fu_1304_p2;
reg  signed [15:0] r_V_2_1_2_i_reg_1813;
wire  signed [17:0] grp_fu_1467_p3;
reg  signed [17:0] tmp14_reg_1818;
reg    ap_enable_reg_pp0_iter3;
wire   [7:0] tmp_1_fu_1323_p2;
reg   [7:0] tmp_1_reg_1823;
wire   [7:0] tmp_31_fu_1329_p1;
reg   [7:0] tmp_31_reg_1828;
reg   [0:0] p_Result_s_reg_1833;
wire   [7:0] p_Val2_1_fu_1391_p2;
reg   [7:0] p_Val2_1_reg_1839;
wire   [0:0] not_i_i_i_fu_1407_p2;
reg   [0:0] not_i_i_i_reg_1844;
reg    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter1;
reg    ap_condition_pp0_exit_iter2_state6;
reg    ap_enable_reg_pp0_iter4;
wire   [10:0] k_buf_0_val_3_address0;
reg    k_buf_0_val_3_ce0;
wire   [7:0] k_buf_0_val_3_q0;
wire   [10:0] k_buf_0_val_3_address1;
reg    k_buf_0_val_3_ce1;
reg    k_buf_0_val_3_we1;
wire   [10:0] k_buf_0_val_4_address0;
reg    k_buf_0_val_4_ce0;
wire   [7:0] k_buf_0_val_4_q0;
wire   [10:0] k_buf_0_val_4_address1;
reg    k_buf_0_val_4_ce1;
reg    k_buf_0_val_4_we1;
reg   [7:0] k_buf_0_val_4_d1;
wire   [10:0] k_buf_0_val_5_address0;
reg    k_buf_0_val_5_ce0;
wire   [7:0] k_buf_0_val_5_q0;
wire   [10:0] k_buf_0_val_5_address1;
reg    k_buf_0_val_5_ce1;
reg    k_buf_0_val_5_we1;
reg   [7:0] k_buf_0_val_5_d1;
reg   [31:0] t_V_reg_448;
wire    ap_CS_fsm_state10;
wire   [63:0] tmp_58_i_fu_1007_p1;
reg    ap_block_pp0_stage0_01001;
reg   [7:0] src_kernel_win_0_va_fu_256;
reg   [7:0] src_kernel_win_0_va_1_fu_260;
reg   [7:0] src_kernel_win_0_va_2_fu_264;
reg   [7:0] src_kernel_win_0_va_3_fu_268;
reg   [7:0] src_kernel_win_0_va_4_fu_272;
reg   [7:0] src_kernel_win_0_va_5_fu_276;
reg   [7:0] right_border_buf_0_s_fu_280;
wire   [7:0] col_buf_0_val_0_0_fu_1046_p3;
reg   [7:0] right_border_buf_0_1_fu_284;
reg   [7:0] right_border_buf_0_2_fu_288;
reg   [7:0] right_border_buf_0_3_fu_292;
wire   [7:0] col_buf_0_val_1_0_fu_1064_p3;
reg   [7:0] right_border_buf_0_4_fu_296;
reg   [7:0] right_border_buf_0_5_fu_300;
wire   [7:0] col_buf_0_val_2_0_fu_1082_p3;
wire   [31:0] tmp_fu_494_p2;
wire   [31:0] tmp_9_fu_542_p2;
wire   [30:0] tmp_11_fu_570_p4;
wire   [31:0] tmp_118_i_fu_603_p2;
wire   [0:0] tmp_12_fu_609_p3;
wire   [0:0] tmp_120_i_fu_623_p2;
wire   [0:0] rev_fu_617_p2;
wire   [0:0] tmp_13_fu_634_p3;
wire   [31:0] p_assign_7_i_fu_642_p2;
wire   [31:0] p_p2_i497_i_i_fu_648_p3;
wire   [31:0] p_assign_6_1_i_fu_666_p2;
wire   [0:0] tmp_16_fu_672_p3;
wire   [0:0] tmp_120_1_i_fu_686_p2;
wire   [0:0] rev1_fu_680_p2;
wire   [0:0] tmp_17_fu_697_p3;
wire   [31:0] p_assign_7_1_i_fu_705_p2;
wire   [31:0] p_p2_i497_i_1_i_fu_711_p3;
wire   [31:0] p_assign_6_2_i_fu_729_p2;
wire   [0:0] tmp_18_fu_735_p3;
wire   [0:0] tmp_120_2_i_fu_749_p2;
wire   [0:0] rev2_fu_743_p2;
wire   [0:0] tmp_19_fu_760_p3;
wire   [31:0] p_assign_7_2_i_fu_768_p2;
wire   [31:0] p_p2_i497_i_2_i_fu_774_p3;
wire   [0:0] tmp_131_i_fu_656_p2;
wire   [31:0] p_assign_8_i_fu_661_p2;
wire   [0:0] or_cond_i496_i_i_fu_628_p2;
wire   [31:0] p_p2_i497_i_i_p_assig_fu_792_p3;
wire   [0:0] tmp_131_1_i_fu_719_p2;
wire   [31:0] p_assign_8_1_i_fu_724_p2;
wire   [0:0] or_cond_i496_i_1_i_fu_691_p2;
wire   [31:0] p_p2_i497_i_1_i_p_ass_fu_808_p3;
wire   [0:0] tmp_131_2_i_fu_782_p2;
wire   [31:0] p_assign_8_2_i_fu_787_p2;
wire   [0:0] or_cond_i496_i_2_i_fu_754_p2;
wire   [31:0] p_p2_i497_i_2_i_p_ass_fu_824_p3;
wire   [31:0] row_assign_8_i_fu_845_p2;
wire   [31:0] row_assign_8_1_i_fu_853_p2;
wire   [31:0] row_assign_8_2_i_fu_861_p2;
wire   [30:0] tmp_23_fu_880_p4;
wire   [31:0] ImagLoc_x_fu_896_p2;
wire   [0:0] tmp_24_fu_902_p3;
wire   [0:0] tmp_6_i_fu_916_p2;
wire   [0:0] rev3_fu_910_p2;
wire   [0:0] tmp_25_fu_927_p3;
wire   [31:0] p_assign_1_fu_935_p2;
wire   [31:0] p_p2_i_i_i_fu_941_p3;
wire   [31:0] p_assign_2_fu_954_p2;
wire   [0:0] tmp_6_i_not_fu_967_p2;
wire   [0:0] tmp_8_i_fu_949_p2;
wire   [0:0] sel_tmp7_fu_973_p2;
wire   [0:0] sel_tmp8_fu_979_p2;
wire   [31:0] p_assign_3_fu_959_p3;
wire   [0:0] icmp1_fu_890_p2;
wire   [31:0] col_assign_1_fu_1003_p2;
wire   [7:0] tmp_3_fu_1035_p5;
wire   [7:0] tmp_4_fu_1053_p5;
wire   [7:0] tmp_5_fu_1071_p5;
wire   [7:0] tmp_6_fu_1125_p5;
wire   [7:0] tmp_7_fu_1143_p5;
wire   [7:0] tmp_8_fu_1161_p5;
wire   [7:0] r_V_2_0_i_fu_1201_p0;
wire  signed [7:0] r_V_2_0_i_fu_1201_p1;
wire  signed [15:0] r_V_2_0_i_fu_1201_p2;
wire   [7:0] r_V_2_1_i_fu_1218_p0;
wire  signed [7:0] r_V_2_1_i_fu_1218_p1;
wire   [7:0] r_V_2_2_1_i_fu_1231_p0;
wire  signed [7:0] r_V_2_2_1_i_fu_1231_p1;
wire  signed [15:0] r_V_2_2_1_i_fu_1231_p2;
wire  signed [16:0] grp_fu_1458_p3;
wire  signed [17:0] sum_V_0_1_cast_i_fu_1279_p1;
wire  signed [17:0] tmp19_cast_fu_1288_p1;
wire   [7:0] r_V_2_1_2_i_fu_1304_p0;
wire  signed [7:0] r_V_2_1_2_i_fu_1304_p1;
(* use_dsp48 = "no" *) wire   [16:0] tmp_s_fu_1291_p2;
wire   [7:0] tmp_29_fu_1312_p1;
wire   [7:0] tmp_30_fu_1316_p1;
wire  signed [18:0] tmp_138_1_2_cast_i_fu_1335_p1;
wire  signed [18:0] sum_V_1_cast_i_fu_1332_p1;
wire   [18:0] tmp12_fu_1338_p2;
wire  signed [18:0] tmp23_cast_fu_1344_p1;
wire   [18:0] sum_V_2_1_i_fu_1347_p2;
wire   [7:0] r_V_2_2_2_i_fu_1360_p0;
wire  signed [7:0] r_V_2_2_2_i_fu_1360_p1;
wire  signed [15:0] r_V_2_2_2_i_fu_1360_p2;
wire  signed [19:0] tmp_138_2_2_i_fu_1365_p1;
wire  signed [19:0] sum_V_2_1_cast_i_fu_1353_p1;
wire   [19:0] p_Val2_s_fu_1377_p2;
wire   [7:0] tmp_32_fu_1373_p1;
wire   [7:0] tmp_2_fu_1369_p2;
wire   [11:0] p_Result_1_i_i_i_fu_1397_p4;
wire   [0:0] tmp_i_i_i_fu_1413_p2;
wire   [0:0] overflow_fu_1418_p2;
wire   [0:0] tmp_1_i_i_i_fu_1431_p2;
wire   [7:0] p_mux_i_i_cast_i_fu_1423_p3;
wire   [7:0] grp_fu_1444_p0;
wire  signed [7:0] grp_fu_1444_p1;
wire   [7:0] grp_fu_1451_p0;
wire  signed [7:0] grp_fu_1451_p1;
wire   [7:0] grp_fu_1458_p0;
wire  signed [7:0] grp_fu_1458_p1;
wire   [7:0] grp_fu_1467_p0;
wire  signed [7:0] grp_fu_1467_p1;
reg   [4:0] ap_NS_fsm;
reg    ap_block_pp0;
reg    ap_enable_operation_164;
reg    ap_enable_state5_pp0_iter1_stage0;
reg    ap_enable_operation_181;
reg    ap_enable_state6_pp0_iter2_stage0;
reg    ap_predicate_op195_store_state6;
reg    ap_enable_operation_195;
reg    ap_predicate_op202_store_state6;
reg    ap_enable_operation_202;
reg    ap_enable_operation_167;
reg    ap_enable_operation_184;
reg    ap_predicate_op193_store_state6;
reg    ap_enable_operation_193;
reg    ap_predicate_op200_store_state6;
reg    ap_enable_operation_200;
reg    ap_predicate_op169_load_state5;
reg    ap_enable_operation_169;
reg    ap_predicate_op187_load_state6;
reg    ap_enable_operation_187;
reg    ap_predicate_op191_store_state6;
reg    ap_enable_operation_191;
reg    ap_predicate_op199_store_state6;
reg    ap_enable_operation_199;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [15:0] grp_fu_1444_p00;
wire   [15:0] grp_fu_1451_p00;
wire   [15:0] grp_fu_1458_p00;
wire   [15:0] grp_fu_1467_p00;
wire   [15:0] r_V_2_0_i_fu_1201_p00;
wire   [15:0] r_V_2_1_2_i_fu_1304_p00;
wire   [15:0] r_V_2_1_i_fu_1218_p00;
wire   [15:0] r_V_2_2_1_i_fu_1231_p00;
wire   [15:0] r_V_2_2_2_i_fu_1360_p00;
reg    ap_condition_1167;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
end

Filter2D_k_buf_0_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_3_address0),
    .ce0(k_buf_0_val_3_ce0),
    .q0(k_buf_0_val_3_q0),
    .address1(k_buf_0_val_3_address1),
    .ce1(k_buf_0_val_3_ce1),
    .we1(k_buf_0_val_3_we1),
    .d1(p_src_data_stream_V_dout)
);

Filter2D_k_buf_0_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_4_address0),
    .ce0(k_buf_0_val_4_ce0),
    .q0(k_buf_0_val_4_q0),
    .address1(k_buf_0_val_4_address1),
    .ce1(k_buf_0_val_4_ce1),
    .we1(k_buf_0_val_4_we1),
    .d1(k_buf_0_val_4_d1)
);

Filter2D_k_buf_0_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_5_address0),
    .ce0(k_buf_0_val_5_ce0),
    .q0(k_buf_0_val_5_q0),
    .address1(k_buf_0_val_5_address1),
    .ce1(k_buf_0_val_5_ce1),
    .we1(k_buf_0_val_5_we1),
    .d1(k_buf_0_val_5_d1)
);

filter2D_hls_mux_eOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
filter2D_hls_mux_eOg_U21(
    .din0(right_border_buf_0_s_fu_280),
    .din1(right_border_buf_0_1_fu_284),
    .din2(8'd0),
    .din3(tmp_26_reg_1753),
    .dout(tmp_3_fu_1035_p5)
);

filter2D_hls_mux_eOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
filter2D_hls_mux_eOg_U22(
    .din0(right_border_buf_0_3_fu_292),
    .din1(right_border_buf_0_4_fu_296),
    .din2(8'd0),
    .din3(tmp_26_reg_1753),
    .dout(tmp_4_fu_1053_p5)
);

filter2D_hls_mux_eOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
filter2D_hls_mux_eOg_U23(
    .din0(right_border_buf_0_5_fu_300),
    .din1(right_border_buf_0_2_fu_288),
    .din2(8'd0),
    .din3(tmp_26_reg_1753),
    .dout(tmp_5_fu_1071_p5)
);

filter2D_hls_mux_eOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
filter2D_hls_mux_eOg_U24(
    .din0(col_buf_0_val_0_0_fu_1046_p3),
    .din1(col_buf_0_val_1_0_fu_1064_p3),
    .din2(col_buf_0_val_2_0_fu_1082_p3),
    .din3(tmp_20_reg_1702),
    .dout(tmp_6_fu_1125_p5)
);

filter2D_hls_mux_eOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
filter2D_hls_mux_eOg_U25(
    .din0(col_buf_0_val_0_0_fu_1046_p3),
    .din1(col_buf_0_val_1_0_fu_1064_p3),
    .din2(col_buf_0_val_2_0_fu_1082_p3),
    .din3(tmp_21_reg_1707),
    .dout(tmp_7_fu_1143_p5)
);

filter2D_hls_mux_eOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
filter2D_hls_mux_eOg_U26(
    .din0(col_buf_0_val_0_0_fu_1046_p3),
    .din1(col_buf_0_val_1_0_fu_1064_p3),
    .din2(col_buf_0_val_2_0_fu_1082_p3),
    .din3(tmp_22_reg_1712),
    .dout(tmp_8_fu_1161_p5)
);

filter2D_hls_mac_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
filter2D_hls_mac_fYi_U27(
    .din0(grp_fu_1444_p0),
    .din1(grp_fu_1444_p1),
    .din2(r_V_2_0_i_fu_1201_p2),
    .dout(grp_fu_1444_p3)
);

filter2D_hls_mac_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
filter2D_hls_mac_fYi_U28(
    .din0(grp_fu_1451_p0),
    .din1(grp_fu_1451_p1),
    .din2(r_V_2_2_1_i_fu_1231_p2),
    .dout(grp_fu_1451_p3)
);

filter2D_hls_mac_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
filter2D_hls_mac_fYi_U29(
    .din0(grp_fu_1458_p0),
    .din1(grp_fu_1458_p1),
    .din2(r_V_2_1_i_reg_1798),
    .dout(grp_fu_1458_p3)
);

filter2D_hls_mac_g8j #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 18 ))
filter2D_hls_mac_g8j_U30(
    .din0(grp_fu_1467_p0),
    .din1(grp_fu_1467_p1),
    .din2(tmp13_reg_1803),
    .dout(grp_fu_1467_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((exitcond461_i_i_fu_554_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((exitcond460_i_i_fu_869_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter2_state6)) begin
                ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter1;
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            ap_enable_reg_pp0_iter5 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond460_i_i_fu_869_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        t_V_1_reg_459 <= j_V_fu_874_p2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        t_V_1_reg_459 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        t_V_reg_448 <= i_V_reg_1652;
    end else if ((~((p_kernel_val_2_V_2_empty_n == 1'b0) | (p_kernel_val_2_V_1_empty_n == 1'b0) | (p_kernel_val_2_V_0_empty_n == 1'b0) | (p_kernel_val_1_V_2_empty_n == 1'b0) | (p_kernel_val_1_V_1_empty_n == 1'b0) | (p_kernel_val_1_V_0_empty_n == 1'b0) | (p_kernel_val_0_V_2_empty_n == 1'b0) | (p_kernel_val_0_V_1_empty_n == 1'b0) | (p_kernel_val_0_V_0_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        t_V_reg_448 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond460_i_i_fu_869_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        brmerge_i_reg_1736 <= brmerge_i_fu_993_p2;
        or_cond_i_i_i_reg_1726 <= or_cond_i_i_i_fu_921_p2;
        or_cond_i_i_reg_1743 <= or_cond_i_i_fu_998_p2;
        x_reg_1730 <= x_fu_985_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        brmerge_i_reg_1736_pp0_iter1_reg <= brmerge_i_reg_1736;
        exitcond460_i_i_reg_1717 <= exitcond460_i_i_fu_869_p2;
        exitcond460_i_i_reg_1717_pp0_iter1_reg <= exitcond460_i_i_reg_1717;
        or_cond_i_i_i_reg_1726_pp0_iter1_reg <= or_cond_i_i_i_reg_1726;
        or_cond_i_i_reg_1743_pp0_iter1_reg <= or_cond_i_i_reg_1743;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_V_reg_1652 <= i_V_fu_559_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond461_i_i_fu_554_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        icmp_reg_1662 <= icmp_fu_580_p2;
        tmp_115_i_reg_1675 <= tmp_115_i_fu_598_p2;
        tmp_2_i_reg_1657 <= tmp_2_i_fu_565_p2;
        tmp_93_1_i_reg_1671 <= tmp_93_1_i_fu_592_p2;
        tmp_93_i_reg_1667 <= tmp_93_i_fu_586_p2;
        y_1_i_reg_1687 <= y_1_i_fu_816_p3;
        y_2_i_reg_1692 <= y_2_i_fu_832_p3;
        y_i_reg_1682 <= y_i_fu_800_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond460_i_i_reg_1717 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_buf_0_val_3_addr_reg_1747 <= tmp_58_i_fu_1007_p1;
        k_buf_0_val_4_addr_reg_1760 <= tmp_58_i_fu_1007_p1;
        k_buf_0_val_5_addr_reg_1766 <= tmp_58_i_fu_1007_p1;
        tmp_26_reg_1753 <= tmp_26_fu_1013_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_i_reg_1743_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        not_i_i_i_reg_1844 <= not_i_i_i_fu_1407_p2;
        p_Result_s_reg_1833 <= p_Val2_s_fu_1377_p2[32'd19];
        p_Val2_1_reg_1839 <= p_Val2_1_fu_1391_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        or_cond_i_i_reg_1743_pp0_iter2_reg <= or_cond_i_i_reg_1743_pp0_iter1_reg;
        or_cond_i_i_reg_1743_pp0_iter3_reg <= or_cond_i_i_reg_1743_pp0_iter2_reg;
        or_cond_i_i_reg_1743_pp0_iter4_reg <= or_cond_i_i_reg_1743_pp0_iter3_reg;
        src_kernel_win_0_va_6_reg_1772_pp0_iter3_reg <= src_kernel_win_0_va_6_reg_1772;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_i_reg_1743_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        r_V_2_1_2_i_reg_1813 <= r_V_2_1_2_i_fu_1304_p2;
        sum_V_1_i_reg_1808 <= sum_V_1_i_fu_1295_p2;
        tmp_1_reg_1823 <= tmp_1_fu_1323_p2;
        tmp_31_reg_1828 <= tmp_31_fu_1329_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_i_reg_1743_pp0_iter1_reg == 1'd1) & (exitcond460_i_i_reg_1717_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        r_V_2_1_i_reg_1798 <= r_V_2_1_i_fu_1218_p2;
        src_kernel_win_0_va_10_reg_1787 <= src_kernel_win_0_va_1_fu_260;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_i_reg_1657 == 1'd1) & (icmp_reg_1662 == 1'd1) & (or_cond_i_i_i_reg_1726_pp0_iter1_reg == 1'd1) & (exitcond460_i_i_reg_1717_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        right_border_buf_0_1_fu_284 <= right_border_buf_0_s_fu_280;
        right_border_buf_0_2_fu_288 <= right_border_buf_0_5_fu_300;
        right_border_buf_0_3_fu_292 <= col_buf_0_val_1_0_fu_1064_p3;
        right_border_buf_0_4_fu_296 <= right_border_buf_0_3_fu_292;
        right_border_buf_0_5_fu_300 <= col_buf_0_val_2_0_fu_1082_p3;
        right_border_buf_0_s_fu_280 <= col_buf_0_val_0_0_fu_1046_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond460_i_i_reg_1717_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        src_kernel_win_0_va_1_fu_260 <= src_kernel_win_0_va_fu_256;
        src_kernel_win_0_va_2_fu_264 <= src_kernel_win_0_va_7_fu_1154_p3;
        src_kernel_win_0_va_3_fu_268 <= src_kernel_win_0_va_2_fu_264;
        src_kernel_win_0_va_4_fu_272 <= src_kernel_win_0_va_8_fu_1172_p3;
        src_kernel_win_0_va_5_fu_276 <= src_kernel_win_0_va_4_fu_272;
        src_kernel_win_0_va_fu_256 <= src_kernel_win_0_va_6_fu_1136_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond460_i_i_reg_1717_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_6_reg_1772 <= src_kernel_win_0_va_6_fu_1136_p3;
        src_kernel_win_0_va_7_reg_1777 <= src_kernel_win_0_va_7_fu_1154_p3;
        src_kernel_win_0_va_8_reg_1782 <= src_kernel_win_0_va_8_fu_1172_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_i_reg_1743_pp0_iter1_reg == 1'd1) & (exitcond460_i_i_reg_1717_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        sum_V_0_1_i_reg_1792 <= grp_fu_1444_p3;
        tmp13_reg_1803 <= grp_fu_1451_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_i_reg_1743_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        tmp14_reg_1818 <= grp_fu_1467_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((p_kernel_val_2_V_2_empty_n == 1'b0) | (p_kernel_val_2_V_1_empty_n == 1'b0) | (p_kernel_val_2_V_0_empty_n == 1'b0) | (p_kernel_val_1_V_2_empty_n == 1'b0) | (p_kernel_val_1_V_1_empty_n == 1'b0) | (p_kernel_val_1_V_0_empty_n == 1'b0) | (p_kernel_val_0_V_2_empty_n == 1'b0) | (p_kernel_val_0_V_1_empty_n == 1'b0) | (p_kernel_val_0_V_0_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        tmp_137_0_1_i_reg_1604 <= tmp_137_0_1_i_fu_510_p1;
        tmp_137_0_2_i_reg_1609 <= tmp_137_0_2_i_fu_514_p1;
        tmp_137_0_i_reg_1599 <= tmp_137_0_i_fu_506_p1;
        tmp_137_1_1_i_reg_1619 <= tmp_137_1_1_i_fu_522_p1;
        tmp_137_1_2_i_reg_1624 <= tmp_137_1_2_i_fu_526_p1;
        tmp_137_1_i_reg_1614 <= tmp_137_1_i_fu_518_p1;
        tmp_137_2_1_i_reg_1634 <= tmp_137_2_1_i_fu_534_p1;
        tmp_137_2_2_i_reg_1639 <= tmp_137_2_2_i_fu_538_p1;
        tmp_137_2_i_reg_1629 <= tmp_137_2_i_fu_530_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_115_i_reg_1675 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        tmp_20_reg_1702 <= tmp_20_fu_849_p1;
        tmp_21_reg_1707 <= tmp_21_fu_857_p1;
        tmp_22_reg_1712 <= tmp_22_fu_865_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        tmp_48_0_not_i_reg_1697 <= tmp_48_0_not_i_fu_840_p2;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_condition_pp0_exit_iter2_state6 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter2_state6 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond461_i_i_fu_554_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond461_i_i_fu_554_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_buf_0_val_3_ce0 = 1'b1;
    end else begin
        k_buf_0_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_2_i_reg_1657 == 1'd1) & (icmp_reg_1662 == 1'd1) & (or_cond_i_i_i_reg_1726_pp0_iter1_reg == 1'd1) & (exitcond460_i_i_reg_1717_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_93_i_reg_1667 == 1'd1) & (or_cond_i_i_i_reg_1726_pp0_iter1_reg == 1'd1) & (icmp_reg_1662 == 1'd0) & (exitcond460_i_i_reg_1717_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        k_buf_0_val_3_ce1 = 1'b1;
    end else begin
        k_buf_0_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_2_i_reg_1657 == 1'd1) & (icmp_reg_1662 == 1'd1) & (or_cond_i_i_i_reg_1726_pp0_iter1_reg == 1'd1) & (exitcond460_i_i_reg_1717_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_93_i_reg_1667 == 1'd1) & (or_cond_i_i_i_reg_1726_pp0_iter1_reg == 1'd1) & (icmp_reg_1662 == 1'd0) & (exitcond460_i_i_reg_1717_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        k_buf_0_val_3_we1 = 1'b1;
    end else begin
        k_buf_0_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_buf_0_val_4_ce0 = 1'b1;
    end else begin
        k_buf_0_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_2_i_reg_1657 == 1'd1) & (icmp_reg_1662 == 1'd1) & (or_cond_i_i_i_reg_1726_pp0_iter1_reg == 1'd1) & (exitcond460_i_i_reg_1717_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_93_1_i_reg_1671 == 1'd1) & (or_cond_i_i_i_reg_1726_pp0_iter1_reg == 1'd1) & (icmp_reg_1662 == 1'd0) & (exitcond460_i_i_reg_1717_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        k_buf_0_val_4_ce1 = 1'b1;
    end else begin
        k_buf_0_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1167)) begin
        if (((tmp_2_i_reg_1657 == 1'd1) & (icmp_reg_1662 == 1'd1))) begin
            k_buf_0_val_4_d1 = k_buf_0_val_3_q0;
        end else if (((tmp_93_1_i_reg_1671 == 1'd1) & (icmp_reg_1662 == 1'd0))) begin
            k_buf_0_val_4_d1 = p_src_data_stream_V_dout;
        end else begin
            k_buf_0_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_2_i_reg_1657 == 1'd1) & (icmp_reg_1662 == 1'd1) & (or_cond_i_i_i_reg_1726_pp0_iter1_reg == 1'd1) & (exitcond460_i_i_reg_1717_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_93_1_i_reg_1671 == 1'd1) & (or_cond_i_i_i_reg_1726_pp0_iter1_reg == 1'd1) & (icmp_reg_1662 == 1'd0) & (exitcond460_i_i_reg_1717_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        k_buf_0_val_4_we1 = 1'b1;
    end else begin
        k_buf_0_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_buf_0_val_5_ce0 = 1'b1;
    end else begin
        k_buf_0_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_2_i_reg_1657 == 1'd1) & (icmp_reg_1662 == 1'd1) & (or_cond_i_i_i_reg_1726_pp0_iter1_reg == 1'd1) & (exitcond460_i_i_reg_1717_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_93_i_reg_1667 == 1'd1) & (or_cond_i_i_i_reg_1726_pp0_iter1_reg == 1'd1) & (icmp_reg_1662 == 1'd0) & (exitcond460_i_i_reg_1717_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        k_buf_0_val_5_ce1 = 1'b1;
    end else begin
        k_buf_0_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1167)) begin
        if (((tmp_2_i_reg_1657 == 1'd1) & (icmp_reg_1662 == 1'd1))) begin
            k_buf_0_val_5_d1 = k_buf_0_val_4_q0;
        end else if (((tmp_93_i_reg_1667 == 1'd1) & (icmp_reg_1662 == 1'd0))) begin
            k_buf_0_val_5_d1 = p_src_data_stream_V_dout;
        end else begin
            k_buf_0_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_2_i_reg_1657 == 1'd1) & (icmp_reg_1662 == 1'd1) & (or_cond_i_i_i_reg_1726_pp0_iter1_reg == 1'd1) & (exitcond460_i_i_reg_1717_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_93_i_reg_1667 == 1'd1) & (or_cond_i_i_i_reg_1726_pp0_iter1_reg == 1'd1) & (icmp_reg_1662 == 1'd0) & (exitcond460_i_i_reg_1717_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        k_buf_0_val_5_we1 = 1'b1;
    end else begin
        k_buf_0_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond_i_i_reg_1743_pp0_iter4_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        p_dst_data_stream_V_blk_n = p_dst_data_stream_V_full_n;
    end else begin
        p_dst_data_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_i_i_reg_1743_pp0_iter4_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        p_dst_data_stream_V_write = 1'b1;
    end else begin
        p_dst_data_stream_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_kernel_val_0_V_0_blk_n = p_kernel_val_0_V_0_empty_n;
    end else begin
        p_kernel_val_0_V_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((p_kernel_val_2_V_2_empty_n == 1'b0) | (p_kernel_val_2_V_1_empty_n == 1'b0) | (p_kernel_val_2_V_0_empty_n == 1'b0) | (p_kernel_val_1_V_2_empty_n == 1'b0) | (p_kernel_val_1_V_1_empty_n == 1'b0) | (p_kernel_val_1_V_0_empty_n == 1'b0) | (p_kernel_val_0_V_2_empty_n == 1'b0) | (p_kernel_val_0_V_1_empty_n == 1'b0) | (p_kernel_val_0_V_0_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_kernel_val_0_V_0_read = 1'b1;
    end else begin
        p_kernel_val_0_V_0_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_kernel_val_0_V_1_blk_n = p_kernel_val_0_V_1_empty_n;
    end else begin
        p_kernel_val_0_V_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((p_kernel_val_2_V_2_empty_n == 1'b0) | (p_kernel_val_2_V_1_empty_n == 1'b0) | (p_kernel_val_2_V_0_empty_n == 1'b0) | (p_kernel_val_1_V_2_empty_n == 1'b0) | (p_kernel_val_1_V_1_empty_n == 1'b0) | (p_kernel_val_1_V_0_empty_n == 1'b0) | (p_kernel_val_0_V_2_empty_n == 1'b0) | (p_kernel_val_0_V_1_empty_n == 1'b0) | (p_kernel_val_0_V_0_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_kernel_val_0_V_1_read = 1'b1;
    end else begin
        p_kernel_val_0_V_1_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_kernel_val_0_V_2_blk_n = p_kernel_val_0_V_2_empty_n;
    end else begin
        p_kernel_val_0_V_2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((p_kernel_val_2_V_2_empty_n == 1'b0) | (p_kernel_val_2_V_1_empty_n == 1'b0) | (p_kernel_val_2_V_0_empty_n == 1'b0) | (p_kernel_val_1_V_2_empty_n == 1'b0) | (p_kernel_val_1_V_1_empty_n == 1'b0) | (p_kernel_val_1_V_0_empty_n == 1'b0) | (p_kernel_val_0_V_2_empty_n == 1'b0) | (p_kernel_val_0_V_1_empty_n == 1'b0) | (p_kernel_val_0_V_0_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_kernel_val_0_V_2_read = 1'b1;
    end else begin
        p_kernel_val_0_V_2_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_kernel_val_1_V_0_blk_n = p_kernel_val_1_V_0_empty_n;
    end else begin
        p_kernel_val_1_V_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((p_kernel_val_2_V_2_empty_n == 1'b0) | (p_kernel_val_2_V_1_empty_n == 1'b0) | (p_kernel_val_2_V_0_empty_n == 1'b0) | (p_kernel_val_1_V_2_empty_n == 1'b0) | (p_kernel_val_1_V_1_empty_n == 1'b0) | (p_kernel_val_1_V_0_empty_n == 1'b0) | (p_kernel_val_0_V_2_empty_n == 1'b0) | (p_kernel_val_0_V_1_empty_n == 1'b0) | (p_kernel_val_0_V_0_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_kernel_val_1_V_0_read = 1'b1;
    end else begin
        p_kernel_val_1_V_0_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_kernel_val_1_V_1_blk_n = p_kernel_val_1_V_1_empty_n;
    end else begin
        p_kernel_val_1_V_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((p_kernel_val_2_V_2_empty_n == 1'b0) | (p_kernel_val_2_V_1_empty_n == 1'b0) | (p_kernel_val_2_V_0_empty_n == 1'b0) | (p_kernel_val_1_V_2_empty_n == 1'b0) | (p_kernel_val_1_V_1_empty_n == 1'b0) | (p_kernel_val_1_V_0_empty_n == 1'b0) | (p_kernel_val_0_V_2_empty_n == 1'b0) | (p_kernel_val_0_V_1_empty_n == 1'b0) | (p_kernel_val_0_V_0_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_kernel_val_1_V_1_read = 1'b1;
    end else begin
        p_kernel_val_1_V_1_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_kernel_val_1_V_2_blk_n = p_kernel_val_1_V_2_empty_n;
    end else begin
        p_kernel_val_1_V_2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((p_kernel_val_2_V_2_empty_n == 1'b0) | (p_kernel_val_2_V_1_empty_n == 1'b0) | (p_kernel_val_2_V_0_empty_n == 1'b0) | (p_kernel_val_1_V_2_empty_n == 1'b0) | (p_kernel_val_1_V_1_empty_n == 1'b0) | (p_kernel_val_1_V_0_empty_n == 1'b0) | (p_kernel_val_0_V_2_empty_n == 1'b0) | (p_kernel_val_0_V_1_empty_n == 1'b0) | (p_kernel_val_0_V_0_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_kernel_val_1_V_2_read = 1'b1;
    end else begin
        p_kernel_val_1_V_2_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_kernel_val_2_V_0_blk_n = p_kernel_val_2_V_0_empty_n;
    end else begin
        p_kernel_val_2_V_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((p_kernel_val_2_V_2_empty_n == 1'b0) | (p_kernel_val_2_V_1_empty_n == 1'b0) | (p_kernel_val_2_V_0_empty_n == 1'b0) | (p_kernel_val_1_V_2_empty_n == 1'b0) | (p_kernel_val_1_V_1_empty_n == 1'b0) | (p_kernel_val_1_V_0_empty_n == 1'b0) | (p_kernel_val_0_V_2_empty_n == 1'b0) | (p_kernel_val_0_V_1_empty_n == 1'b0) | (p_kernel_val_0_V_0_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_kernel_val_2_V_0_read = 1'b1;
    end else begin
        p_kernel_val_2_V_0_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_kernel_val_2_V_1_blk_n = p_kernel_val_2_V_1_empty_n;
    end else begin
        p_kernel_val_2_V_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((p_kernel_val_2_V_2_empty_n == 1'b0) | (p_kernel_val_2_V_1_empty_n == 1'b0) | (p_kernel_val_2_V_0_empty_n == 1'b0) | (p_kernel_val_1_V_2_empty_n == 1'b0) | (p_kernel_val_1_V_1_empty_n == 1'b0) | (p_kernel_val_1_V_0_empty_n == 1'b0) | (p_kernel_val_0_V_2_empty_n == 1'b0) | (p_kernel_val_0_V_1_empty_n == 1'b0) | (p_kernel_val_0_V_0_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_kernel_val_2_V_1_read = 1'b1;
    end else begin
        p_kernel_val_2_V_1_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_kernel_val_2_V_2_blk_n = p_kernel_val_2_V_2_empty_n;
    end else begin
        p_kernel_val_2_V_2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((p_kernel_val_2_V_2_empty_n == 1'b0) | (p_kernel_val_2_V_1_empty_n == 1'b0) | (p_kernel_val_2_V_0_empty_n == 1'b0) | (p_kernel_val_1_V_2_empty_n == 1'b0) | (p_kernel_val_1_V_1_empty_n == 1'b0) | (p_kernel_val_1_V_0_empty_n == 1'b0) | (p_kernel_val_0_V_2_empty_n == 1'b0) | (p_kernel_val_0_V_1_empty_n == 1'b0) | (p_kernel_val_0_V_0_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_kernel_val_2_V_2_read = 1'b1;
    end else begin
        p_kernel_val_2_V_2_read = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_2_i_reg_1657 == 1'd1) & (icmp_reg_1662 == 1'd1) & (or_cond_i_i_i_reg_1726_pp0_iter1_reg == 1'd1) & (exitcond460_i_i_reg_1717_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((or_cond_i_i_i_reg_1726_pp0_iter1_reg == 1'd1) & (icmp_reg_1662 == 1'd0) & (exitcond460_i_i_reg_1717_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        p_src_data_stream_V_blk_n = p_src_data_stream_V_empty_n;
    end else begin
        p_src_data_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op201_read_state6 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op190_read_state6 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        p_src_data_stream_V_read = 1'b1;
    end else begin
        p_src_data_stream_V_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((p_kernel_val_2_V_2_empty_n == 1'b0) | (p_kernel_val_2_V_1_empty_n == 1'b0) | (p_kernel_val_2_V_0_empty_n == 1'b0) | (p_kernel_val_1_V_2_empty_n == 1'b0) | (p_kernel_val_1_V_1_empty_n == 1'b0) | (p_kernel_val_1_V_0_empty_n == 1'b0) | (p_kernel_val_0_V_2_empty_n == 1'b0) | (p_kernel_val_0_V_1_empty_n == 1'b0) | (p_kernel_val_0_V_0_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond461_i_i_fu_554_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) & ~((ap_enable_reg_pp0_iter4 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter5 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_enable_reg_pp0_iter4 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter5 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ImagLoc_x_fu_896_p2 = ($signed(32'd4294967295) + $signed(t_V_1_reg_459));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_pp0 = ((ap_ST_fsm_pp0_stage0 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage0_subdone));
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op201_read_state6 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op190_read_state6 == 1'b1)))) | ((or_cond_i_i_reg_1743_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op201_read_state6 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op190_read_state6 == 1'b1)))) | ((or_cond_i_i_reg_1743_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter2 == 1'b1) & (((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op201_read_state6 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op190_read_state6 == 1'b1)))) | ((or_cond_i_i_reg_1743_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1)));
end

always @ (*) begin
    ap_block_state1 = ((p_kernel_val_2_V_2_empty_n == 1'b0) | (p_kernel_val_2_V_1_empty_n == 1'b0) | (p_kernel_val_2_V_0_empty_n == 1'b0) | (p_kernel_val_1_V_2_empty_n == 1'b0) | (p_kernel_val_1_V_1_empty_n == 1'b0) | (p_kernel_val_1_V_0_empty_n == 1'b0) | (p_kernel_val_0_V_2_empty_n == 1'b0) | (p_kernel_val_0_V_1_empty_n == 1'b0) | (p_kernel_val_0_V_0_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state4_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state6_pp0_stage0_iter2 = (((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op201_read_state6 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op190_read_state6 == 1'b1)));
end

assign ap_block_state7_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state9_pp0_stage0_iter5 = ((or_cond_i_i_reg_1743_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_V_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_1167 = ((or_cond_i_i_i_reg_1726_pp0_iter1_reg == 1'd1) & (exitcond460_i_i_reg_1717_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_enable_operation_164 = (exitcond460_i_i_reg_1717 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_167 = (exitcond460_i_i_reg_1717 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_169 = (ap_predicate_op169_load_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_181 = (exitcond460_i_i_reg_1717_pp0_iter1_reg == 1'd0);
end

always @ (*) begin
    ap_enable_operation_184 = (exitcond460_i_i_reg_1717_pp0_iter1_reg == 1'd0);
end

always @ (*) begin
    ap_enable_operation_187 = (ap_predicate_op187_load_state6 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_191 = (ap_predicate_op191_store_state6 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_193 = (ap_predicate_op193_store_state6 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_195 = (ap_predicate_op195_store_state6 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_199 = (ap_predicate_op199_store_state6 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_200 = (ap_predicate_op200_store_state6 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_202 = (ap_predicate_op202_store_state6 == 1'b1);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_enable_state5_pp0_iter1_stage0 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state6_pp0_iter2_stage0 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_predicate_op169_load_state5 = ((brmerge_i_reg_1736 == 1'd1) & (exitcond460_i_i_reg_1717 == 1'd0));
end

always @ (*) begin
    ap_predicate_op187_load_state6 = ((brmerge_i_reg_1736_pp0_iter1_reg == 1'd1) & (exitcond460_i_i_reg_1717_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op190_read_state6 = ((or_cond_i_i_i_reg_1726_pp0_iter1_reg == 1'd1) & (icmp_reg_1662 == 1'd0) & (exitcond460_i_i_reg_1717_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op191_store_state6 = ((tmp_93_i_reg_1667 == 1'd1) & (or_cond_i_i_i_reg_1726_pp0_iter1_reg == 1'd1) & (icmp_reg_1662 == 1'd0) & (exitcond460_i_i_reg_1717_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op193_store_state6 = ((tmp_93_1_i_reg_1671 == 1'd1) & (or_cond_i_i_i_reg_1726_pp0_iter1_reg == 1'd1) & (icmp_reg_1662 == 1'd0) & (exitcond460_i_i_reg_1717_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op195_store_state6 = ((tmp_93_i_reg_1667 == 1'd1) & (or_cond_i_i_i_reg_1726_pp0_iter1_reg == 1'd1) & (icmp_reg_1662 == 1'd0) & (exitcond460_i_i_reg_1717_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op199_store_state6 = ((tmp_2_i_reg_1657 == 1'd1) & (icmp_reg_1662 == 1'd1) & (or_cond_i_i_i_reg_1726_pp0_iter1_reg == 1'd1) & (exitcond460_i_i_reg_1717_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op200_store_state6 = ((tmp_2_i_reg_1657 == 1'd1) & (icmp_reg_1662 == 1'd1) & (or_cond_i_i_i_reg_1726_pp0_iter1_reg == 1'd1) & (exitcond460_i_i_reg_1717_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op201_read_state6 = ((tmp_2_i_reg_1657 == 1'd1) & (icmp_reg_1662 == 1'd1) & (or_cond_i_i_i_reg_1726_pp0_iter1_reg == 1'd1) & (exitcond460_i_i_reg_1717_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op202_store_state6 = ((tmp_2_i_reg_1657 == 1'd1) & (icmp_reg_1662 == 1'd1) & (or_cond_i_i_i_reg_1726_pp0_iter1_reg == 1'd1) & (exitcond460_i_i_reg_1717_pp0_iter1_reg == 1'd0));
end

assign brmerge_i_fu_993_p2 = (tmp_6_i_fu_916_p2 | tmp_48_0_not_i_reg_1697);

assign col_assign_1_fu_1003_p2 = (tmp_11_i_fu_488_p2 - x_reg_1730);

assign col_buf_0_val_0_0_fu_1046_p3 = ((brmerge_i_reg_1736_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_0_val_3_q0 : tmp_3_fu_1035_p5);

assign col_buf_0_val_1_0_fu_1064_p3 = ((brmerge_i_reg_1736_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_0_val_4_q0 : tmp_4_fu_1053_p5);

assign col_buf_0_val_2_0_fu_1082_p3 = ((brmerge_i_reg_1736_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_0_val_5_q0 : tmp_5_fu_1071_p5);

assign exitcond460_i_i_fu_869_p2 = ((t_V_1_reg_459 == tmp_i_fu_470_p2) ? 1'b1 : 1'b0);

assign exitcond461_i_i_fu_554_p2 = ((t_V_reg_448 == tmp_1_i_fu_476_p2) ? 1'b1 : 1'b0);

assign grp_fu_1444_p0 = grp_fu_1444_p00;

assign grp_fu_1444_p00 = src_kernel_win_0_va_4_fu_272;

assign grp_fu_1444_p1 = tmp_137_0_1_i_reg_1604;

assign grp_fu_1451_p0 = grp_fu_1451_p00;

assign grp_fu_1451_p00 = src_kernel_win_0_va_2_fu_264;

assign grp_fu_1451_p1 = tmp_137_1_1_i_reg_1619;

assign grp_fu_1458_p0 = grp_fu_1458_p00;

assign grp_fu_1458_p00 = src_kernel_win_0_va_8_reg_1782;

assign grp_fu_1458_p1 = tmp_137_0_2_i_reg_1609;

assign grp_fu_1467_p0 = grp_fu_1467_p00;

assign grp_fu_1467_p00 = src_kernel_win_0_va_10_reg_1787;

assign grp_fu_1467_p1 = tmp_137_2_i_reg_1629;

assign i_V_fu_559_p2 = (t_V_reg_448 + 32'd1);

assign icmp1_fu_890_p2 = ((tmp_23_fu_880_p4 != 31'd0) ? 1'b1 : 1'b0);

assign icmp_fu_580_p2 = ((tmp_11_fu_570_p4 != 31'd0) ? 1'b1 : 1'b0);

assign j_V_fu_874_p2 = (t_V_1_reg_459 + 32'd1);

assign k_buf_0_val_3_address0 = tmp_58_i_fu_1007_p1;

assign k_buf_0_val_3_address1 = k_buf_0_val_3_addr_reg_1747;

assign k_buf_0_val_4_address0 = tmp_58_i_fu_1007_p1;

assign k_buf_0_val_4_address1 = k_buf_0_val_4_addr_reg_1760;

assign k_buf_0_val_5_address0 = tmp_58_i_fu_1007_p1;

assign k_buf_0_val_5_address1 = k_buf_0_val_5_addr_reg_1766;

assign not_i_i_i_fu_1407_p2 = ((p_Result_1_i_i_i_fu_1397_p4 != 12'd0) ? 1'b1 : 1'b0);

assign or_cond_i496_i_1_i_fu_691_p2 = (tmp_120_1_i_fu_686_p2 & rev1_fu_680_p2);

assign or_cond_i496_i_2_i_fu_754_p2 = (tmp_120_2_i_fu_749_p2 & rev2_fu_743_p2);

assign or_cond_i496_i_i_fu_628_p2 = (tmp_120_i_fu_623_p2 & rev_fu_617_p2);

assign or_cond_i_i_fu_998_p2 = (icmp_reg_1662 & icmp1_fu_890_p2);

assign or_cond_i_i_i_fu_921_p2 = (tmp_6_i_fu_916_p2 & rev3_fu_910_p2);

assign overflow_fu_1418_p2 = (tmp_i_i_i_fu_1413_p2 & not_i_i_i_reg_1844);

assign p_Result_1_i_i_i_fu_1397_p4 = {{p_Val2_s_fu_1377_p2[19:8]}};

assign p_Val2_1_fu_1391_p2 = (tmp_32_fu_1373_p1 + tmp_2_fu_1369_p2);

assign p_Val2_s_fu_1377_p2 = ($signed(tmp_138_2_2_i_fu_1365_p1) + $signed(sum_V_2_1_cast_i_fu_1353_p1));

assign p_assign_1_fu_935_p2 = (32'd1 - t_V_1_reg_459);

assign p_assign_2_fu_954_p2 = (tmp_10_i_fu_548_p2 - p_p2_i_i_i_fu_941_p3);

assign p_assign_3_fu_959_p3 = ((or_cond_i_i_i_fu_921_p2[0:0] === 1'b1) ? ImagLoc_x_fu_896_p2 : p_assign_2_fu_954_p2);

assign p_assign_6_1_i_fu_666_p2 = ($signed(32'd4294967294) + $signed(t_V_reg_448));

assign p_assign_6_2_i_fu_729_p2 = ($signed(32'd4294967293) + $signed(t_V_reg_448));

assign p_assign_7_1_i_fu_705_p2 = (32'd2 - t_V_reg_448);

assign p_assign_7_2_i_fu_768_p2 = (32'd3 - t_V_reg_448);

assign p_assign_7_i_fu_642_p2 = (32'd1 - t_V_reg_448);

assign p_assign_8_1_i_fu_724_p2 = (tmp_133_i_fu_500_p2 - p_p2_i497_i_1_i_fu_711_p3);

assign p_assign_8_2_i_fu_787_p2 = (tmp_133_i_fu_500_p2 - p_p2_i497_i_2_i_fu_774_p3);

assign p_assign_8_i_fu_661_p2 = (tmp_133_i_fu_500_p2 - p_p2_i497_i_i_fu_648_p3);

assign p_dst_data_stream_V_din = ((tmp_1_i_i_i_fu_1431_p2[0:0] === 1'b1) ? p_mux_i_i_cast_i_fu_1423_p3 : p_Val2_1_reg_1839);

assign p_mux_i_i_cast_i_fu_1423_p3 = ((tmp_i_i_i_fu_1413_p2[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign p_neg465_i_i_fu_482_p2 = ($signed(32'd4294967295) + $signed(p_src_rows_V));

assign p_p2_i497_i_1_i_fu_711_p3 = ((tmp_17_fu_697_p3[0:0] === 1'b1) ? p_assign_7_1_i_fu_705_p2 : p_assign_6_1_i_fu_666_p2);

assign p_p2_i497_i_1_i_p_ass_fu_808_p3 = ((tmp_131_1_i_fu_719_p2[0:0] === 1'b1) ? p_p2_i497_i_1_i_fu_711_p3 : p_assign_8_1_i_fu_724_p2);

assign p_p2_i497_i_2_i_fu_774_p3 = ((tmp_19_fu_760_p3[0:0] === 1'b1) ? p_assign_7_2_i_fu_768_p2 : p_assign_6_2_i_fu_729_p2);

assign p_p2_i497_i_2_i_p_ass_fu_824_p3 = ((tmp_131_2_i_fu_782_p2[0:0] === 1'b1) ? p_p2_i497_i_2_i_fu_774_p3 : p_assign_8_2_i_fu_787_p2);

assign p_p2_i497_i_i_fu_648_p3 = ((tmp_13_fu_634_p3[0:0] === 1'b1) ? p_assign_7_i_fu_642_p2 : tmp_118_i_fu_603_p2);

assign p_p2_i497_i_i_p_assig_fu_792_p3 = ((tmp_131_i_fu_656_p2[0:0] === 1'b1) ? p_p2_i497_i_i_fu_648_p3 : p_assign_8_i_fu_661_p2);

assign p_p2_i_i_i_fu_941_p3 = ((tmp_25_fu_927_p3[0:0] === 1'b1) ? p_assign_1_fu_935_p2 : ImagLoc_x_fu_896_p2);

assign r_V_2_0_i_fu_1201_p0 = r_V_2_0_i_fu_1201_p00;

assign r_V_2_0_i_fu_1201_p00 = src_kernel_win_0_va_5_fu_276;

assign r_V_2_0_i_fu_1201_p1 = tmp_137_0_i_reg_1599;

assign r_V_2_0_i_fu_1201_p2 = ($signed({{1'b0}, {r_V_2_0_i_fu_1201_p0}}) * $signed(r_V_2_0_i_fu_1201_p1));

assign r_V_2_1_2_i_fu_1304_p0 = r_V_2_1_2_i_fu_1304_p00;

assign r_V_2_1_2_i_fu_1304_p00 = src_kernel_win_0_va_7_reg_1777;

assign r_V_2_1_2_i_fu_1304_p1 = tmp_137_1_2_i_reg_1624;

assign r_V_2_1_2_i_fu_1304_p2 = ($signed({{1'b0}, {r_V_2_1_2_i_fu_1304_p0}}) * $signed(r_V_2_1_2_i_fu_1304_p1));

assign r_V_2_1_i_fu_1218_p0 = r_V_2_1_i_fu_1218_p00;

assign r_V_2_1_i_fu_1218_p00 = src_kernel_win_0_va_3_fu_268;

assign r_V_2_1_i_fu_1218_p1 = tmp_137_1_i_reg_1614;

assign r_V_2_1_i_fu_1218_p2 = ($signed({{1'b0}, {r_V_2_1_i_fu_1218_p0}}) * $signed(r_V_2_1_i_fu_1218_p1));

assign r_V_2_2_1_i_fu_1231_p0 = r_V_2_2_1_i_fu_1231_p00;

assign r_V_2_2_1_i_fu_1231_p00 = src_kernel_win_0_va_fu_256;

assign r_V_2_2_1_i_fu_1231_p1 = tmp_137_2_1_i_reg_1634;

assign r_V_2_2_1_i_fu_1231_p2 = ($signed({{1'b0}, {r_V_2_2_1_i_fu_1231_p0}}) * $signed(r_V_2_2_1_i_fu_1231_p1));

assign r_V_2_2_2_i_fu_1360_p0 = r_V_2_2_2_i_fu_1360_p00;

assign r_V_2_2_2_i_fu_1360_p00 = src_kernel_win_0_va_6_reg_1772_pp0_iter3_reg;

assign r_V_2_2_2_i_fu_1360_p1 = tmp_137_2_2_i_reg_1639;

assign r_V_2_2_2_i_fu_1360_p2 = ($signed({{1'b0}, {r_V_2_2_2_i_fu_1360_p0}}) * $signed(r_V_2_2_2_i_fu_1360_p1));

assign rev1_fu_680_p2 = (tmp_16_fu_672_p3 ^ 1'd1);

assign rev2_fu_743_p2 = (tmp_18_fu_735_p3 ^ 1'd1);

assign rev3_fu_910_p2 = (tmp_24_fu_902_p3 ^ 1'd1);

assign rev_fu_617_p2 = (tmp_12_fu_609_p3 ^ 1'd1);

assign row_assign_8_1_i_fu_853_p2 = (p_neg465_i_i_fu_482_p2 - y_1_i_reg_1687);

assign row_assign_8_2_i_fu_861_p2 = (p_neg465_i_i_fu_482_p2 - y_2_i_reg_1692);

assign row_assign_8_i_fu_845_p2 = (p_neg465_i_i_fu_482_p2 - y_i_reg_1682);

assign sel_tmp7_fu_973_p2 = (tmp_6_i_not_fu_967_p2 | tmp_24_fu_902_p3);

assign sel_tmp8_fu_979_p2 = (tmp_8_i_fu_949_p2 & sel_tmp7_fu_973_p2);

assign src_kernel_win_0_va_6_fu_1136_p3 = ((tmp_115_i_reg_1675[0:0] === 1'b1) ? tmp_6_fu_1125_p5 : col_buf_0_val_0_0_fu_1046_p3);

assign src_kernel_win_0_va_7_fu_1154_p3 = ((tmp_115_i_reg_1675[0:0] === 1'b1) ? tmp_7_fu_1143_p5 : col_buf_0_val_1_0_fu_1064_p3);

assign src_kernel_win_0_va_8_fu_1172_p3 = ((tmp_115_i_reg_1675[0:0] === 1'b1) ? tmp_8_fu_1161_p5 : col_buf_0_val_2_0_fu_1082_p3);

assign sum_V_0_1_cast_i_fu_1279_p1 = sum_V_0_1_i_reg_1792;

assign sum_V_1_cast_i_fu_1332_p1 = $signed(sum_V_1_i_reg_1808);

assign sum_V_1_i_fu_1295_p2 = ($signed(sum_V_0_1_cast_i_fu_1279_p1) + $signed(tmp19_cast_fu_1288_p1));

assign sum_V_2_1_cast_i_fu_1353_p1 = $signed(sum_V_2_1_i_fu_1347_p2);

assign sum_V_2_1_i_fu_1347_p2 = ($signed(tmp12_fu_1338_p2) + $signed(tmp23_cast_fu_1344_p1));

assign tmp12_fu_1338_p2 = ($signed(tmp_138_1_2_cast_i_fu_1335_p1) + $signed(sum_V_1_cast_i_fu_1332_p1));

assign tmp19_cast_fu_1288_p1 = grp_fu_1458_p3;

assign tmp23_cast_fu_1344_p1 = tmp14_reg_1818;

assign tmp_10_i_fu_548_p2 = ($signed(32'd4294967294) + $signed(tmp_9_fu_542_p2));

assign tmp_115_i_fu_598_p2 = ((t_V_reg_448 > p_src_rows_V) ? 1'b1 : 1'b0);

assign tmp_118_i_fu_603_p2 = ($signed(32'd4294967295) + $signed(t_V_reg_448));

assign tmp_11_fu_570_p4 = {{t_V_reg_448[31:1]}};

assign tmp_11_i_fu_488_p2 = (32'd3 + p_src_cols_V);

assign tmp_120_1_i_fu_686_p2 = (($signed(p_assign_6_1_i_fu_666_p2) < $signed(p_src_rows_V)) ? 1'b1 : 1'b0);

assign tmp_120_2_i_fu_749_p2 = (($signed(p_assign_6_2_i_fu_729_p2) < $signed(p_src_rows_V)) ? 1'b1 : 1'b0);

assign tmp_120_i_fu_623_p2 = (($signed(tmp_118_i_fu_603_p2) < $signed(p_src_rows_V)) ? 1'b1 : 1'b0);

assign tmp_12_fu_609_p3 = tmp_118_i_fu_603_p2[32'd31];

assign tmp_131_1_i_fu_719_p2 = (($signed(p_p2_i497_i_1_i_fu_711_p3) < $signed(p_src_rows_V)) ? 1'b1 : 1'b0);

assign tmp_131_2_i_fu_782_p2 = (($signed(p_p2_i497_i_2_i_fu_774_p3) < $signed(p_src_rows_V)) ? 1'b1 : 1'b0);

assign tmp_131_i_fu_656_p2 = (($signed(p_p2_i497_i_i_fu_648_p3) < $signed(p_src_rows_V)) ? 1'b1 : 1'b0);

assign tmp_133_i_fu_500_p2 = (32'd2 + tmp_fu_494_p2);

assign tmp_137_0_1_i_fu_510_p1 = $signed(p_kernel_val_0_V_1_dout);

assign tmp_137_0_2_i_fu_514_p1 = $signed(p_kernel_val_0_V_2_dout);

assign tmp_137_0_i_fu_506_p1 = $signed(p_kernel_val_0_V_0_dout);

assign tmp_137_1_1_i_fu_522_p1 = $signed(p_kernel_val_1_V_1_dout);

assign tmp_137_1_2_i_fu_526_p1 = $signed(p_kernel_val_1_V_2_dout);

assign tmp_137_1_i_fu_518_p1 = $signed(p_kernel_val_1_V_0_dout);

assign tmp_137_2_1_i_fu_534_p1 = $signed(p_kernel_val_2_V_1_dout);

assign tmp_137_2_2_i_fu_538_p1 = $signed(p_kernel_val_2_V_2_dout);

assign tmp_137_2_i_fu_530_p1 = $signed(p_kernel_val_2_V_0_dout);

assign tmp_138_1_2_cast_i_fu_1335_p1 = r_V_2_1_2_i_reg_1813;

assign tmp_138_2_2_i_fu_1365_p1 = r_V_2_2_2_i_fu_1360_p2;

assign tmp_13_fu_634_p3 = tmp_118_i_fu_603_p2[32'd31];

assign tmp_16_fu_672_p3 = p_assign_6_1_i_fu_666_p2[32'd31];

assign tmp_17_fu_697_p3 = p_assign_6_1_i_fu_666_p2[32'd31];

assign tmp_18_fu_735_p3 = p_assign_6_2_i_fu_729_p2[32'd31];

assign tmp_19_fu_760_p3 = p_assign_6_2_i_fu_729_p2[32'd31];

assign tmp_1_fu_1323_p2 = (tmp_29_fu_1312_p1 + tmp_30_fu_1316_p1);

assign tmp_1_i_fu_476_p2 = (32'd2 + p_src_rows_V);

assign tmp_1_i_i_i_fu_1431_p2 = (p_Result_s_reg_1833 | overflow_fu_1418_p2);

assign tmp_20_fu_849_p1 = row_assign_8_i_fu_845_p2[1:0];

assign tmp_21_fu_857_p1 = row_assign_8_1_i_fu_853_p2[1:0];

assign tmp_22_fu_865_p1 = row_assign_8_2_i_fu_861_p2[1:0];

assign tmp_23_fu_880_p4 = {{t_V_1_reg_459[31:1]}};

assign tmp_24_fu_902_p3 = ImagLoc_x_fu_896_p2[32'd31];

assign tmp_25_fu_927_p3 = ImagLoc_x_fu_896_p2[32'd31];

assign tmp_26_fu_1013_p1 = col_assign_1_fu_1003_p2[1:0];

assign tmp_29_fu_1312_p1 = tmp_s_fu_1291_p2[7:0];

assign tmp_2_fu_1369_p2 = (tmp_31_reg_1828 + tmp_1_reg_1823);

assign tmp_2_i_fu_565_p2 = ((t_V_reg_448 < p_src_rows_V) ? 1'b1 : 1'b0);

assign tmp_30_fu_1316_p1 = r_V_2_1_2_i_fu_1304_p2[7:0];

assign tmp_31_fu_1329_p1 = grp_fu_1467_p3[7:0];

assign tmp_32_fu_1373_p1 = r_V_2_2_2_i_fu_1360_p2[7:0];

assign tmp_48_0_not_i_fu_840_p2 = (tmp_2_i_reg_1657 ^ 1'd1);

assign tmp_58_i_fu_1007_p1 = x_reg_1730;

assign tmp_6_i_fu_916_p2 = (($signed(ImagLoc_x_fu_896_p2) < $signed(p_src_cols_V)) ? 1'b1 : 1'b0);

assign tmp_6_i_not_fu_967_p2 = (tmp_6_i_fu_916_p2 ^ 1'd1);

assign tmp_8_i_fu_949_p2 = (($signed(p_p2_i_i_i_fu_941_p3) < $signed(p_src_cols_V)) ? 1'b1 : 1'b0);

assign tmp_93_1_i_fu_592_p2 = ((t_V_reg_448 == 32'd0) ? 1'b1 : 1'b0);

assign tmp_93_i_fu_586_p2 = ((t_V_reg_448 == 32'd1) ? 1'b1 : 1'b0);

assign tmp_9_fu_542_p2 = p_src_cols_V << 32'd1;

assign tmp_fu_494_p2 = p_src_rows_V << 32'd1;

assign tmp_i_fu_470_p2 = (32'd2 + p_src_cols_V);

assign tmp_i_i_i_fu_1413_p2 = (p_Result_s_reg_1833 ^ 1'd1);

assign tmp_s_fu_1291_p2 = ($signed(grp_fu_1458_p3) + $signed(sum_V_0_1_i_reg_1792));

assign x_fu_985_p3 = ((sel_tmp8_fu_979_p2[0:0] === 1'b1) ? p_p2_i_i_i_fu_941_p3 : p_assign_3_fu_959_p3);

assign y_1_i_fu_816_p3 = ((or_cond_i496_i_1_i_fu_691_p2[0:0] === 1'b1) ? p_assign_6_1_i_fu_666_p2 : p_p2_i497_i_1_i_p_ass_fu_808_p3);

assign y_2_i_fu_832_p3 = ((or_cond_i496_i_2_i_fu_754_p2[0:0] === 1'b1) ? p_assign_6_2_i_fu_729_p2 : p_p2_i497_i_2_i_p_ass_fu_824_p3);

assign y_i_fu_800_p3 = ((or_cond_i496_i_i_fu_628_p2[0:0] === 1'b1) ? tmp_118_i_fu_603_p2 : p_p2_i497_i_i_p_assig_fu_792_p3);

endmodule //Filter2D
